### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by GreatFireWall** [erdewit/ib_insync#105]
```
Python Version: Python 3.6.5 :: Anaconda, Inc.
```
```
IB API Version: 9.73.7
```
```
TWS Version:
Build 973.2l, Oct 16, 2018 12:12:21 PM 
Jolt Build 1.9.6, Jul 19, 2018 06:39:19 PM 
Nia Build 2.16.0, Feb 2, 2018 12:12:24 PM 
ModelNav Build 1.7.10, Jul 13, 2018 02:47:50 PM 
Riskfeed Build 2.31.4, Sep 14, 2018 01:46:10 PM  
Java Version: 1.8.0_152, OS: Windows 10 (amd64, 10.0), Memory: heap max 768Mb, current 319Mb
```

![image](https://user-images.githubusercontent.com/4510984/47513628-3aac9500-d8b1-11e8-9830-be98ad482286.png)

**Comment by erdewit** [comment]
This is a bug in IBAPI which makes it a responsibility of IB.

It looks like your (Chinese?) language settings trigger it, you may try setting TWS to English.

**Comment by GreatFireWall** [comment]
yes, Chinese.
But is there any ways to force IB TWS API always use utf-8 for resolve this issue ?

**Comment by erdewit** [comment]
You can ask IB....

**Comment by GreatFireWall** [comment]
Can I change this in IB Python API source code ?

**Comment by erdewit** [comment]
If you know the encoding used then yes.

**Comment by GreatFireWall** [comment]
thanks, I will be try.
