### ISSUE TITLE
IB.disconnect doesn't work as expected

### ISSUE THREAD

**Issue by valentinmk** [erdewit/ib_insync#106]
I am trying to handle reconnect in some asyncio project. But I have stucked with `clientId 1 already in use?` error. I just unable to execute a correct disconnection from TWS with IB.disconnect() method.
We could reproduce this behavour in jupiter notebook. In first case we connect and disconnect in one jupiter cell and get an error. In second case we split code in multiple cells and all works perfect. 
[Link to more readable gist](https://gist.github.com/valentinmk/c17aef7cda1821f6b22fef3b2e3c25a2)
What I am doing wrong? How it could be fixed?

Example code:
```python
from ib_insync import *
util.startLoop()
ib = IB()
```
##  Run in one cell won't work
```python
ib.connect('10.2.50.121', 4003, clientId=1)
ib.disconnect()
ib.waitOnUpdate(1)
ib.connect('10.2.50.121', 4003, clientId=1)
```
>    ERROR:ib_insync.client:Peer closed connection
>    ERROR:ib_insync.client:clientId 1 already in use?
>    ERROR:ib_insync.client:API connection failed: TimeoutError()
>    ---------------------------------------------------------------------------

> TimeoutError                              Traceback (most recent call last)
>  ...
>    C:\ProgramData\Anaconda3\lib\asyncio\tasks.py in wait_for(fut, timeout, loop)
>        360             fut.remove_done_callback(cb)
>        361             fut.cancel()
>    --> 362             raise futures.TimeoutError()
>        363     finally:
>        364         timeout_handle.cancel()
>    TimeoutError: 
##  Run in multiple cells works as expected
```python
ib.connect('10.2.50.121', 4003, clientId=1)
```
> <IB connected to 10.2.50.121:4003 clientId=1>

```python
ib.disconnect()
ib.waitOnUpdate(1)
```
> True
```python
ib.connect('10.2.50.121', 4003, clientId=1)
```
> <IB connected to 10.2.50.121:4003 clientId=1>

**Comment by erdewit** [comment]
The other side (TWS) can be a bit slow to realize that the client has disconnected. You can try IB.sleep(1) to give it more time. Changing the clientId works too.

**Comment by valentinmk** [comment]
The same behavior with IB.sleep(). I have got first connection in TWS connection manager in active state while second connection starting to execute.
![2018-10-30_15-01-13](https://user-images.githubusercontent.com/12662946/47716762-b5c8cf00-dc54-11e8-88a6-a1b634de7fa6.png)

Code that I am running:
```python
ib.connect('10.2.50.121', 4003, clientId=1)
ib.waitOnUpdate(1)
IB.sleep(1)
ib.disconnect()
ib.waitOnUpdate(1)
IB.sleep(5)
ib.connect('10.2.50.121', 4003, clientId=1)
```

**Comment by erdewit** [comment]
> I have got first connection in TWS connection manager in active state while second connection starting to execute.

That's the whole problem, TWS is actively aborting the second connection. Try sleeping longer. Btw the waitOnUpdate doesn't make sense after disconnecting.

**Comment by valentinmk** [comment]
Well, it's seem a bug of Windows version of `SelectorSocketTransport`
I have modified code like that (I am checking actual state of transport after `disconnect` was called):
```
ib.connect('10.2.50.121', 4003, clientId=100)
ib.sleep(1)
transport = ib.client.conn.socket.transport
print(transport)
print(ib.client.conn)
ib.disconnect()
print(transport)
print(ib.client.conn)
for i in range(2):
    ib.waitOnUpdate(1)
    print(transport)
    print(ib.client.conn)
    ib.sleep(6)
    transport.close()
ib.connect('10.2.50.121', 4003, clientId=100)
```
## On Windows
> <_SelectorSocketTransport fd=1164 read=polling write=<idle, bufsize=0>>
> <ib_insync.client.Connection object at 0x000001424050BF28>
> <_SelectorSocketTransport closing fd=1164 read=idle write=<idle, bufsize=0>>
> None
> <_SelectorSocketTransport closing fd=1164 read=idle write=<idle, bufsize=0>>
> None
> <_SelectorSocketTransport closing fd=1164 read=idle write=<idle, bufsize=0>>
> None
```
ERROR:ib_insync.client:Peer closed connection
ERROR:ib_insync.client:clientId 100 already in use?
ERROR:ib_insync.client:API connection failed: TimeoutError()
```

## On Linux (debian in this case)
> <_SelectorSocketTransport fd=57 read=polling write=<idle, bufsize=0>>
> <ib_insync.client.Connection object at 0x7f7731f45160>
> <_SelectorSocketTransport closed fd=57>
> None
> <_SelectorSocketTransport closed fd=57>
> None
> <_SelectorSocketTransport closed fd=57>
> None
> <IB connected to 10.2.50.121:4003 clientId=100>
