### ISSUE TITLE
Retrieving Data

### ISSUE THREAD

**Issue by schalkw-gmail-com** [erdewit/ib_insync#108]
I'm trying to write an algorithm to be used with Interactive Brokers in Python.

My problem starts at the very beginning, how is the data compiled from the server?

The algo i'm writing requires to run on Heikin Ashi data where each bar is represented by 2000 ticks (physical trades).

Perhaps I'm missing the info  / explanation but I can not find out how the data is returned from IB. 
I see there is a tick and a bar but I cant figure out what is what.

Can you perhaps give me some details on this?

**Comment by ElliotP123** [comment]
I would check IB's API documents. They have limits on bar size for different instruments, historical data availability, etc. If it's available from their API, it's likely available in this package.

**Comment by erdewit** [comment]
Heikin Ashi bars and constant tick volume bars are not available, although they can be constructed from ticks.
