### ISSUE TITLE
Manual orders order status

### ISSUE THREAD

**Issue by mdelvaux** [erdewit/ib_insync#11]
The IB API allows to forward messages related to manual orders to a designated client, identified by the "Master API client ID" in TWS (or IB gateway) settings.  When the ib_insync client is identified as the designated client, the messages received are not correctly recognized, I see the following error reported

ERROR:ib_insync.wrapper:orderStatus: No order found for orderId 0 and clientId 0
ERROR:ib_insync.wrapper:orderStatus: No order found for orderId 0 and clientId 0
ERROR:ib_insync.wrapper:orderStatus: No order found for orderId 0 and clientId 0

There are multiple errors because there are multiple status messages for each order.  Surprisingly all orders seem also tagged with the same orderId, i.e. a later message will get the same orderId.  It is my first time experimenting with such a designated client, so I am not really sure about the expected format of the messages, i.e. how can messages be grouped meaningfully if they all have the same orderId.

I am not sure what would be the best method to handle these, possibly:
- filter them out completely, so that no error message is reported
- put them in a predefined bucket for orderId 0
- something else?

**Comment by erdewit** [comment]
The code has been updated so that manually submitted orders or orders from other API clients are now ignored.
