### ISSUE TITLE
ib.portfolio() and ib.accountValues() update every 20 minutes

### ISSUE THREAD

**Issue by shlomikushchi** [erdewit/ib_insync#112]
Hi, I'm working with v0.9.38 (worked with 0.9.27 previously with the same issue )
I'm trying to do this:

```
ib = IB()
ib.connect('127.0.0.1', 7497)
ib.portfolio()
ib.accountValues()
```

and the values seem to update every 20 minutes give or take 

how do I make it update constantly? (every X seconds)

tried to run in and out of market hours.

**Comment by erdewit** [comment]
If there's no event loop running then nothing will get updated. So either have some form of event loop running, or force updates with ib.sleep(0).

**Comment by shlomikushchi** [comment]
I am using this 
```
from ib_insync.util import sleep
while True:
    ib.portfolio()
    ib.accountValues()
    sleep(5)

```

and this still doesn't work

how should the event loop be dealt with?

**Comment by shlomikushchi** [comment]
@erdewit 
also, inside `ib.connect()` we have this:
```
    self._run(self.connectAsync(host, port, clientId, timeout))
    return self
```
which in turn does that:

```
return util.run(*awaitables, timeout=self.RequestTimeout)
```
which is doing the `loop.run_forever()`
so it seems we do have the event loop running 
also, as I mentioned it updates every 20 minutes if I run it constantly...

**Comment by erdewit** [comment]
The loop in ib.connect() will stop once connected. The while loop with util.sleep(5) does look proper and will keep portfolio and account values updated. If they stay the same then there are just no changes.

**Comment by shlomikushchi** [comment]
@erdewit I have TWS opened. 
not only that there are constant changes in TWS (as I said - during market hours.. so for instance right now)
when there is a change with this code lines - the values are incorrect:
![image](https://user-images.githubusercontent.com/7924802/49172404-a6b76880-f349-11e8-9b19-9d656bb5366a.png)


where `stocksValue` is derived from `GrossPositionValue` (from `ib.accountValues()`)


and again - the values change somewhere between 15 to 20 minutes

**Comment by shlomikushchi** [comment]
so it doesn't seem like I'm using the code in a wrong way?
should I make a script with the code I'm using so you can debug it ?

**Comment by erdewit** [comment]
The code is okay although I don't know if GrossPositionValue corresponds to what TWS shows (there are so many account value keys). You can turn on debug logging to see the network traffic for yourself.

**Comment by shlomikushchi** [comment]
@erdewit is it possible to set the update interval? haven't found a way to do that... (if we set aside the values for now.. it's still updates every 15 minutes. ) 
is it possible to set it to every X seconds somehow?

**Comment by erdewit** [comment]
No idea why the updates come so infrequent for you, for me they come every couple minutes or so, or after a trade. Perhaps ask IB.
