### ISSUE TITLE
ib python api version compatibility

### ISSUE THREAD

**Issue by ustcyue** [erdewit/ib_insync#114]
I follow the instruction to downloaded the twsapi_macunix.974.01 from http://interactivebrokers.github.io/. But after unzip I found the python api version inside is still 9.73.7. Did anyone successfully downloaded python 9.74.01 from IB website?

**Comment by ustcyue** [comment]
seems IB just forgot to update the version string ...

**Comment by hadrianl** [comment]
so far, I got no problem with 9.73.7(except encoding problems!!!)

**Comment by erdewit** [comment]
Yes, IB forgot to set the version info again. You can use [util.ibapiVersionInfo()](https://rawgit.com/erdewit/ib_insync/master/docs/html/api.html#ib_insync.util.ibapiVersionInfo) instead to find the real version.
