### ISSUE TITLE
question about encoding！

### ISSUE THREAD

**Issue by hadrianl** [erdewit/ib_insync#115]
Hi.I'm from China.I found out that ibapi is not well support with Chinese.I always got an encoding error when I qualify the Stocks.It seems that ibapi is decoding with utf8 while my TWS is using ANSI.I wonder if ib_insync can fix this.Thanks!
So far, I figured out `ibapi.utils.decode` and `ibapi.decoder.Decoder.interpretWithSignature`  that could cause this problem.

**Comment by hadrianl** [comment]
by the way，my platfrom is win10

**Comment by erdewit** [comment]
This is an issue with ibapi and therefore within the area of responsibility of IB.

You could edit the ibapi code to set the encoding though.
