### ISSUE TITLE
BUG with latest ipykernel!

### ISSUE THREAD

**Issue by hadrianl** [erdewit/ib_insync#120]
It seems that util.startloop() was not working after I got ipykernel updated!

**Comment by hadrianl** [comment]
It is ok when downgrade to 4.10.0 but not latest 5.1.0

**Comment by erdewit** [comment]
Version 5 and higher have a running asyncio loop that needs to be patched. Use either util.startLoop(), util.patchAsyncio() or nest_asyncio.apply().
