### ISSUE TITLE
qualifyContract not finding 20190215 monthly expiration

### ISSUE THREAD

**Issue by filipeh** [erdewit/ib_insync#122]
qualifyContracts and reqContractDetails are not able to locate any 20190215 monthly expiration for any symbol. Here is an example. It is returning weeklies for Feb only.

ib.qualifyContracts(Contract(symbol='DBX', secType='OPT', lastTradeDateOrContractMonth='20190215', strike=20.5, right='C', multiplier='100', exchange='SMART', currency='USD'))
Error 200, reqId 404: No security definition has been found for the request, contract: Contract(secType='OPT', symbol='DBX', lastTradeDateOrContractMonth='20190215', strike=20.5, right='C', multiplier='100', exchange='SMART', currency='USD')
Unknown contract: Contract(secType='OPT', symbol='DBX', lastTradeDateOrContractMonth='20190215', strike=20.5, right='C', multiplier='100', exchange='SMART', currency='USD')
Out[2]: []
ib.qualifyContracts(Contract(symbol='DBX', secType='OPT', lastTradeDateOrContractMonth='201902', strike=20.5, right='C', multiplier='100', exchange='SMART', currency='USD'))
Ambiguous contract: Contract(secType='OPT', symbol='DBX', lastTradeDateOrContractMonth='201902', strike=20.5, right='C', multiplier='100', exchange='SMART', currency='USD'), possibles are [Option(conId=345643133, symbol='DBX', lastTradeDateOrContractMonth='20190201', strike=20.5, right='C', multiplier='100', exchange='SMART', currency='USD', localSymbol='DBX   190201C00020500', tradingClass='DBX'), Option(conId=347637843, symbol='DBX', lastTradeDateOrContractMonth='20190208', strike=20.5, right='C', multiplier='100', exchange='SMART', currency='USD', localSymbol='DBX   190208C00020500', tradingClass='DBX')]
Out[3]: []
ib.qualifyContracts(Contract(symbol='DBX', secType='OPT', lastTradeDateOrContractMonth='201902', strike=20.5, right='C', multiplier='100', exchange='CBOE', currency='USD'))
Ambiguous contract: Contract(secType='OPT', symbol='DBX', lastTradeDateOrContractMonth='201902', strike=20.5, right='C', multiplier='100', exchange='CBOE', currency='USD'), possibles are [Option(conId=345643133, symbol='DBX', lastTradeDateOrContractMonth='20190201', strike=20.5, right='C', multiplier='100', exchange='CBOE', currency='USD', localSymbol='DBX   190201C00020500', tradingClass='DBX'), Option(conId=347637843, symbol='DBX', lastTradeDateOrContractMonth='20190208', strike=20.5, right='C', multiplier='100', exchange='CBOE', currency='USD', localSymbol='DBX   190208C00020500', tradingClass='DBX')]
Out[4]: []
ib.qualifyContracts(Contract(symbol='DBX', secType='OPT', lastTradeDateOrContractMonth='201902', strike=20.5, right='C', multiplier='100', primaryExchange='CBOE', currency='USD'))
Ambiguous contract: Contract(secType='OPT', symbol='DBX', lastTradeDateOrContractMonth='201902', strike=20.5, right='C', multiplier='100', primaryExchange='CBOE', currency='USD'), possibles are [Option(conId=345643133, symbol='DBX', lastTradeDateOrContractMonth='20190201', strike=20.5, right='C', multiplier='100', exchange='CBOE', currency='USD', localSymbol='DBX   190201C00020500', tradingClass='DBX'), Option(conId=347637843, symbol='DBX', lastTradeDateOrContractMonth='20190208', strike=20.5, right='C', multiplier='100', exchange='CBOE', currency='USD', localSymbol='DBX   190208C00020500', tradingClass='DBX')]
Out[5]: []
ib.qualifyContracts(Contract(symbol='DBX', secType='OPT', lastTradeDateOrContractMonth='20190215', strike=20.5, right='C', multiplier='100', primaryExchange='CBOE', currency='USD'))
Out[6]: []
Error 200, reqId 408: No security definition has been found for the request, contract: Contract(secType='OPT', symbol='DBX', lastTradeDateOrContractMonth='20190215', strike=20.5, right='C', multiplier='100', primaryExchange='CBOE', currency='USD')
Unknown contract: Contract(secType='OPT', symbol='DBX', lastTradeDateOrContractMonth='20190215', strike=20.5, right='C', multiplier='100', primaryExchange='CBOE', currency='USD')

**Comment by erdewit** [comment]
If I do
```python
c = Option(symbol='DBX', strike=20.5, right='C', multiplier='100', primaryExchange='CBOE', currency='USD')
util.df(cd.contract for cd in ib.reqContractDetails(c))
```
then the feb 15 contract is simply not available from IB - you can ask them why.
