### ISSUE TITLE
AllOpenOrders

### ISSUE THREAD

**Issue by hadrianl** [erdewit/ib_insync#125]
I wonder why "AllOpenOrders" is not accessed.Sometimes, I might need to get all openorders in non-Master Client

**Comment by hadrianl** [comment]
I just got the new commit reviewed.I think the new commit about reqAllOpenOrders seems to be in conflict with "trades".While calling it,  trade also would change info "AllTrades"

**Comment by hadrianl** [comment]
reqOpenOrders and reqAllOpenOrders share the same callback func "openOrder".So, "startReq" might need different keys to tell these two req apart

**Comment by erdewit** [comment]
Calling ib.reqAllOpenOrders() will also update ib.trades(), etc. This is a good thing I believe and can be used to see all available info (like contract and status). The bad thing is that it will not automatically be kept in-sync and will go stale.

Since reqOpenOrders and reqAllOpenOrders also share openOrdersEnd they may not be used at the same time, so might as well use the same key to simplify the code.

**Comment by erdewit** [comment]
This has been released in v0.9.42

**Comment by quadricanna** [comment]
Will it be possible to check order status using orderid or permId?

**Comment by erdewit** [comment]
> Will it be possible to check order status using orderid or permId?

Sure, ib.trades() etc are just lists that can be filtered by these id's.

**Comment by quadricanna** [comment]
I was able to filter out the order among other orders using permId, but I couldn't go further to filter out **just the status** etc Filled, Cancelled, or PreSubmitted. 
I'm planning to store this information in my database. Following (tuple) is what I'm currently getting. I'm wondering if you can help with your expertise.


(Trade(contract=Stock(conId=319647899, symbol='HUGE', right='?', exchange='SMART', currency='CAD', localSymbol='HUGE', tradingClass='HUGE'), order=Order(softDollarTier=SoftDollarTier(), orderId=12, clientId=777, permId=1234567890, action='BUY', totalQuantity=2500.0, orderType='LMT', lmtPrice=0.15, auxPrice=0.0, tif='GTC', ocaType=3, trailStopPrice=1.15, volatilityType=0, deltaNeutralOrderType='None', deltaNeutralOpenClose='?', referencePriceType=0, account='xxxxxxxx', clearingIntent='IB', adjustedOrderType='None', dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(status='PreSubmitted', remaining=2500.0, permId=1234567890, clientId=777, whyHeld='locate'), fills=[], log=[TradeLogEntry(time=datetime.datetime(2019, 2, 18, 19, 59, 58, 520182, tzinfo=datetime.timezone.utc), status='PreSubmitted', message='')]),)

**Comment by erdewit** [comment]
```
trade.orderStatus.status
```
