### ISSUE TITLE
Getting OrderHistory

### ISSUE THREAD

**Issue by quadricanna** [erdewit/ib_insync#128]
I'm wondering if there is a way to get history of all orders. My bot needs to check some information on past orders to make buy or sell decision.

**Comment by hadrianl** [comment]
History orders is not accessed by ibapi! I`m trying to figure out this as well.....

**Comment by quadricanna** [comment]
Thanks Hadrianl, It is unfortunate this function is not available.

**Comment by hadrianl** [comment]
u can just set TWS to auto export trade data

**Comment by quadricanna** [comment]
Is there is a way to also fetch individual OrderStatus() for example by using orderId or permId as argument since these are unique identifier. All these functions return all orders and it is difficult to work with. Openorders(), orders().

**Comment by hadrianl** [comment]
ib.trades() contain OrderStatus

**Comment by quadricanna** [comment]
ib.trades() does not perform the task. I'm looking for a way to search for orderStatus with OrderId or PermId of existing executed or open orders

**Comment by chengsu99** [comment]
ib.trades() only includes the trading filled today?

**Comment by erdewit** [comment]
> ib.trades() only includes the trading filled today?

Yes. Perhaps you can use FlexReport.

**Comment by chengsu99** [comment]
> > ib.trades() only includes the trading filled today?
> 
> Yes. Perhaps you can use FlexReport.

Thank you. After creating a flexreport, is it automatically updated?

**Comment by hadrianl** [comment]
> ib.trades() only includes the trading filled today?

Base on the setting in TWS. u could get the last 7 days trading filled at most

**Comment by quadricanna** [comment]
> > ib.trades() only includes the trading filled today?
> 
> Base on the setting in TWS. u could get the last 7 days trading filled at most

last 7 days orders will help too but how do you get to this setting?

**Comment by mobeigi** [comment]
Hmm kind of sucks this isn't easily available through the API. I wanted an automatic log of trades and might have to approach it in a different way then.
