### ISSUE TITLE
Get orders status after reconnect?

### ISSUE THREAD

**Issue by eric0470** [erdewit/ib_insync#130]
Hi. Can you explain how to get information about order after "reconnect"? The code below shows the problem. 

```python
import asyncio
from ib_insync import IB, MarketOrder, Future
from ib_insync import util as ib_util


async def main(loop):
    ib_util.patchAsyncio()
    ib = IB()

    await ib.connectAsync('127.0.0.1', 4002, 11, 30)
    await asyncio.sleep(5)

    contract = Future('ES', '20190315', 'GLOBEX')
    order = MarketOrder('BUY', 1, tif='GTC')
    trade = ib.placeOrder(contract, order)
    order_id = order.orderId

    ib.disconnect()
    await asyncio.sleep(5)

    # Connect after disconnect
    await ib.connectAsync('127.0.0.1', 4002, 11, 30)
    await asyncio.sleep(5)

    print('Trades', ib.trades())

    for execution in ib.executions():
        if order_id == execution.orderId:
            print('Found execution', execution)

    print('Orders', ib.orders())

    ib.disconnect()
    await asyncio.sleep(5)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()

    try:
        loop.run_until_complete(main(loop))
    finally:
        loop.close()
```
The result of code above:
```
Trades []
Found execution Execution(execId='0000e1a7.5c46793a.01.01', time=datetime.datetime(2019, 1, 22, 6, 53, 26, tzinfo=datetime.timezone.utc), ... exchange='GLOBEX', side='BOT', shares=1.0, price=2651.0, permId=300501251, clientId=11, orderId=131317, cumQty=1.0, avgPrice=2651.0, lastLiquidity=1)
Orders []
```
I want to know what exactly happens with my order. Is it cancelled, is it  filled, or is it pending? If order is pending, I can see it in openTrades() even after reconnect, but if it cancelled, i can not get information about it. If is filled i can get information about it in executions() by searching with orderId. But can I trust orderId? Is orderId unique value? Can I mark order as cancelled if this order is not in openTrades() and executions()?

**Comment by hadrianl** [comment]
It depends on where the order came from. If the order is from TWS, use permId,Otherwise clientID + orderId

**Comment by erdewit** [comment]
> Can you explain how to get information about order after "reconnect"?

After disconnect the state of the IB object is cleared and the original order is not known anymore. On reconnect the order has been filled already so it is no longer an open order, and these historic orders are not synced on connect. I would suggest to store the orders in a database.
