### ISSUE TITLE
Error massage “Please specify account”

### ISSUE THREAD

**Issue by quadricanna** [erdewit/ib_insync#131]
I have more than 1 account under my username. The algorithm was working fine when there was only 1 account number under my profile. Now, I have 2 account and am getting error to specify account before order can be placed.

Not sure if ib.connect() accept account number as an argument. Can you please confirm how to specify account to run algo on.

Thanks

**Comment by erdewit** [comment]
Set the ``order.account`` before placing it.

**Comment by quadricanna** [comment]
Thanks!

**Comment by aymagee92** [comment]
Thank you for answering this. I was stumped after not seeing this parameter in the documentation and receiving the same error. Is there a way we can update the documentation to show this parameter?
