### ISSUE TITLE
requestFA not returning answer

### ISSUE THREAD

**Issue by Javdat** [erdewit/ib_insync#132]
`requestFA` is returning None, even though both IB gateway and debugging show that there is a return from IB.

Example:
Debugging shows that there is a return from IB.

![screen shot 2019-02-06 at 16 25 51](https://user-images.githubusercontent.com/19429297/52352471-e88d1b00-2a2c-11e9-925f-df385c94073d.png)

But, no return from ib_insync (`print(a)` returns `None`):
![screen shot 2019-02-06 at 16 26 08](https://user-images.githubusercontent.com/19429297/52352518-00649f00-2a2d-11e9-844d-4b7a87479d6c.png)

`ibapi` version: 9.73.7
`ib_insync` version: 0.9.33

**Comment by erdewit** [comment]
This is fixed in the repo.
