### ISSUE TITLE
Error nandling

### ISSUE THREAD

**Issue by AndreyTihonov** [erdewit/ib_insync#134]
Hi there!

Could you explain me how  handle errors?
I found out (https://github.com/erdewit/ib_insync/issues/59 with example
but error raise when I try to run this code

 ib.setCallback('error', onError)
AttributeError: 'IB' object has no attribute 'setCallback'

**Comment by erdewit** [comment]
ib.setCallback has been depreciated to make way for a new event system:

```
ib.errorEvent += onError
```
