### ISSUE TITLE
Continuous futures cannot be hashed

### ISSUE THREAD

**Issue by dyus1983** [erdewit/ib_insync#135]
In case of a regular futures contract:
`fut = ib_insync.Contract(symbol='NQ',
                         secType='FUT',
                         exchange='GLOBEX',
                         lastTradeDateOrContractMonth='20190315',
                         multiplier='20',
                         currency='USD',
                         localSymbol='NQH9',
                         tradingClass='NQ')`
`ib.qualifyContracts(fut)`
`{fut: 'data'}`

The result is ok:
![image](https://user-images.githubusercontent.com/4759148/53732031-d032e380-3ea6-11e9-89c2-b11a29f0ac14.png)

BUT a ValueError is raised when using with continuous futures:
`cont_contract = ib_insync.Contract(symbol='NQ', secType='CONTFUT', exchange='GLOBEX')`
`ib.qualifyContracts(cont_contract)`
`{cont_contract: 'data'}`

![image](https://user-images.githubusercontent.com/4759148/53732360-eb522300-3ea7-11e9-8456-6393514e0418.png)

**Comment by erdewit** [comment]
[From the docs](https://rawgit.com/erdewit/ib_insync/master/docs/html/_modules/ib_insync/contract.html#Contract.isHashable)

**Comment by dyus1983** [comment]
Is there any suggestion to make it hasheable? Convert to a regular futures?

**Comment by erdewit** [comment]
Sure, you create a normal Future based on conId.

**Comment by dyus1983** [comment]
Thank you for your quick response

**Comment by dyus1983** [comment]
Should I just change secType to 'FUT' or do I have to re-qualify the contract in your opinion?

**Comment by dyus1983** [comment]
> [From the docs](https://rawgit.com/erdewit/ib_insync/master/docs/html/_modules/ib_insync/contract.html#Contract.isHashable)

Ewald,
I am keep getting a mess with continuous futures being unhashable.
May I propose a change to the hashing approach?
**From:**
```
class Contract(Object):
    ...
    def __hash__(self):
        if not self.isHashable():
            raise ValueError(f'Contract {self} can\'t be hashed')
        return self.conId
```

**To something like this:**
```
class Contract(Object):
    ...
    def __hash__(self):
        hash_id = self.conId * 10
        if self.conId == 28812380 or self.secType == 'BAG'
            hash_id += 1  # or 'raise ValueError(f'Contract {self} can\'t be hashed')'
        elif self.secType == 'CONTFUT':
            hash_id += 2

        return hash_id
```

Hash numbers will still be unique and continuous futures contracts will be hashable.

Many thanks!
