### ISSUE TITLE
Currency in accountSummary

### ISSUE THREAD

**Issue by MiniXC** [erdewit/ib_insync#136]
I was not able to perform a request equivalent to ``reqAccountSummary(reqAccId, "All", "$LEDGER:ALL")``.
So I looked at the ``reqAccountSummaryAsync`` and found that the ``tags`` argument is ``ibapi.account_summary_tags.AccountSummaryTags.AllTags``, which includes all tags but makes it impossible to request a specific ledger (see [reqAccountSummary](https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#a3e0d55d36cd416639b97ee6e47a86fe9))
````
def reqAccountSummaryAsync(self):
reqId = self.client.getReqId()
future = self.wrapper.startReq(reqId)
self.client.reqAccountSummary(
  reqId, 'All',
  ibapi.account_summary_tags.AccountSummaryTags.AllTags
)
return future
````
I suggest changing ``ibapi.account_summary_tags.AccountSummaryTags.AllTags`` to ``ibapi.account_summary_tags.AccountSummaryTags.AllTags + ',$LEDGER:ALL'`` to not only return base currency.

**Comment by erdewit** [comment]
Thank you for the report. The extra ledger has been added.
