### ISSUE TITLE
The order still in "pendingSubmit".

### ISSUE THREAD

**Issue by fabio11c** [erdewit/ib_insync#138]
Hi, I'm having a problem with the "Ordering" notebook, when I try to place an order, the order stills in the "pendingSubmit" status.

This is the code:

from ib_insync import *
util.startLoop()

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=13)

limitOrder = LimitOrder('BUY', 100, 0.05)
limitTrade = ib.placeOrder(contract, limitOrder)

limitTrade

And when I try to change the quantity of the order, it shows this error message:

"ValueError: invalid literal for int() with base 10: b'1.7976931348623157E308'
ERROR:ib_insync.client:Peer closed connection"

Can you help me?

**Comment by hadrianl** [comment]
it doesn't seem like changing the quantity.u did place a limitOrder.

**Comment by hadrianl** [comment]
just make sure the price and the quantity are available for this contract

**Comment by fabio11c** [comment]
Hi hadrianl, I'm trying this code in a paper trading account.

How can I see if the price and quantity are available for the contract?

**Comment by fabio11c** [comment]
I trying to put prices nearly to the bid/ask and the order stills in "pendingSubmit" status.

**Comment by erdewit** [comment]
A paper trading account only fills orders during market hours (unlike the old edemo account).

I've tried the ordering notebook and it runs okay.
