### ISSUE TITLE
How can I retrieve FuturesOption() prices? 

### ISSUE THREAD

**Issue by SteffenNa** [erdewit/ib_insync#14]
Hello! First of all I want to thank you for this beautiful piece of software.
Would you please be so kind and give me an example of how to retrieve FuturesOptions prices and greeks? Or if you could add that to your notebooks that would be great. 
Am Looking at Option on the 10y Treasury Note Future (IB code is 'ZN'). Tried this to no avail:
`contract = FuturesOption('ZN' , '20170922', 127.5, 'C', 'ECBOT')`
Your help will be much appreciated.

**Comment by erdewit** [comment]
Hi Steffen,
The FuturesOption takes keyword arguments like:
```python
contract = FuturesOption(symbol='ZN' , lastTradeDateOrContractMonth='20170922',
        strike=127.5, right='C', exchange='ECBOT')
```
But it is a valid expectation that this would be the same as for Option. The FuturesOption constructor has been updated to reflect that and your original contract specification will work as is.
