### ISSUE TITLE
Can't set "outsideRth" (Regular Trading Hours)

### ISSUE THREAD

**Issue by yehoshuadimarsky** [erdewit/ib_insync#141]
``` 
In [52]: from ib_insync import Stock

In [53]: aapl = Stock(conId=265598, symbol='AAPL', exchange='SMART')

In [54]: aapl
Out[54]: Stock(conId=265598, symbol='AAPL', exchange='SMART')

In [55]: o = MarketOrder('BUY', 5)

In [56]: o.outsideRth = True

In [57]: ib.placeOrder(aapl, o)
Out[57]: Trade(contract=Stock(conId=265598, symbol='AAPL', exchange='SMART'), order=MarketOrder(orderId=1602, clientId=1, action='BUY', totalQuantity=5, outsideRth=True, account='DU1375550'), orderStatus=OrderStatus(status='PendingSubmit'), fills=[], log=[TradeLogEntry(time=datetime.datetime(2019, 4, 4, 20, 41, 7, 654259, tzinfo=datetime.timezone.utc), status='PendingSubmit', message='')])

In [58]: o.outsideRth
Out[58]: False
```
Doing this at about 4:40 PM EST in New Jersey, after the markets are closed.

Using version 0.9.45

I'm trying to trade outside Regular Trading Hours, so I set the `outsideRth` flag on the order to `True`. But when I submit it, it gets rejected as "after hours", and then RESETS the flag to `False`. Why???

**Comment by erdewit** [comment]
The ``outsideRth`` property is modified on the IB server's end and this is copied back into the orignal order. So it's just following IB's logic, whatever that is.

**Comment by steel3d** [comment]
@erdewit so what is the correct way to place an an order to execute after hours? I know how to do it in TWS, but how to do it with ib_insync? Thanks!
