### ISSUE TITLE
Error: This event loop is already running

### ISSUE THREAD

**Issue by yiorgosn** [erdewit/ib_insync#143]
Hi I am getting this error message now every time i run any ib_insync function with one exception: accountValues() is the only method that returns the correct data.  I reached out to IB and they mentioned that they receive my calls going to them from ib_insync and they reply, so there is possibly a  problem with how ib_insync is lately handling the feedback.

Other error messages i get are: Error 504, reqId -1: Not connected

When I execute method accountValues() after this error as well, it returns the correct data.

**Comment by erdewit** [comment]
https://github.com/erdewit/nest_asyncio

**Comment by yiorgosn** [comment]
Works perfect.  Thank you!

**Comment by jlixfeld** [comment]
Where are you seeing a reference to uvloop?

Looking at util.py, asyncio is imported and the run method calls asyncio functions.
