### ISSUE TITLE
it`s better to provide a param which  determine the default accoutupdate

### ISSUE THREAD

**Issue by hadrianl** [erdewit/ib_insync#149]
https://github.com/erdewit/ib_insync/blob/8981a500d3b6a42de0cbaa755ae3a162e1bdc184/ib_insync/ib.py#L1599

**Comment by erdewit** [comment]
There are updates for all accounts already via reqAccountUpdatesMulti.

Note that reqAccountUpdates can also be canceled and restarted for a different account, isn't that sufficient?

**Comment by hadrianl** [comment]
it seems better  to get a  default option.besides,   with a default option, it`s able to get the  right portfolio information after connection was ready

**Comment by erdewit** [comment]
I've thought about it and think this use case does not warrant an extra parameter.

There's already synchronization of positions of all accounts, and if a user really want the specific Portfolio information of an account it can be done like so:

```
ib.client.reqAccountUpdates(False, ib.wrapper.accounts[0])  # cancel
ib.reqAccountUpdates(desiredAccount)
```
