### ISSUE TITLE
How is to catch realized PnL for an Exercised option?

### ISSUE THREAD

**Issue by 33327** [erdewit/ib_insync#151]
Hi, 
I had couple of put options (friday's expiration) that Auto Exercised. I had an underlying stock balance of 300 Long shares at say 25 dollars avg price. 2 put options strk 30 by Auto Exercise SOLD 200, therefor I made realized PnL on this trade that cleared on Saturday.

I can't seem to be able to pull the Pnl resulted off the API. I see it in UI on TWS without PnL under Trades tab too.

I run ib.executions and ib.fills, but no PnL is listed. How can I go about getting it under this circumstances and moving forward? 
Thanks

**Comment by erdewit** [comment]
You can ask IB.
