### ISSUE TITLE
Market depht, times and sales, OHLC in one line?

### ISSUE THREAD

**Issue by greg2paris** [erdewit/ib_insync#156]
Hello,
First I want to thank you for your awesome work, I have tried to use the official IB api for a while but it is very hard to use.
Then I found your implementation and I could retrive live data in less than 10 minutes.
Your code is very well explained and the exemples are ready to go.

I have one question though, how can I retrive in one single row, the market depth (5 buys levels, and 5 sells levels), times and sales (last trading price and volume in real time), and the Open, High, Low, Close of the current day in every single line?

Since the market depth update frequency is not the same as the times and sales, I would like to record the market depth only when their is a new line in the times and sales.

I will lose a lot of market depht information but it would save a lot of space in the hard drive.

How can I do that?

**Comment by erdewit** [comment]
The ``ib.pendingTickersEvent`` or ``ticker.updateEvent`` events can be used. with an event handler that checks if there are any ``ticker.ticksByTicks`` (i.e. if there are any new Time & Sale ticks):

```python
def onPendingTickers(tickers):
    for ticker in tickers:
        if ticker.tickByTicks:
            write(...)

ib.pendingTickersEvent += onPendingTickers
```

**Comment by greg2paris** [comment]
I dont understand what is ib.pendingTickersEvent += onPendingTickers doing 
is this "+=" doing a loop?
