### ISSUE TITLE
[question] How to update the dom data on demand?

### ISSUE THREAD

**Issue by greg2paris** [erdewit/ib_insync#158]
Hi there,
I use the code to show the live data of the dom.
I would like to update the dome only when I make the request.
For exemple:
I request the live data, then when a new data is coming it shows it.
Then I make my calculation.
When my calculation are finished, I request the live data again just for one time, when their is new data It shows it and I can loop like this.

because now I use this code below, but I dont realy understand what is the line :
"ticker.updateEvent += onTickerUpdate" is doing. 
Its kind of doing a loop, but then it stops and I dont have any control of it.
So I would like to just ask for the dom data when I need it in my code at différent places.

```
df = pd.DataFrame(index=range(5),
        columns='bidSize bidPrice askPrice askSize'.split())

def onTickerUpdate(ticker):
    bids = ticker.domBids
    for i in range(5):
        df.iloc[i, 0] = bids[i].size if i < len(bids) else 0
        df.iloc[i, 1] = bids[i].price if i < len(bids) else 0
    asks = ticker.domAsks
    for i in range(5):
        df.iloc[i, 2] = asks[i].price if i < len(asks) else 0
        df.iloc[i, 3] = asks[i].size if i < len(asks) else 0
    clear_output(wait=True)
    display(df)

ticker.updateEvent += onTickerUpdate

IB.sleep(15);
```

**Comment by erdewit** [comment]
The "ticker.updateEvent += onTickerUpdate" is adding an event handler to the ticker's update event. See the [eventkit project](https://github.com/erdewit/eventkit) for the full details on how this works.

The loop is actually started with IB.sleep(15), which run the event loop for 15 secs.

The ticker's DOM state is always kept up to date and is ready to be used at any time.
