### ISSUE TITLE
[question] Why is position data requested by default?

### ISSUE THREAD

**Issue by kevinlmadison** [erdewit/ib_insync#159]
We are working on a client's application and according to their legal team we the developers should not have access to position data. In our fork we have removed the logging but we weren't sure if there was an underlying reason for requesting the positions during startup. Thanks for this library! We're happy to contribute!

**Comment by erdewit** [comment]
The positions are part of the state that is synced on startup and then kept in sync. It's a namesake feature of the project.

Note that ``wrapper.updatePortfolio`` also handles portfolio data.
