### ISSUE TITLE
[question] how to print last trade profits?

### ISSUE THREAD

**Issue by greg2paris** [erdewit/ib_insync#160]
Hey, 
I tried to show last trade pnl with those commands :
print("ib.trades()", ib.trades())
print("ib.orders()", ib.orders())
print("ib.pnl()", ib.pnl())
print("ib.pnlSingle()", ib.pnlSingle())

The trades and orders dont have any pnl and the ib.pnl() and ib.pnlSingle() always shows an empty array even if I open and close positions.

I am using clientId = 0
ib.connect('127.0.0.1', 7497, clientId=0)

How can I show last trade profits?

Edit :
I somehow found how to print trades profits with this:
print("realizedPNL", ib.fills()[-1].commissionReport.realizedPNL)

But the thing is that it doesn't update when I open a trade, it shows the trade before the last one, I still cant retrieve the last trade's profits.

Then I tried to connect one more time just after opening and closing a trade with this : ib.connect('127.0.0.1', 7497, clientId=0)

Now its showing the last profits with the same line : 
print("realizedPNL", ib.fills()[-1].commissionReport.realizedPNL)

but I think their should be an easier way to do it without having to reconect every time to get the last trade profits, right ?

**Comment by erdewit** [comment]
There is [reqPnL](https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.reqPnL) to start a profit & loss subscription.

**Comment by greg2paris** [comment]
I will answer my question, it took me a long time to retrive the last trades informations so mabe it will help other people.
I succeded to retrive the last trade realized pnl and commission with this lines: 

```
    try:
        last_trade_pnl = ib.trades()[-1].fills[0].commissionReport.realizedPNL  # last trade realized pnl
        print("ib.trades()[-1].fills[0].commissionReport.realizedPNL: ", last_trade_pnl)
    except:
        print("no last_trade_pnl")

    try:
        last_trade_commission = ib.trades()[-1].fills[0].commissionReport.commission  # last trade commission
        print("ib.trades()[-1].fills[0].commissionReport.commission: ", last_trade_commission)
    except:
        print("no last_trade_commission")
```
first I look for the info for the last trade with :
ib.trades()[-1]
then I look up for the fills informations: 
ib.trades()[-1].fills
then i look for the commission report information, i dont know why, but it only works when i specify the [0] position in the fills array :
ib.trades()[-1].fills[0].commissionReport
finaly i ask for realizedPNL : 
ib.trades()[-1].fills[0].commissionReport.realizedPNL

I dont know if it is the best way to do it, but its the only way I found.

**Comment by piotrgolawski** [comment]
@greg2paris Why everything in trades have the same conId?
