### ISSUE TITLE
Requesting historical prices bonds

### ISSUE THREAD

**Issue by dkapur** [erdewit/ib_insync#162]
How to request for historical prices of bonds.
I am getting the following error when I try to do this.
```
  contract = Bond('T 1 3/4 06/15/22',exchange = 'BONDLARGE')
  bidbars = ib.reqHistoricalData(contract, endDateTime=t, durationStr='32 D',
  barSizeSetting='1 min', whatToShow='BID', useRTH=True)

```
The symbol being passed is from the IB product listings page for BondLarge.
I get the following error

TypeError('__init__() takes 1 positional argument but 2 were given')
Please help in how can I resolve this.

Thank You,
Dhruv

**Comment by erdewit** [comment]
>  contract = Bond('T 1 3/4 06/15/22',exchange = 'BONDLARGE')

The ``Bond`` constructor takes no positional arguments, only keyword arguments. Bonds tend to be best specified with their conId or their ISIN, for example ``Bond(secIdType='ISIN', secId='US03076KAA60')``.
