### ISSUE TITLE
Order Never moves past PendingSubmit (but it gets filled in IB)

### ISSUE THREAD

**Issue by JustinGirard** [erdewit/ib_insync#164]
from ib_insync import *
util.startLoop()
import time
ib = IB()
ib.connect(SERVER, PORT, clientId=13)
contract = Stock('AAPL', 'SMART', 'USD')
ib.qualifyContracts(contract)
order = MarketOrder('BUY', 100)
trade = ib.placeOrder(contract, order)

while not trade.isDone():
    print('-----------------------')
    print(trade)
    time.sleep(1)
print('Never prints')

**Comment by erdewit** [comment]
https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.sleep

**Comment by JustinGirard** [comment]
GREAT!!! thank you.
