### ISSUE TITLE
Error handling fields: ['90', '18325', '-1', '20190702  16:50:30', '', '', '', '', '-1.0', '-1']

### ISSUE THREAD

**Issue by greg2paris** [erdewit/ib_insync#166]
hello, i got this error, do you know what is it?

> ValueError: could not convert string to float: 
> Error handling fields: ['90', '18325', '-1', '20190702  16:50:30', '', '', '', '', '-1.0', '-1']
> Traceback (most recent call last):
>   File "C:\Users\greg\AppData\Local\Programs\Python\Python37\lib\site-packages\ib_insync\decoder.py", line 188, in interpret
>     handler(fields)
>   File "C:\Users\greg\AppData\Local\Programs\Python\Python37\lib\site-packages\ib_insync\decoder.py", line 429, in historicalDataUpdate
>     open=float(get()),

**Comment by erdewit** [comment]
The OHLCV values that are sent are empty. I see that the official ibapi package will set these to 0.0 in this case and I've updated ib_insync to do the same. It will be bogus values though.
