### ISSUE TITLE
Installing with Conda

### ISSUE THREAD

**Issue by yehoshuadimarsky** [erdewit/ib_insync#171]
I currently use conda instead of pip, it's much better for me in the setup we have at my org. I see that this library isn't currently available in conda, so I want to add it there myself into the conda-forge library (I've done this with several pip packages that weren't in conda, such as azure-cosmos).

1. Do you mind if I do this?
2. I will use this issue to keep people posted about it

**Comment by yehoshuadimarsky** [comment]
Link to the conda-forge PR: https://github.com/conda-forge/staged-recipes/pull/8896

**Comment by yehoshuadimarsky** [comment]
Update - this has been accepted into the conda-forge channel and is now available for installation from conda
```conda install -c conda-forge ib-insync```

**Comment by erdewit** [comment]
Hi Josh, thanks for creating the conda recipes.

There's a dist.sh file that I use for uploading new releases, if there's anything that can be added to it to facilitate with the conda updates let me know.

**Comment by yehoshuadimarsky** [comment]
Thanks. The process for updating the conda package is

1. Fork the source repo with the recipe (https://github.com/conda-forge/ib-insync-feedstock)
2. Make the changes to the `recipe/meta.yaml` file
3. Open a pull request
4. A maintainer of that repo (currently just me) accepts the PR, once the CI builds are successful
5. By accepting and merging the PR, the conda-forge CI system automatically builds it and uploads it to conda-forge

If you wish, I can add you as a maintainer on that repo so you can merge PRs yourself.

As far as updating the `meta.yaml` file, assuming you keep uploading it to PyPI, basically only the following needs updating for new releases if nothing big (like new dependencies) changes:
* version number
* sha256 from PyPI

Maybe you can automate some or all of these steps in your `dist.sh` script. Let me know if you need help.

More details of the process are available in the conda-forge docs.
