### ISSUE TITLE
get contract symbol from openOrders()

### ISSUE THREAD

**Issue by gozhhu** [erdewit/ib_insync#174]
Sorry it is too easy, but I have tried more than two days.. 
How to get Contract info with permId / orderId ?

--------- result from openOrders ----------
Order(orderId=-26, permId=195475513, action='SELL', totalQuantity=6, orderType='LMT', lmtPrice=1.05, auxPrice=0.0, tif='GTC', ocaType=3, rule80A='0', openClose='', eTradeOnly=False, firmQuoteOnly=False, volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='XXXXXXXXX', clearingIntent='IB', orderComboLegs=[], adjustedOrderType='None', conditions=[], softDollarTier=SoftDollarTier(), cashQty=0.0, dontUseAutoPriceForHedge=True)

**Comment by gozhhu** [comment]
btw: with openTrades() I can get only some orders of my own.

**Comment by erdewit** [comment]
There is ``ib.openTrades()`` that gives all related information about the order including the contract.
