### ISSUE TITLE
Wrong unrealizedPnL value

### ISSUE THREAD

**Issue by eric0470** [erdewit/ib_insync#176]
What could be the reason why I started receiving a wrong unrealizedPnL values back? For example for GC  contract I received value: `179,769,313,486,231,570,814,527,423,731,704,356,798,070,567,525,844,996,598,917,476,803,157,260,780,028,538,760,589,558,632,766,878,171,540,458,953,514,382,464,234,321,326,889,464,182,768,467,546,703,537,516,986,049,910,576,5` (formatted by :,.2f).

I use `reqPnLSingle` function to subscribe to pnl object and using unrealizedPnL property from it to check UPNL value. Where is this value come from?

**Comment by erdewit** [comment]
These are the values as sent by IB and they are just passed along.
