### ISSUE TITLE
decode with correct encoding

### ISSUE THREAD

**Issue by viponedream** [erdewit/ib_insync#180]
utils.py --> def decode()
     return s.decode(errors='backslashreplace')  -->> some problem here.

 s.decode(encoding="GBK")  #   non-english location have to specify the correct one that set in tws.

so another question is how to get the language you set in tws?

**Comment by erdewit** [comment]
> so another question is how to get the language you set in tws?

The problem is that this is not known, and the encoding that is used is not known either
