### ISSUE TITLE
could every request to run as it's own thread?

### ISSUE THREAD

**Issue by viponedream** [erdewit/ib_insync#183]
Is now the framwork run in one thread?
sorry for my poor English. 
For example, 
if i put the ib_insync in my trading system. 
then i request the reqHistorical(each request must wait secs) that may take a long time. it will suspend the whole trading system.
another market stream will missing. 
So i think all the requests like reqContract, reqHistorical to run in it's own thread. 

The final trading system is  no matter how long the reqeust takes. it won't affect  to the main tread.

Can we do that?

**Comment by erdewit** [comment]
To run requests concurrently there are the *Async methods, such as reqHistoricalAsync. This does require knowledge of async programming though.
