### ISSUE TITLE
Why LimitOrder() has trailStopPrice?

### ISSUE THREAD

**Issue by gozhhu** [erdewit/ib_insync#189]
Hello, I just found some of my order completed with an incorrect trail stop price, so I print them out and I found:
------------------------
Order(orderId=215, clientId=1501, permId=XXXXXXXX, action='BUY', totalQuantity=6, orderType='LMT', lmtPrice=0.98, auxPrice=0.0, tif='DAY', ocaType=3, trailStopPrice=1.98, openClose='', eTradeOnly=False, firmQuoteOnly=False, volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='xxxxxxxxxx', clearingIntent='IB', orderComboLegs=[], adjustedOrderType='None', conditions=[], softDollarTier=SoftDollarTier(), cashQty=0.0, dontUseAutoPriceForHedge=True)
-------------------------
I use LimitOrder function, but I found "trailStopPrice=1.98" ( lmtPrice=0.98 ), please give me some advise about it, and how can I get ride of it? trailStopPrice=0? or same as price?

updated: This problem only happens in ComboLegs order, trailStopPrice=(lmtPrice+1) in ComboLegs( 2 leg ), how to solve it?

**Comment by gozhhu** [comment]
updated: The actual problem is trailStopPrice=lmtPrice*2 in ComboLegs( 2 leg ), how to solve it?

**Comment by erdewit** [comment]
The ``trailStopPrice`` on the order is set by IB and I'm not sure why they do that.
