### ISSUE TITLE
Permission denied: '/opt/ibc/scripts/ibcstart.sh'

### ISSUE THREAD

**Issue by joan-arau** [erdewit/ib_insync#190]
Using Ibcontroller I am getting this error message: 

PermissionError: [Errno 13] Permission denied: '/opt/ibc/scripts/ibcstart.sh'

I have done this in the terminal: 

 cd /opt/ibc
 sudo chmod o+x *.sh */*.sh

ls -l gives this:

-rw-r--r-x@ 1 USER  staff  13606  4 Jun 12:37 ibcstart.sh

**Comment by Neocryan** [comment]
You don't have the permission , try `sudo /opt/ibc/scripts/ibcstart.sh`.
Or just give it the permission if you think it is safe: `chmod +x  /opt/ibc/scripts/ibcstart.sh`

**Comment by joan-arau** [comment]
Thank you very much, this seems to have partially fixed my problem. 
sudo /opt/ibc/scripts/ibcstart.sh seems to work fine in the terminal. in ib_insync I got the error that it can't find the config.ini file so I created an empty file (do I have to store my user and pw data in there or is it fine if I just give it when I call IBC from ib_insync in python?) 

Now I am getting this error : 
/opt/ibc/scripts/ibcstart.sh: line 157: ${mode^^}: bad substitution

=========================== An error has occurred =============================



Error:  does not exist

**Comment by Neocryan** [comment]
You can copy the `/opt/ibc/config.ini` to the default path `~/ibc`. Before using IBC from ib_insync, I recommend you to set up your IBC following the [user guide](https://github.com/IbcAlpha/IBC/blob/master/userguide.md)
