### ISSUE TITLE
error message:Request Timed Out

### ISSUE THREAD

**Issue by Kagaratsch** [erdewit/ib_insync#195]
Pretty much any bulk operation starts throwing error messages,e.g.:

Error 162, reqId 1663: Historical Market Data Service error message:Request Timed Out, contract: Stock(symbol='AZN', exchange='SMART', currency='USD')

almost immediately, and skipping operation steps. Any idea how to catch this error and resubmit the operation on the fly?

**Comment by erdewit** [comment]
The error message is coming from the IB backoffice. It would be up to you to see which requests succeeded and which failed and retry the ones that failed.

**Comment by Kagaratsch** [comment]
Yes. I mean, ideally any error message should be handled through try: and catch commands. ib_insync does not seem to catch these errors though so I'm wondering if you know how to do that manually?
