### ISSUE TITLE
A Bug when using multi accounts

### ISSUE THREAD

**Issue by hadrianl** [erdewit/ib_insync#197]
https://github.com/erdewit/ib_insync/blob/1a79398fcabe197ece8ca10f54e64ef865fae10e/ib_insync/ib.py#L1626

when i got 2 accounts and had requested "reqAccountUpdates(accounts[1])" using one client, it`s impossible to connect to TWS or IBGateway through another client because of this "Warning 2101, reqId -1: Unable subscribe to account as the following clients are subscribed to a different account.{1}"

**Comment by erdewit** [comment]
I would suggest to override or monkey-paths the ``ib.connectAsync`` method for your specific situation.
