### ISSUE TITLE
Error 10168, reqId 4: Requested market data is not subscribed

### ISSUE THREAD

**Issue by manajit04** [erdewit/ib_insync#198]
Hi there, 
I am trying to use option chain code I am getting following error. "Error 10168, reqId 4: Requested market data is not subscribed."

Can someone please help?

Thanks
![image](https://user-images.githubusercontent.com/39574868/68694650-888d4d00-0547-11ea-85c3-187947b47911.png)

**Comment by erdewit** [comment]
The error means there is no (paid) subscription for the data.

**Comment by bscully27** [comment]
from interactivebrokers.com/AccountManagement
"All of our clients have access to delayed market data by default*. You can generate real-time quotes for any supported security on demand by clicking on the Snapshot button (  ) in any trading platform - no need for a monthly streaming subscription."

Why isn't delayed data coming through?
