### ISSUE TITLE
No Tar.GZ file on PyPI for v0.9.57

### ISSUE THREAD

**Issue by yehoshuadimarsky** [erdewit/ib_insync#199]
On PyPI there are typically both a `whl` file and a `tar.gz` containing the source code. For earlier releases this was working fine, but for v0.9.57 for some reason the `tar.gz` file is missing. 

The `conda-forge` channel for the `conda` package manager relies on the `tar.gz` file, and it can't update to the latest version. That's why I'm asking. I'm the maintainer at https://github.com/conda-forge/ib-insync-feedstock.

Good:
https://pypi.org/project/ib-insync/0.9.56/#files

Bad:
https://pypi.org/project/ib-insync/0.9.57/#files

Did something change or get messed up with the file at https://github.com/erdewit/ib_insync/blob/master/dist.sh ?

**Comment by erdewit** [comment]
Hi Josh, not sure what happened with the tar.gz file but a new 0.9.58 release was just uploaded that does have it.
