### ISSUE TITLE
util.startLoop() outside of Jupyter Notebook

### ISSUE THREAD

**Issue by chrisayers101** [erdewit/ib_insync#20]
Hey there - thanks for an awesome Python Wrapper!!!

Is it possible to use the util.startLoop() method outside of Juypter notebook.  I would like to schedule a CRON job that kicks of a script on an Amazon EC2 instance.

error I get when running the method outside of jupyter is:
RuntimeError: You didn't specify a kernel, and no IPython Application with a kernel appears to be running.

Thanks heaps...

**Comment by erdewit** [comment]
For a normal Python script it is not necessary or even appropriate to cal util.startLoop(), it can simply be left out.
