### ISSUE TITLE
ib_insync not working in Nameko service

### ISSUE THREAD

**Issue by ilieszidane** [erdewit/ib_insync#207]
I am trying to get ib_insync "working" within a nameko service, so far without succcess.

I have tried to patch asyncio(), still does not work, failing at the imports.

```
import asyncio
from ib_insync import IB, util
from ib_insync.contract import *  # noqa

util.patchAsyncio()
```

Any help/suggestion is appreciated.

_|File "/usr/local/bin/nameko", line 8, in <module>
|  sys.exit(main())
|File "/usr/local/lib/python3.6/site-packages/nameko/cli/main.py", line 112, in main
|  args.main(args)
|File "/usr/local/lib/python3.6/site-packages/nameko/cli/commands.py", line 110, in main
|  main(args)
|File "/usr/local/lib/python3.6/site-packages/nameko/cli/run.py", line 181, in main
|  import_service(path)
|File "/usr/local/lib/python3.6/site-packages/nameko/cli/run.py", line 46, in import_service
|  __import__(module_name)
|  from ib_insync import IB, util
|File "/usr/local/lib/python3.6/site-packages/ib_insync/__init__.py", line 7, in <module>
|  from eventkit import Event
|File "/usr/local/lib/python3.6/site-packages/eventkit/__init__.py", line 4, in <module>
|  from .event import Event
|File "/usr/local/lib/python3.6/site-packages/eventkit/event.py", line 7, in <module>
|  from .util import NO_VALUE, loop
|File "/usr/local/lib/python3.6/site-packages/eventkit/util.py", line 19, in <module>
|  loop = asyncio.get_event_loop()
|File "/usr/local/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
|  return get_event_loop_policy().get_event_loop()
|File "/usr/local/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
|  % threading.current_thread().name)
| RuntimeError: There is no current event loop in thread 'MainThread'._

**Comment by erdewit** [comment]
It would be better to use ib_insync with an asyncio-aware framework. It seems nameko doesn't support asyncio.
