### ISSUE TITLE
async errors when market data request is called in order exec callback

### ISSUE THREAD

**Issue by openSourceBugs** [erdewit/ib_insync#208]
def orderExecCallback(self,theTrade, fill):
    self.ib.reqHistoricalData(contract, endDateTime='', durationStr="3600 S",
                                                      barSizeSetting= "1 min", whatToShow='TRADES', useRTH=True) 

After placing a bracket order, the 2nd order which gets executed (stoploss or take profit) causes some weird async "empty dequeue" error.  I tried installing the latest async library and this still happened.  I tried the async apply hack, and another hack and still got this error.

**Comment by erdewit** [comment]
Can you please provide a minimal test case that triggers the issue?

**Comment by erdewit** [comment]
Closing this.
