### ISSUE TITLE
Calling ib.accountValues() does not update values.

### ISSUE THREAD

**Issue by dyus1983** [erdewit/ib_insync#21]
Calling ib.accountValues() does not update values in sync. Values are updated only upon connection. Tried both in TWS and IBG using real trading account with real-time data. Tags checked: 'EquityWithLoanValue', 'StockMarketValue'. 

ib.accountSummary() does not update either. Only on the first run.

TWS Build 968.2d, Oct 10, 2017 2:59:29 PM

**Comment by shlomikushchi** [comment]
was there a solution? I'm facing the same issues with current version
