### ISSUE TITLE
qt gui slow

### ISSUE THREAD

**Issue by yandreiy** [erdewit/ib_insync#211]
Using qt gui with ib_sync `IB.run()` results in a very slow Gui. 
I've tried the qt example from here: https://github.com/erdewit/ib_insync/blob/master/examples/qt_ticker_table.py
Clicking on the cells is slow and can take 1-2 sec or more for the event to be executed.

Using regular qt event loop (not the `IB.run()`) all works well as expected. 

Environment: macos Catalina version 10.15

**Comment by yandreiy** [comment]
Btw, tested in ubuntu and this works fine, so I'm guessing it's a macos related problem.

**Comment by erdewit** [comment]
There's not much I can do about this. Perhaps try running with pyside2 instead of pyqt5.
