### ISSUE TITLE
portfolio() brings an empty list, even when I've stocks in my portoflio

### ISSUE THREAD

**Issue by cocodrino** [erdewit/ib_insync#214]
Hello,  when I request my portfolio using portfolio() method this always bring an empty list, but I've several stocks in the trader workstation, do you know what could be the problem here? please let me know if you need more details or info

![image](https://user-images.githubusercontent.com/616412/73756769-813ca080-473e-11ea-9950-9689136b0050.png)

![image](https://user-images.githubusercontent.com/616412/73756964-d37dc180-473e-11ea-898a-8f2d7278c377.png)

thank you

**Comment by cocodrino** [comment]
ok I notice that when I call reqAccountUpdates before call the portfolio method, this works...now sometime reqAccountUpdates freeze

it's not clear to me but I need run reqAccountUpdates, freeze the repl, then abort with ctr-c, and then recall reqAccountUpdates and it run really fast this time...

**Comment by erdewit** [comment]
It seems you're running interactively from a standard Python console. That's is okay but it will not keep things automatically up to date. Updates have to be forced then, for example with ``ib.sleep(0)``.

It's easier to use notebooks for interactive use.
