### ISSUE TITLE
Not possible to place a STOP order ADJUSTED to TRAIL

### ISSUE THREAD

**Issue by wircho** [erdewit/ib_insync#216]
The code that follows from the IB API docs seems simple enough:

```
# Buy (parent) order
buyOrder = ib_insync.LimitOrder("BUY", count, price, orderId = buyOrderId, transmit = False)
  
# Sell order (adjustable stop loss)
sellOrder = ib_insync.Order(orderId = sellOrderId)
sellOrder.action = "SELL"
sellOrder.orderType = "STP"
sellOrder.auxPrice = sellOrderPrice
sellOrder.totalQuantity = count

# Adjustable parameters
sellOrder.triggerPrice = sellOrderTriggerPrice
sellOrder.adjustedOrderType = "TRAIL"
sellOrder.adjustableTrailingUnit = 1 # (trailing %)
sellOrder.adjustedTrailingAmount = 10.0 # 10%
sellOrder.parentId = buyOrder.orderId
sellOrder.transmit = True
  
buyTrade = ib.placeOrder(contract, buyOrder)
sellTrade = ib.placeOrder(contract, sellOrder)
```

The bracket order goes through if the sell (stop loss) order has none of the "Adjustable parameters". However, setting these parameters means that `sellOrder` is never submitted at all.

References:
https://interactivebrokers.github.io/tws-api/adjustable_stops.html
https://groups.io/g/twsapi/topic/usage_of_adjusted_to_trail/22683601?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,22683601

**Comment by erdewit** [comment]
This is more a question for the IB support staff.

**Comment by darrenspriet** [comment]
Did anyone achieve this?  I am curious if there is a workaround or a solution found?
