### ISSUE TITLE
exception Timeout Error: same code works in for some users and other not

### ISSUE THREAD

**Issue by cocodrino** [erdewit/ib_insync#218]
Hi good day, currently we have a script that connects to the trader workstation, the script works ok in some machines but in others we get the error displayed in the image.  we've tried changing the timeout  and RequestTimeout

I was able to replicate the issue in my machine, using the python version 3.8.0...if I use this specific version I get the same error, but using the version 3.7.6 and 3.8.6 works fine, unfortunately a team mate had tried these versions and didn't work

is possible fix this issue without try several python version till this work?...thank you

![image](https://user-images.githubusercontent.com/616412/74731153-db992f00-521d-11ea-8849-35febd585942.png)

**Comment by erdewit** [comment]
A connection failure generally indicates a network/permissions issue.
