### ISSUE TITLE
I can't create straddle spread order.

### ISSUE THREAD

**Issue by SunHxiao** [erdewit/ib_insync#223]
spread_contract = Contract()
spread_contract.symbol = "TSLA"
spread_contract.secType = "BAG"
spread_contract.currency = "USD"
spread_contract.exchange = "SMART"

option1 = Contract()
option1.symbol = "TSLA"
option1.secType = "OPT"
option1.exchange = "SMART"
option1.currency = "USD"
option1.primaryExchange = "NASDAQ"
option1.multiplier = "100"
option1.lastTradeDateOrContractMonth = 20200412
option1.right = 'C'
option1.strike = 535
ib.qualifyContracts(option1)
print(option1)

option2 = Contract()
option2.symbol = "TSLA"
option2.secType = "OPT"
option2.exchange = "SMART"
option2.currency = "USD"
option2.primaryExchange = "NASDAQ"
option2.multiplier = "100"
option2.lastTradeDateOrContractMonth = 20200416
option2.right = 'C'
option2.strike = 540
ib.qualifyContracts(option2)
print(option2)

leg1 = ComboLeg()
leg1.conId = option1.conId  # DBK JUN 21 2019 C
leg1.ratio = 1
leg1.action = "BUY"
leg1.exchange = "SMART"
leg2 = ComboLeg()
leg2.conId = option2.conId  # DBK MAR 15 2019 C
leg2.ratio = 1
leg2.action = "SELL"
leg2.exchange = "SMART"
spread_contract.comboLegs = []
spread_contract.comboLegs.append(leg1)
spread_contract.comboLegs.append(leg2)
ib.qualifyContracts(spread_contract)
print(spread_contract)

ib_order = LimitOrder('BUY', 100, 545, algoStrategy='Adaptive',
                      algoParams=[TagValue('adaptivePriority', 'Normal')])
trade = ib.placeOrder(spread_contract, ib_order)
print(trade)

Error 321, reqId 125: Error validating request:-'bQ' : cause - 'BAG' isn't supported for contract data request. Please enter a valid security type, contract: Contract(secType='BAG', symbol='TSLA', exchange='SMART', currency='USD', comboLegs=[ComboLeg(conId=0, ratio=1, action='BUY', exchange='SMART', openClose=0, shortSaleSlot=0, designatedLocation='', exemptCode=-1), ComboLeg(conId=0, ratio=1, action='SELL', exchange='SMART', openClose=0, shortSaleSlot=0, designatedLocation='', exemptCode=-1)])
Unknown contract: Contract(secType='BAG', symbol='TSLA', exchange='SMART', currency='USD', comboLegs=[ComboLeg(conId=0, ratio=1, action='BUY', exchange='SMART', openClose=0, shortSaleSlot=0, designatedLocation='', exemptCode=-1), ComboLeg(conId=0, ratio=1, action='SELL', exchange='SMART', openClose=0, shortSaleSlot=0, designatedLocation='', exemptCode=-1)])

Error 200, reqId 123: No security definition has been found for the request, contract: Contract(secType='OPT', symbol='TSLA', lastTradeDateOrContractMonth=20200412, strike=535, right='C', multiplier='100', exchange='SMART', primaryExchange='NASDAQ', currency='USD')
Unknown contract: Contract(secType='OPT', symbol='TSLA', lastTradeDateOrContractMonth=20200412, strike=535, right='C', multiplier='100', exchange='SMART', primaryExchange='NASDAQ', currency='USD')

**Comment by stnatter** [comment]
You need to call `qualifyContracts` for each leg of your `BAG` separately. A better place for such questions is actually the user group where chances are your question has been asked before already ;-)
