### ISSUE TITLE
reqMktData always give nan

### ISSUE THREAD

**Issue by lihanchen** [erdewit/ib_insync#229]
I am still exploring ib insync. I wrote a simple snippnet to keep track of stock price.
The ticker return has nan/None/empty values in almost all fields after a long time. 
```
import time
from ib_insync import *
ib = IB()
ib.connect('127.0.0.1', 8002, clientId=1)
contract = Stock('TSLA', 'SMART', 'USD')
Ticker=ib.reqMktData(contract)
while True:
    time.sleep(5)
    print(Ticker.last)
```
I have tws 978.1o, Python 3.7. I can get market data from Java API.

**Comment by erdewit** [comment]
>  time.sleep(5)

must be ib.sleep(5)

**Comment by lihanchen** [comment]
It fixes the issue. I found information about ib.sleep() vs time.sleep(). Thank you very much.

**Comment by cappaberra** [comment]
Having a sleep in there is extremely important so the API has time to pull the ticks.
