### ISSUE TITLE
I would like to get hisotrical data on the futur

### ISSUE THREAD

**Issue by jiany30** [erdewit/ib_insync#234]
Hello Everyone
contracts = Future('ES', '20200619', 'GLOBEX', includeExpired=True)
ib.qualifyContracts(contracts)
# ib.reqMarketDataType(4)
bars = ib.reqHistoricalData(
     contracts,
     "",
     "5 Y",
     "1 day",
     "TRADES",
     True
 )
 print(bars)

I have got this error
"Error 162, reqId 425: Historical Market Data Service error message:No market data permissions for GLOBEX FUT, contract: Contract(secType='FUT', conId=396336017, symbol='ES', lastTradeDateOrContractMonth='20210319', multiplier='50', exchange='GLOBEX', currency='USD', localSymbol='ESH1', tradingClass='ES')"
Can you help me?
What was wrong?
How to solve this problem?
Best regards!

**Comment by RGLDN** [comment]
The answer is in your message - "No market data permissions for GLOBEX FUT"

You need to subscribe to market data before you can access it. See https://www.interactivebrokers.com/en/software/am3/am/settings/marketdatasubscriptions.htm
