### ISSUE TITLE
Ticker updateEvent not fired in some occasions

### ISSUE THREAD

**Issue by rgeronimi** [erdewit/ib_insync#236]
Once a reqMktData subscription has been performed through ib_insync,
I noticed the Ticker.updateEvent event is not fired in many occasions where it should (i.e., once the data has been sent back by IB server), as if the event got "lost". This results in code waiting forever for an event. I noticed this for option ticker data as well as dividend ticker data.

However the IB.updateEvent event has been fired everytime and contains the correct data. So it points toward a bug inside the ib_insync library and not on the IB server side.

Looking at the code of wrapper.py, the error seems to come from the combinations of 2 things:

- Althought IB.updateEvent is fired in all cases, Ticker.updateEvent gets fired only for tickers that got added to a Wrapper.pendingTickers list during processing of data received from the IB server

- During processing of this data, tickers get added to this list based on rules that vary depending on the type of data. For example, for dividends, they do not get added to the list. So another ticker data field needs to change later to trigger the event (like price or volume). If nothing else changes (eg because the market is closed), nothing happens even later. This explains the observed seemingly erratic behavior of the API. The same inconsistency pattern occurs for other type of ticker data in other methods of the Wrapper class (e.g., bid/ask changes).

I have only a cursory understanding of the API specifications, so I may be wrong regarding whether it is a bug or an intended behavior that is not explained (yet) in the documentation. In all cases, either the code or the documentation shall be fixed.

**Comment by rgeronimi** [comment]
Looking more at the code, it seems that there are 3 different actions:

1. One or several Ticker data field(s) being updated when receiving data from IB server (eg dividends or options data)
2. A new Tick object being added to the Ticker object
3. The Ticker being added to the Wrapper.pendingTickers list, thus triggering a Ticker.updateEvent later once the IB server data has been processed

As written above, It seems (1) does not lead to (3) for all data fields. Looking at the code, it seems (2) and (3) are systematically  linked - one is always done with the other. So Ticker.updateEvent events are emitted only when new Ticks gets created. This is intuitive for price and volume changes, but not for other kind of data.

One solution would be the following:
Link systematically (1) and (3) instead, performing (3) systematically as soon as (1) is performed. Keep (2) separated, being executed (as today) only when the price or volume changes.

**Comment by erdewit** [comment]
Thanks for the systematic review of this particular behaviour. It is fixed by setting the ticker as pending for anything in the wrapper that changes it.
