### ISSUE TITLE
RuntimeError: Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by devburn118** [erdewit/ib_insync#237]
I get the following error when running the first code sample from the Options Chain notebook. The code executes fine and anything following within the same text block runs fine.

> 2020-04-19 20:00:46,774 tornado.application ERROR Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x10f61a1e0>)
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
>     ret = callback()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 265, in enter_eventloop
>     self.eventloop(self)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ib_insync/util.py", line 450, in _ipython_loop_asyncio
>     loop.run_forever()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 411, in run_forever
>     'Cannot run the event loop while another loop is running')
> RuntimeError: Cannot run the event loop while another loop is running

The problem is the next code I try and run (Input 2/textblock 2) gives me the following issue and will no longer work:

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-2-fdbe47a45b7e> in <module>()
>       1 spx = Index('SPX', 'CBOE')
> ----> 2 ib.qualifyContracts(spx)
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ib_insync/ib.py in qualifyContracts(self, *contracts)
>     535             contracts: Contracts to qualify.
>     536         """
> --> 537         return self._run(self.qualifyContractsAsync(*contracts))
>     538 
>     539     def bracketOrder(
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ib_insync/ib.py in _run(self, *awaitables)
>     290 
>     291     def _run(self, *awaitables: Awaitable):
> --> 292         return util.run(*awaitables, timeout=self.RequestTimeout)
>     293 
>     294     def waitOnUpdate(self, timeout: float = 0) -> bool:
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ib_insync/util.py in run(timeout, *awaitables)
>     302         if timeout:
>     303             future = asyncio.wait_for(future, timeout)
> --> 304         task = asyncio.ensure_future(future)
>     305 
>     306         def onError(_):
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py in ensure_future(coro_or_future, loop)
>     517         if loop is None:
>     518             loop = events.get_event_loop()
> --> 519         task = loop.create_task(coro_or_future)
>     520         if task._source_traceback:
>     521             del task._source_traceback[-1]
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py in create_task(self, coro)
>     280         Return a task object.
>     281         """
> --> 282         self._check_closed()
>     283         if self._task_factory is None:
>     284             task = tasks.Task(coro, loop=self)
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py in _check_closed(self)
>     355     def _check_closed(self):
>     356         if self._closed:
> --> 357             raise RuntimeError('Event loop is closed')
>     358 
>     359     def _asyncgen_finalizer_hook(self, agen):

**Comment by devburn118** [comment]
I am using:
Jupyter Notebook v5.0
Python v3.6.2

Thanks for your help.

**Comment by erdewit** [comment]
It is a very old version of Jupyter. I would suggest trying a newer one.
