### ISSUE TITLE
How to calculate P&L in real-time

### ISSUE THREAD

**Issue by SunHxiao** [erdewit/ib_insync#238]
After placing order, I would like to log the P&L per loop.
But I don't how to calculate the P&L.

For example: 
While True:
    contract = Stock('AAPL', 'SMART', 'USD')
    ib.qualifyContracts(contract)
    lmtPrice =  274.3
    totalQuantity = 20
    limitOrder = LimitOrder('BUY', totalQuantity, lmtPrice)
    stopPrice = 274.5
    stopOrder = StopOrder('BUY', totalQuantity, stopPrice)
    trade1 = ib.placeOrder(contract, limitOrder)
    trade2 = ib.placeOrder(contract, stopOrder)
    ###### Here is ############

    #########################
    ib.sleep(60)

**Comment by erdewit** [comment]
See reqPnL:

https://ib-insync.readthedocs.io/api.html?#ib_insync.ib.IB.reqPnL
