### ISSUE TITLE
Historical Prices for Multiple Securities

### ISSUE THREAD

**Issue by boflan** [erdewit/ib_insync#24]
Ewald, thanks so much for this package.  I'm a beginner with Python and found IB's API unusable without it.  For my analysis, I needed a dataframe of multiple securities.  I didn't see that option so created a loop.  I'm not sure if this would be of use to others and am sure you'd be able to code it more efficiently, but wanted to share in case you'd like to add having multiple securities to your notebook examples.  

`symlist = (universe) #universe is a list created in a separate cell
df = pd.DataFrame()

for x in symlist:
    contract = Stock(x, 'SMART', 'USD')
    bars = ib.reqHistoricalData(
        contract,
        endDateTime='',
        durationStr='250 D',
        barSizeSetting='1 day',
        whatToShow='ADJUSTED_LAST', #use ADJUSTED_LAST for stocks, MIDPOINT for currencies
        useRTH=True,
        formatDate=1)
    data = util.df(bars)
    data = data.set_index('date')
    data = data['close']
    data = data.to_frame(x)
    df = pd.concat([df, data], axis=1)`

**Comment by erdewit** [comment]
Thanks for sharing Boflan. I think the insync user group is a be better place to share code snippets as more folks will be seeing them.
