### ISSUE TITLE
Historical quarterly finanical statements data and monthly financial ratios

### ISSUE THREAD

**Issue by MislavSag** [erdewit/ib_insync#240]
I succedfully pulled finanical statements (FS) from IB using simple function:

`fundData = ib.reqFundamentalData(con, reportType='ReportsFinStatements')`

This gives me some metadata on FS, annual data, and interim data. 

I would like to know is there a possibility o get **quarterly** historical FS? I have read IB docs, ib_sync docs, and try to found info on groups.io, but without success.

Same thing for financial ratios. I can get only current (market) info on financial ratios using ib.reqMktData(con, '258')`, but not the history. 

Is there a possibility to retrieve quarterly FS or monthly financial ratios?

For financial ratios in IB docs they say:

> For older data, it is feasible you may receive less tags (refer to LATESTADATE tag).

but don't say explicitly how to retrieve older data.

**Comment by erdewit** [comment]
You can ask IBKR.

best, Ewald

**Comment by MislavSag** [comment]
Ok, I will.

**Comment by valerianrossigneux** [comment]
@MislavSag ever found the right tags to access historical data?
