### ISSUE TITLE
why would i get the error message: Only 50 simultaneous API historical data requests allowed

### ISSUE THREAD

**Issue by SunHxiao** [erdewit/ib_insync#241]
Hi, Erdewit.
I really appreciate your help.
I am trading with some stocks.
By the way, I am getting this error message after some time.
![image](https://user-images.githubusercontent.com/56060401/80495532-9ff7af80-899a-11ea-817d-08897b65d177.png)
How can I fix this error?
I will wait for your favorable reply.
Best regards!

**Comment by erdewit** [comment]
If only the error message could tell us...
