### ISSUE TITLE
Expected functionality of ib.tickers()?

### ISSUE THREAD

**Issue by Shellcat-Zero** [erdewit/ib_insync#246]
According to the [documentation](https://ib-insync.readthedocs.io/api.html?highlight=tickers#ib_insync.ib.IB.tickers), the `tickers()` function is supposed to return a list of all tickers on IB, but for me this always returns an empty list.  Is this a bug, or how is this function intended to be used?

I was looking for a method to obtain all forex pairs from IB, if there is one, but other methods returning all tradable stocks, etc, on IB would be convenient to know as well if they exist.  Thanks.

**Comment by erdewit** [comment]
That sort of instrument information is available from the IB product listings, not the API.

The ``ib.tickers()`` returns a list of tickers subscribed with reqMktData.
