### ISSUE TITLE
I am going to automate Entry and Exit Strategy

### ISSUE THREAD

**Issue by SunHxiao** [erdewit/ib_insync#247]
Hello.
I am going to automate Entry and Exit Strategy
I am very interested in ib_insync
But I don't know how to build automate Entry and Exit Strategy on the ib_insync.
Entry strategy is only valid for the first x minutes (default input at 30 minutes)  from market opening.
So  Specifics Entry strategy for Puts and calls
For Calls:
a.	Enter if first candlestick is above the highest pre-market close price
b.	Enter if first candle is very bullish (80-100% body of whole candle and bull candle)
c.	Enter if first candlestick is above the Vwap
For Puts:
a.	Enter if first candlestick is below the lowest pre-market close price
b.	Enter if first candle is very bearish (80-100% body of whole candle and bear candle)
c.	Enter if first candlestick is below the Vwap
Can you help me?
I 'd love to hear favorable reply from you
Thanks.

**Comment by erdewit** [comment]
IB-insync provides the building blocks but it's up to you to do the building.

**Comment by SunHxiao** [comment]
Hi.erdewit.
Thanks for your reply.
Can you help me?
Would you please inform me how to automate Entry and Exit Strategy for options?
I will wait for your reply.
