### ISSUE TITLE
Dear Erdewit.

### ISSUE THREAD

**Issue by SunHxiao** [erdewit/ib_insync#249]
Hi.erdewit.
Thanks for your reply.
Can you help me?
Would you please inform me how to automate Entry and Exit Strategy for options?
I will wait for your reply.

**Comment by erdewit** [comment]
You can take a look here, for example:
https://github.com/jamesmawm/High-Frequency-Trading-Model-with-IB

**Comment by SunHxiao** [comment]
Hi @erdewit.
Thanks for your quick reply.
I have following issue.
"Only 50 simultaneous API historical data requests allowed."
For fixing this error, I have used ib.cancelHistoricalData function.
So I fixed the error.
But I am getting this message.
image
I don't want to get this message.
Can you help me?
Thanks for your kind.
