### ISSUE TITLE
RuntimeWarning: coroutine 'IB.connectAsync' was never awaited

### ISSUE THREAD

**Issue by atkinson** [erdewit/ib_insync#251]
Hello

Thanks for this great library. I'm trying to use IB_insync with FastAPI (a framework that uses uvloop).

As we can't patch uvloop, I understand I should use the Async suffix on the methods.

However, I get this message when running connectAsync:

```
RuntimeWarning: coroutine 'IB.connectAsync' was never awaited
  ib.connectAsync('127.0.0.1', 7496, clientId=0)
```
And, it's more than a harmless warning because if I subsequently try to get data, I get ConnectionError('Not connected').

Checking the logs in TWS confirms that no connection attempt was made.

I have included sample code below to illustrate. 

Many thanks
Rich

Python 3.7.4
ib-insync==0.9.59

```
import asyncio
from fastapi import FastAPI
from ib_insync import IB, Stock, util

app = FastAPI()
ib = IB()
ib.connectAsync('127.0.0.1', 7496, clientId=3)


@app.get("/")
async def read_root():
    return {"Hello": "World"}
```

**Comment by drusakov778** [comment]
I think all you need is to 'await' on the ib.connectAsync() function, exactly as the error is saying. E.g. the following snippet runs and connects finely:

```
import asyncio
import uvicorn
from fastapi import FastAPI
from ib_insync import IB, Stock, util

app = FastAPI()

@app.on_event("startup")
async def start_tasks():
    ib = IB()
    await ib.connectAsync('localhost', 4002, clientId=3)

@app.get("/")
async def read_root():
    return {"Hello": "World"}

if __name__ == '__main__':
    uvicorn.run(app)
```

**Comment by drusakov778** [comment]
p.s. there is a good discussion group here: h[https://groups.io/g/insync](https://groups.io/g/insync)

**Comment by atkinson** [comment]
Yes - thank you. This is my first foray with asyncio. Will join the group.

many thanks @drusakov778
