### ISSUE TITLE
Unhandled case: market data subscriptions lost upon IB server reconnection

### ISSUE THREAD

**Issue by rgeronimi** [erdewit/ib_insync#256]
IB error 1101 indicates that the IB server (gateway) lost all the market data subscriptions between the disconnection and reconnection of the client:
https://interactivebrokers.github.io/tws-api/message_codes.html

I have not managed to reproduce this case to test how the ib_insync library behaves in such case.
Thus I don't know if this is a legacy IB error code or if it's still current.

This 1101 error code doesn't seem to be handled in ib_insync code. So it is currently the responsibility of the client to be aware of this and handle it accordingly.

2 strategies are possible :
(1) Keep it unhandled by ib_insync. The client has to be aware of it and is responsible for managing it (through the ib.errorEvent callback)
(2) Handle automatically re-submission of market subscriptions, as the ib_insync library already handles all of them

The philosophy of ib_insync seems to be to "just make it work" and not keep important IB side effects in the dark so maybe (2) shall be preferred.

**Comment by erdewit** [comment]
IB-insync makes no attempt to shield the user from any of the vast variety of market data failures that can occur, of which error 1101 is just one vary rare case.

What works works well in practice is to reconnect directly on error 1100 and then resubscribe.
