### ISSUE TITLE
reqHeadTimeStamp on indexes

### ISSUE THREAD

**Issue by algoterranean** [erdewit/ib_insync#258]
When I attempt to request the head timestamp for an index, say:

```
c = Contract(symbol='SPX', secType='IND', exchange='CBOE')
self.reqHeadTimeStamp(c, whatToShow='TRADES', useRTH=False)
```

I don't receive any information back. In fact, not only don't I get any info, the function just never returns at all and never triggers a timeout. There is also nothing in the log files (log level = DEBUG) indicating an issue, and nothing in the ib_insync or IB docs indicating this would be an issue.

I have tested out several indices on different exchanges, and they all run into the same issue, and I have no problem pulling, say, STK or FUT head timestamps. I also have no problem pulling data on these indices in general.

Any suggestions?

I am using ib_insync `0.9.59`, python `3.8.2`, and IB Gateway `972.1y`

**Comment by erdewit** [comment]
No idea, the contract works for me and returns ``datetime.datetime(2004, 3, 4, 14, 30)``. Best to ask IBKR about this.

**Comment by algoterranean** [comment]
Thanks, I will.
