### ISSUE TITLE
open interest for options 

### ISSUE THREAD

**Issue by TonyTang1997** [erdewit/ib_insync#259]
Is it possible for us to get the open interest for each option contract? I cannot find it right now in the after reqTickers(contract)

**Comment by erdewit** [comment]
With the snapshot tickers that are used by ``reqTickers`` it's not possible. With streaming tickers it is possible with generic tick 101:

https://ib-insync.readthedocs.io/api.html?#ib_insync.ib.IB.reqMktData

**Comment by noobymcnoob** [comment]
I've spent 4 days driving myself nuts trying to figure this out. Should've just come here.

**Comment by drusakov778** [comment]
@noobymcnoob -the discussion group at https://groups.io/g/insync/topics can be even better

**Comment by fridary** [comment]
> With the snapshot tickers that are used by `reqTickers` it's not possible. With streaming tickers it is possible with generic tick 101:
> 
> https://ib-insync.readthedocs.io/api.html?#ib_insync.ib.IB.reqMktData

This is extremely important questions, so it's impossible to get historical open interest data? Like some days/months ago.

**Comment by jiehunt** [comment]
I am so sorry, i am new in ib API.
I also want to get the oepn interest data from market.
the code should like this ?

ib.reqMktData(contract, '101', False, False)
tiker = ib.tiker(contract)
ib. sleep(2)

then , get the openinterest from tiker?
but I can get those infor from that.
could you please give me a example code ?

thank you very much.

**Comment by drusakov778** [comment]
> > With the snapshot tickers that are used by `reqTickers` it's not possible. With streaming tickers it is possible with generic tick 101:
> > https://ib-insync.readthedocs.io/api.html?#ib_insync.ib.IB.reqMktData
> 
> This is extremely important question, so it's impossible to get historical open interest data? Like some days/months ago.

my understanding is that the answer is no:
https://groups.io/g/insync/topic/75312604#4960

and re @jiehunt - you should post how-to questions in the forum, https://groups.io/g/insync
