### ISSUE TITLE
Dividend Events Calendar

### ISSUE THREAD

**Issue by joseph-henry** [erdewit/ib_insync#26]
First off, thanks for writing this. It seems to work well so far. 

But I had a question, I didn't see anything in here about getting dividend calendar event data. Is this something that I can request via ib_insync? If not, is this feature on the roadmap?

Thanks!

**Comment by erdewit** [comment]
I'm not aware of a dividend calendar in the IB API. If there is any and ib_insync does not expose it let me know.

**Comment by vertangelx** [comment]
I'm trying to achieve something similar, is there a way to get a contract's dividends, such as the next dividend date? 

https://interactivebrokers.github.io/tws-api/tick_types.html#ib_dividends

**Comment by erdewit** [comment]
Thanks for the suggestion vertangelx. I've added Ticker.dividends (for the next release) and it can be used like:

```python
from ib_insync import *
ib = IB().connect()
contract = Stock('MSFT', 'SMART', 'USD')
ib.qualifyContracts(contract)
ticker = ib.reqMktData(contract, '456') 
IB.sleep(4)
print(ticker.dividends)
```
output:
```
Dividends(past12Months=1.62, next12Months=1.68, nextDate=datetime.date(2018, 5, 16), nextAmount=0.42)
```

**Comment by vertangelx** [comment]
Thank you so much for the swift updates!!!

How often do you push out new releases?

**Comment by erdewit** [comment]
There's a new release now with the dividends.
