### ISSUE TITLE
Right, continuous futures don't support real-time data, but can we help get the "current contract"

### ISSUE THREAD

**Issue by goodboy** [erdewit/ib_insync#263]
It shamefully took me a little while to find it in the docs, but they are clear about this:

>Continuous futures are available from the API with TWS v971 and higher. Continuous futures cannot be used with real time data or to place orders, but only for historical data.

I wonder if maybe there should be a helper function in `ib_insync` to get the current non-continuous contract that IB reports as the continuous one? Hopefully I haven't missed an existing solution for this.

In TWS you can of course get this functionality by clicking on the currently labelled continuous contract and I would assume that underneath it does the same kind of lookup to a specific contract as I'm suggesting here.

Thoughts?

**Comment by erdewit** [comment]
If your quest is to get what IB considers the front contract, then this can be done by qualifying the ``ContFuture`` contract. It's ``conId`` is that of the front contract. The front contract is then constructed by qualifying ``Future(conId=...)``.

**Comment by goodboy** [comment]
@erdewit amazing thanks for the tip :)

Do you think it's not worth wrapping this detail so that users can subscribe for data from this *qualified contract*?
