### ISSUE TITLE
Better document the async API

### ISSUE THREAD

**Issue by goodboy** [erdewit/ib_insync#264]
As per discussion in #262 I think the project could do well with more async API docs (since there appears to be mostly none) which better demonstrate the feature set and core functionality.

I am happy to contribute a PR on this front @erdewit as part of my integration work.

Features that would greatly benefit from this:
- ticker streaming using the async iterator interface of `EventKit.Event`
- batch requesting symbol and contract data using i/o concurrency
- tick-by-tick data streaming
- order entry and monitoring

**Comment by goodboy** [comment]
#265 is a perfect example of why this is needed.

**Comment by goodboy** [comment]
@erdewit on further thought I think that all the async methods should be brought out of the `IB` class and placed on a lower level `API` type that the `IB` methods can delegate to. This would also reduce any need for `xxxAsync` suffixes on method names which doesn't seem all that useful or enlightening (I'm actually auguing that the async api should be *first class* - if anything `xxxSync` should be the suffix for the wrapping sync api). It would also make auto-docs from the type defs a lot more sparse. It also means you could autogen the sync api methods from the async method names at runtime and not have all this method duplication.

**Comment by drusakov778** [comment]
hello Erdewit, Goodboy,

the more I am following the discussion of the last few days, here and in the original #262 thread, the more I see a point in goodboy's comments and suggestions. Purely async framework, without the need of patching + separate synchronous framework either by re-entrant loops or potentially in separate thread may be indeed a nice framework. 

However, I think that ib_insync as it is at the moment is pretty self-contained project, which is already widely used, so taking changing the interface of current ib-class is not possible and not desirable for backward compatibility considerations. It is quite good as it is [with potential addition of some async counterparts to main functions, see #267].

What can be done for an advanced async-ib-in-separate-thread main-thread-sync API is to implement a synchronous interface in a separate say IB2, or IBThrd class and leave current ib "as is". This new class can be either here (preferrable), or even in a separate github project, if someone wants to take this task on him

**Comment by goodboy** [comment]
@drusakov778 the reality is `ib_insync` is **only async**.

You can't have an api that has to yield incrementally to an `asyncio` loop (despite using the methods meant to be called from non async functions to accomplish this) to make things work. And, I mean **all the things**. Yes, it *kinda works* running the event loop incrementally using `ib_insync.util.run()` and `.sleep()` but that's only because the scheduled tasks are short living. **Everything breaks** when you do streaming because now supposedly synchronous code can't actually block without disrupting the ongoing TCP connection because the loop hasn't been given back control. Then all of a sudden you're asking a sync api user to do `.sleep(0)` which is effectively the same thing as `await sleep(0)` (aka "pumping the event loop" or known in more modern async framework parlance as a [check point](https://trio.readthedocs.io/en/stable/reference-core.html#checkpoints)).

The reality is a synchronous api never has to worry about blocking other code, period.
Almost all serious projects separate their sync and async apis:
- the [client apis  in `httpx`](https://github.com/encode/httpx/blob/master/httpx/_client.py#L389) are separated exactly in this way

>However, I think that ib_insync as it is at the moment is pretty self-contained project

What do you mean?
I came to this project and immediately was massively confused by the api and docs.
I shouldn't have to read the core protocol implementation to know how to use the documented api because I don't know where I'm allowed to block and where I'm not :sweat_smile: 

In my opinion **there shouldn't even be a sync api** in this project.
- It really doesn't make a lot of sense; it's wrapping an asynchronous request/response protocol over a TCP socket which can also support long living streams. 
- `asyncio` is the natural fit for this type of system if you want single threaded parallelized I/O 
- A user should be responsible to figure how to run `asyncio` code from their sync code all on their own; it's not exactly a new problem :wink: (oh wait, that's what they have to do right now anyway - because **there is no sync api** see #266, #265).

If you're going to offer a sync api why not look at how other projects who have this same architecture do that?

Regarding,
>so changing the interface of current ib-class is not possible and not desirable for backward compatibility considerations. 

This is exactly why [deprecation warnings are a thing](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) :roll_eyes:. You don't just blindly change out the pretend sync methods, you do it on a major version release and prepare all users for it with warnings on a minor release.

I guess this comes down to what @erdewit wants for the project.
I personally think it has great potential and a decent design but there's always room to grow and for me that means proper docs for the async api and how to use it effectively for serious (production grade) systems. Part of that is not having to append an `Async` suffix to every method. Let me say it again, **there is nothing here that is not async**. This is why I've opened this issue.

>What can be done for an advanced async-ib-in-separate-thread main-thread-sync API is to implement a synchronous interface in a separate say IB2, or IBThrd class and leave current ib "as is".

Firstly, imo this isn't advanced; it's a standard well known solution.
I don't think it matters a ton which type ends up having which methods, whether you keep the pretend sync api or not. The main point is don't make the main docs for this project be on the "sync api" that is the most confusing (and frankly wrong) and then have the most useful api (async) that is actually quite nice (especially when you see the features of `EventKit`) not be documented anywhere except for:
>Asynchronous: All methods that have the “Async” postfix. Implemented as coroutines or methods that return a Future and intended for advanced users.

You know what's a good indicator that a method is async, [the `async def`](https://github.com/erdewit/ib_insync/blob/master/ib_insync/ib.py#L1614) :wink:


In my opinion making a better documented (and exposed) async api should take much higher priority then #262.

Frankly, #262 is just to make it so you don't have to worry about `asyncio`; currently that's simply not the case if you want to do anything more then simple commands (request/response) to the IB api.

My mantra is always to try to help the projects I use get better over time, if they can be improved.
Right now I think there's a really big hole in the docs showing how to properly use this framework.

**Comment by erdewit** [comment]
More documentation or recipes are always welcome! Or a notebook that showcases async usage would be cool.

I'm fairly sure that the vast majority of ib_insync users (who tend to be beginners or non-programmers) use only the sync part. Asynchronous programming is just difficult, even for programmers. For advanced users that already are familiar with asyncio it tends to be pretty straightforward to pick up ib_insync and integrate it with other async frameworks. The async methods just mirror the sync ones; The docstrings are not duplicated for the async methods. Of course it's crucial to understand why the event loop should not be blocked; This comes with the territory when using asyncio. Or event-driven frameworks in general, like javascript or Qt. In return it gives a concurrency that is relatively easy to reason about, without getting into race conditions. "The "One Rule" is a price that is consciously paid for that.

About splitting up the IB class into a sync and async namespace,  just to avoid having to type "Async", I don't really think it's worth the bother. Perhaps a wrapper class that has the renamed async methods and no sync methods.

**Comment by erdewit** [comment]
A recipe for async usage is added to the documentation. More advanced usage is up to the user to explore.

**Comment by markmark1** [comment]
@goodboy this would be very valuable

Features that would greatly benefit from this:

ticker streaming using the async iterator interface of EventKit.Event
batch requesting symbol and contract data using i/o concurrency
tick-by-tick data streaming
order entry and monitoring
