### ISSUE TITLE
ProcessPoolExecutor() not working with ib async functions

### ISSUE THREAD

**Issue by fridary** [erdewit/ib_insync#265]
Hello, thank you very much for great plugin.
I am using python 3.7.7 and ib_insync 0.9.61 and have a problem to execute and run IB API functions simultaneously (parallel), because there are a lot of stocks that need to be loaded just in one moment.

This is very simple code I tried with ProcessPoolExecutor()

```
from ib_insync import *
import concurrent.futures
import asyncio

def trader (ticker):
	print('A')
	df = ib.reqHistoricalData(
		Stock(ticker, 'SMART', 'USD'),
		endDateTime='',
		durationStr='2 D',
		barSizeSetting='1 min',
		whatToShow='TRADES',
		useRTH=True,
		formatDate=1)
	print('B')


ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)

with concurrent.futures.ProcessPoolExecutor(max_workers=2) as executor:
	futures = {executor.submit(trader, t) for t in ['AAPL', 'TSLA']}
```
The result is simple:
```
A
A
```
So it does not get any errors and reqHistoricalData() I don't know why, it just fails to keep executing and don't reach print('B'). Even if I play and add async to def trader or ib.connect inside, it does not load.

Then I tried to work with ThreadPoolExecutor():

```
from ib_insync import *
import concurrent.futures
import asyncio

import nest_asyncio
nest_asyncio.apply()


async def trader (ib, ticker):
	print('A')
	df = await ib.reqHistoricalDataAsync(
		Stock(ticker, 'SMART', 'USD'),
		endDateTime='',
		durationStr='2 D',
		barSizeSetting='1 min',
		whatToShow='TRADES',
		useRTH=True,
		formatDate=1)
	print('B')


async def main(loop):
	ib = IB()
	ib.connect('127.0.0.1', 7497, clientId=1)
	with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
		result = await loop.run_in_executor(executor, trader, ib, 'AAPL')

if __name__ == "__main__":
	loop = asyncio.get_event_loop()
	loop.run_until_complete(main(loop))

```
Error is 
```
RuntimeWarning: coroutine 'trader' was never awaited
  handle = None
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
If I add await, it says
```
result = await loop.run_in_executor(executor, await trader, ib, 'AAPL')
TypeError: object function can't be used in 'await' expression
```
Finally I tried to use only async, but regarding to this https://stackoverflow.com/questions/62543529/how-to-do-math-operations-in-python-with-asyncio-parallel-multiprocessing I can not use async to run functions parallel like reqHistoricalData(). I do this code and it runs consistently:

```
import time
import asyncio
from ib_insync import *

class Trader:
    def __init__(self, ticker):
        self.ticker = ticker

    async def _init(self):
        print('{} started'.format(self.ticker))
        await self.op()
        print('{} ended'.format(self.ticker))

    async def op(self):
        df = await ib.reqHistoricalDataAsync(
            Stock(self.ticker, 'SMART', 'USD'),
            endDateTime='',
            durationStr='2 D',
            barSizeSetting='1 min',
            whatToShow='TRADES',
            useRTH=True,
            formatDate=1)

        # if you don't have market subscription, you can check execution on math operations below
        # a = range(1000000) 
        # b = [] 
        # for i in a:
        #     b.append(i*2)

async def fetch_tickers():
    return await asyncio.gather(*(asyncio.ensure_future(safe_trader(ticker)) for ticker in ['AAPL', 'TSLA', 'FSLY', 'INO', 'OSTK', 'GO', 'NK', 'CHGG', 'HOLX', 'ORCL', 'AAL', 'GRPN']))

async def safe_trader(ticker):
    async with sem:
        t = Trader(ticker)
        return await t._init()

if __name__ == '__main__':
    ib = IB()
    ib.connect('127.0.0.1', 7497, clientId=1)

    start_time = time.time()
    sem = asyncio.Semaphore(10)
    loop = asyncio.get_event_loop()
    results = loop.run_until_complete(fetch_tickers())
    print("%.2f execution seconds" % (time.time() - start_time))
```

Script executes in 1.16 seconds for 12 stocks. For 1 stock it will be 0.45 seconds.

**So the main question how correctly set up ProcessPoolExecutor() or any other options to run script simultaneously for working with IB API like reqHistoricalData()?** Thank you for help very much.

**Comment by goodboy** [comment]
@fridary it's funny, we were just discussing this in #262.

The real problem here is that this is the totally wrong approach.

**Comment by goodboy** [comment]
@fridary take a look at [this code](https://github.com/erdewit/ib_insync/issues/262#issuecomment-648786250) from @erdewit. Try to adapt your method calls to use the async api with `asyncio`.

**Comment by goodboy** [comment]
@erdewit imo this is a perfect example of a user being completely confused as to the difference between the async and sync apis and doing exactly the wrong thing to make things "work".

**Comment by erdewit** [comment]
The historical requests are all rate-limited so parallelizing the download will not speed it up much. Might as well download it serially and let IB determine the pace. This also avoids the connection being dropped by IB as a punishment for having to many requests.
