### ISSUE TITLE
provide ib.accountSummaryAsync()

### ISSUE THREAD

**Issue by drusakov778** [erdewit/ib_insync#267]
in a purely async framework which can not be patched, e.g. uvicorn, ib.accountSummary() can not be called since it tries to re-enter the asyncio loop on the first call [ via call to sync reqAccountSummary() and not async reqAccountSummaryAsync(), in [https://github.com/erdewit/ib_insync/blob/master/ib_insync/ib.py#L398](https://github.com/erdewit/ib_insync/blob/master/ib_insync/ib.py#L398) ]

it will be nice to provide a purely async version of this function.

Thank you

**Comment by goodboy** [comment]
Even more fuel for #264.

**Comment by erdewit** [comment]
Thanks for the bug report. I will add a ``accountSummaryAsync`` method.

In the mean time you can call  ``await ib.reqAccountSummaryAsync()`` after connecting, this will also fix it.

**Comment by erdewit** [comment]
An ``IB.accountSummaryAsync`` method has been added.
