### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'django-main-thread'

### ISSUE THREAD

**Issue by juan9222** [erdewit/ib_insync#271]
Hi, I'm trying to integrate ib-insync with django using django-channels to get real time data from interactive brokers using a socket and using reqTickByTickData. But I'm struggling with the initial connection. 

I wrote this line of code in services.py:
```
import json, nest_asyncio, asyncio
from ib_insync import *
ib = IB()
def connect_to_ib(): 
    print("Starting IB")
    ib_connection = ib.connect('127.0.0.1', 4002, clientId=1,timeout=4, readonly=False, account='')
    print("IB is Connected?", ib.isConnected())
    return ib_connection
```

but I'm getting this error:

```RuntimeError: There is no current event loop in thread 'django-main-thread'```

It worked in the past briefly and get an ib Object but I don't know why It fails now.

I read  #33 and #167 in order to solve this error but the problem persist. 
```
def create_evenloop():
    print("Starting Event Loop")
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    nest_asyncio.apply()
```

Those functions were called in a consumer in django channels, (normally django is blocking but AsyncWebsocketConsumer from channels make non-blocking code inside PlotterConsumer class )

```
class PlotterConsumer(AsyncWebsocketConsumer):
    create_evenloop()
    ib = connect_to_ib()
    ...
```

**Comment by goodboy** [comment]
:rofl: @juan9222 checkout #262 and #264.

The long story short is there is no synchronous api for you to use currently and if you want to integrate `asyncio` with other concurrency frameworks you have to know what you're doing. Nesting event loops will do nothing to help (and generally speaking is a dirty hack anyway).

**Comment by juan9222** [comment]
> 🤣 @juan9222 checkout #262 and #264.
> 
> The long story short is there is no synchronous api for you to use currently and if you want to integrate `asyncio` with other concurrency frameworks you have to know what you're doing. Nesting event loops will do nothing to help (and generally speaking is a dirty hack anyway).

So it means that i have to use IB API obligatorily?

**Comment by drusakov778** [comment]
no, I think goodboy has exaggerated the situation a bit in his response.

You can use ib_insync with any asyncio framework, but you should be careful to call async functions only, since all the sync-functions use the patching on the build-in python asyncio loop, which is obviously not working when you use non-native event loop. So, basic idea with any app which already has async-io capabilities - (1) start the app and it's own event loop, (2) call all only "async def xxxAsync()" functions from ib_insync framework (from your app's async functions)

The best place to look how it is done and ask additional questions is probably the ib-insync discussion group here, which has plenty of posts on the subject
[https://groups.io/g/insync](https://groups.io/g/insync)

**Comment by goodboy** [comment]
> So it means that i have to use IB API obligatorily?

@juan9222 no it means to use it with a non-`asyncio` framework (in an actual synchronous way) you have launch `ib_insync`'s event loop in another thread (just like you have to with every single-threaded asynchronous I/O system ever). If you want to understand the details just read #262.

Don't worry this isn't your fault. The documentation is extremely unclear about this.

**Comment by juan9222** [comment]
> no, I think goodboy has exaggerated the situation a bit in his response.
> 
> You can use ib_insync with any asyncio framework, but you should be careful to call async functions only, since all the sync-functions use the patching on the build-in python asyncio loop, which is obviously not working when you use non-native event loop. So, basic idea with any app which already has async-io capabilities - (1) start the app and it's own event loop, (2) call all only "async def xxxAsync()" functions from ib_insync framework (from your app's async functions)
> 
> The best place to look how it is done and ask additional questions is probably the ib-insync discussion group, which has plenty of posts on the subject
> https://groups.io/g/insync

To be honest I saw all topics about this error in https://groups.io/g/insync but I still don't get it. 

I used keywords "runtime error" and "django", but I didn't saw something useful about it to apply inside my code.

I already did this on settings.py while I was reading this https://docs.djangoproject.com/en/3.0/topics/async/ in order to enable async support. But it was futile.
````
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
````
I already worked with async code with Javascript and Node.js .I know a little bit about concurrency and event loops applied to async code. But I think I'm missing something important about it under the hood.

I nested the event loop because I was getting another error 
````
RuntimeError: Cannot run the event loop while another loop is running
````
In the forum they don't talk about django-main-thread, and everyone with Runtime error refers to 'Dummy-Thread' instead. 

Do I have to install tornado (or another asyncio framework) in order to work properly?

**Comment by juan9222** [comment]
> no, I think goodboy has exaggerated the situation a bit in his response.
> 
> You can use ib_insync with any asyncio framework, but you should be careful to call async functions only, since all the sync-functions use the patching on the build-in python asyncio loop, which is obviously not working when you use non-native event loop. So, basic idea with any app which already has async-io capabilities - (1) start the app and it's own event loop, (2) call all only "async def xxxAsync()" functions from ib_insync framework (from your app's async functions)
> 
> The best place to look how it is done and ask additional questions is probably the ib-insync discussion group, which has plenty of posts on the subject
> https://groups.io/g/insync

I think I partially solved my problem following your instructions. 

Inside my django channels consumer class I have a coroutine method called "price" and inside it I put this:
````
    async def price(self, event):
        await create_evenloop()
        ib = await connect_to_ib()
        message =  "Hi"
        await self.send(text_data=json.dumps({
            'message': message
        }))
````
A pair of awaits inside the coroutine for create event loop and for ib connect method.

Then I just rename my functions as coroutines with async def create_evenloop(): and async def connect_to_ib(): 

but I'm getting this error right now 
````
RuntimeError: Cannot enter into task <Task pending name='Task-12' coro=<RedisChannelLayer._clean_receive_backup()
````
I'm using redis for caching.

**Comment by drusakov778** [comment]
I think this topic is more appropriate for https://groups.io/g/insync. That group is quite active and I am sure people will be able to help you there.

**Comment by erdewit** [comment]
> `RuntimeError: There is no current event loop in thread 'django-main-thread'`

It's probably just a matter of deploying it properly for asyncio:
https://channels.readthedocs.io/en/latest/deploying.html#configuring-the-asgi-application

That should present a running event loop, and after that it's a matter of using async-compatible code only, as @drusakov778 already said. This includes connectAsync instead of connect.

Creating a new event loop, nesting the loop or running in a separate thread is all unnecessary.

**Comment by juan9222** [comment]
Thank you @goodboy, @erdewit and @drusakov778  for your help. You guys are right, I didn't had the need to use nest_asyncio or create a new event loop. Everything was running inside django's main thread so I was forced to write async code only to make it work properly. I solved my problem this way:
```
from ib_insync import *

async def connectToIB(): 
    ib = IB()
    print("Starting IB")
    ibConnectionPromise = ib.connectAsync('127.0.0.1', 4002, clientId=1,timeout=4, readonly=False, account='')
    return ibConnectionPromise
    
async def requestTick(ibConnectionPromise):
    ib = await ibConnectionPromise
    currentTimePromise = ib.reqCurrentTimeAsync()
    currentTime = await currentTimePromise
    currentTimeString = currentTime.strftime("%d-%b-%Y (%H:%M:%S.%f)")
    return currentTimeString

async def disconnect_to_ib(ibConnectionPromise):
    ib = await ibConnectionPromise
    ib.disconnect()
```

Right now I'm continuing the issue trying to get real time data in the forum that @drusakov778 mentioned above, right now it's pending to approve https://groups.io/g/insync/topics.

**Comment by jchow-hedgedesk** [comment]
@juan9222 was this ever resolved? I'm running into the same issue when trying to run my local server in django
