### ISSUE TITLE
ib_insync.FlexReport is hanging

### ISSUE THREAD

**Issue by sam-huang1223** [erdewit/ib_insync#273]
Hi,

I have been successfully using a script to download a flexquery (trading activity) for the last few weeks - however today it seems like the download isn't working anymore (nothing has changed). It just hangs for >10 minutes.

In the docs you mentioned that the server could go down on weekends, but it's a Monday morning right now. Is this because the server is down unexpectedly? If so, do you know how I could check this?

Thanks,
Sam

**Comment by sam-huang1223** [comment]
actually seems like it's working now - however it looks like the server for flex queries was down in the morning - for future reference, is there any way to check the flex query server status?

**Comment by erdewit** [comment]
> for future reference, is there any way to check the flex query server status?

I don't think there is.
