### ISSUE TITLE
We're discarding trade RT Volume times

### ISSUE THREAD

**Issue by goodboy** [erdewit/ib_insync#274]
- [Ticker.lastSize](https://github.com/erdewit/ib_insync/blob/master/ib_insync/ticker.py#L54) is `float`
- [TickData.size](https://github.com/erdewit/ib_insync/blob/master/ib_insync/objects.py#L206) is `int`

Is there a reason to do with different asset types?

I'm also noticing some duplicate code where this seems to be set in `Wrapper.tickString()`:
- [block for handling tick types `48` **and** `77`](https://github.com/erdewit/ib_insync/blob/master/ib_insync/wrapper.py#L747-L772) where `Ticker.lastSize` is set as an `int`
- [block for handling tick types `77`](https://github.com/erdewit/ib_insync/blob/master/ib_insync/wrapper.py#L783-L805) where `Ticker.lastSize` is also set as an `int`

Actually these two blocks look almost identical minus [this little nested branch section](https://github.com/erdewit/ib_insync/blob/master/ib_insync/wrapper.py#L754-L757).
I'm pretty sure these could be factored.

I'm only looking at this because I realized we're **always** discarding the [RT Volume](https://interactivebrokers.github.io/tws-api/tick_types.html#rt_volume), [clearing time](https://github.com/erdewit/ib_insync/blob/master/ib_insync/wrapper.py#L752) from the exchange.

This pairs with questions I had in #272.
Normally i would expect tick data to have the exchange clearing time for any trades/volume.

As an example (after I've patched the code - don't worry I'll make a PR) this is what I now see from my streaming tick data after adding a `last_fill_time` field from the exchange clearing time we are discarding:
```python
trio got: {'time': 1593468211.4448721, 'tickType': 3, 'price': 3046.5, 'size': 4, 'last_fill_time': None}
trio got: {'time': 1593468211.6727612, 'tickType': 77, 'price': 3046.25, 'size': 7, 'last_fill_time': 1593468211.081}
trio got: {'time': 1593468211.6734376, 'tickType': 3, 'price': 3046.5, 'size': 7, 'last_fill_time': None}
trio got: {'time': 1593468211.6734376, 'tickType': 3, 'price': 3046.5, 'size': 7, 'last_fill_time': None}
trio got: {'time': 1593468211.6734376, 'tickType': 3, 'price': 3046.5, 'size': 7, 'last_fill_time': None}
trio got: {'time': 1593468211.872757, 'tickType': 77, 'price': 3046.25, 'size': 1, 'last_fill_time': 1593468211.281}
trio got: {'time': 1593468211.872757, 'tickType': 77, 'price': 3046.25, 'size': 1, 'last_fill_time': 1593468211.281}
trio got: {'time': 1593468212.3658435, 'tickType': 48, 'price': 3046.25, 'size': 1, 'last_fill_time': 1593468211.774}
trio got: {'time': 1593468212.3662589, 'tickType': 77, 'price': 3046.25, 'size': 1, 'last_fill_time': 1593468211.774}
trio got: {'time': 1593468212.3925517, 'tickType': 77, 'price': 3046.25, 'size': 8, 'last_fill_time': 1593468211.801}
trio got: {'time': 1593468212.3925517, 'tickType': 77, 'price': 3046.25, 'size': 8, 'last_fill_time': 1593468211.801}
trio got: {'time': 1593468212.6746254, 'tickType': 8, 'price': -1.0, 'size': 1699, 'last_fill_time': None}
trio got: {'time': 1593468212.6753259, 'tickType': 0, 'price': 3046.25, 'size': 5, 'last_fill_time': None}
trio got: {'time': 1593468212.6753259, 'tickType': 3, 'price': 3046.5, 'size': 8, 'last_fill_time': None}
trio got: {'time': 1593468212.6753259, 'tickType': 0, 'price': 3046.25, 'size': 5, 'last_fill_time': None}
trio got: {'time': 1593468212.6753259, 'tickType': 3, 'price': 3046.5, 'size': 8, 'last_fill_time': None}
```
Hey @drusakov778, look you can actually see the exchange -> `ib_insync` latency now :wink:.

**Comment by goodboy** [comment]
Also in case it wasn't clear, the `time` field above is just from assigning `time.time()` to `Wrapper.lastTime` in `.tcpDataArrived()`.

**Comment by drusakov778** [comment]
nice : )
different size types may be a typo or ib-insync may be following some IB-internal nuances (although I can not find anything related at the moment).

this reminds me of an interesting recent discussion in ib-insync group that apparently IB does allow fractional share trading (via TWS itself if I understand correctly, but not via API)
[https://groups.io/g/insync/topic/fractional_shares_in/75064689](https://groups.io/g/insync/topic/fractional_shares_in/75064689)

**Comment by goodboy** [comment]
>that apparently IB does allow fractional share trading 

Ahh right I do remember seeing this in the bulletins.
Hmm I wonder what is best then?
Really there shouldn't be too much trouble one way or the other (`int` vs. `float`).

That's pretty interesting if they do eventually offer fractional shares orders through the API.
In that case I guess we definitely want the `float`.

Has anyone messaged their tech team to ask about this?

**Comment by drusakov778** [comment]
not spoken to their tech team, as fractional trading is a bit offside for us at the moment.

general approach with ib-insync is to keep as close to the "source" IB API are possible, e.g. see #252 , so it probably makes sense to keep it as 'int' if these fields are actually 'int' in IB messages, at least up to a moment IB changes it on their side

**Comment by erdewit** [comment]
The ``Ticker.lastSize`` is typed as ``float`` with an eye towards to future... IB is rather behind the times with this, compared to for example the crypto exchanges. Would not work well with only whole bitcoins. Another reason is that NaN as default value is quite convenient. Plus it's perfectly fine to assign an int to it:
https://www.python.org/dev/peps/pep-0484/#the-numeric-tower

**Comment by erdewit** [comment]
> ```python
> trio got: {'time': 1593468212.3925517, 'tickType': 77, 'price': 3046.25, 'size': 8, 'last_fill_time': 1593468211.801}
> ```

This is a good example of the lack of readability of using floats for time.

**Comment by goodboy** [comment]
> lack of readability

@erdewit agreed :100: but to be fair you shouldn't be reading the epoch time directly for measurements, eg. you should be reading the differences/delta for latency.

What do you think about nanoseconds as an `int` as returned by [`time.time_ns()`](https://docs.python.org/3/library/time.html#time.time_ns)?

I would very much prefer this time stamp used internally and on primitive data types allowing the user to choose what higher level time format in their own code.

**Comment by goodboy** [comment]
@erdewit also I was going to close this issue via #275?

The issue isn't actually solved yet?

**Comment by erdewit** [comment]
> What do you think about nanoseconds as an `int` as returned by [`time.time_ns()`](https://docs.python.org/3/library/time.html#time.time_ns)?

I think the current datetimes are perfectly fine and don't need replacing with anything.

**Comment by erdewit** [comment]
Sure, go ahead.

**Comment by erdewit** [comment]
The realtime timestamp is now available as ``Ticker.rtTime``.
