### ISSUE TITLE
Error appears unhandled

### ISSUE THREAD

**Issue by noobymcnoob** [erdewit/ib_insync#277]
With the following code, I get a message on TWS:

```
contract = ib.ContFuture("SPX",exchange="SMART",currency="USD")
conn.reqContractDetails(contract)
```

![image](https://user-images.githubusercontent.com/38162004/86151649-04370c80-bacd-11ea-8243-bccca1a9483a.png)

This causes a timeout on the client side. I'm not sure if an error message is being dropped or not. Using the right exchange (GLOBEX) fixes the issue.

**Comment by noobymcnoob** [comment]
Updated the code, was missing `reqContractDetails`

**Comment by erdewit** [comment]
> ```
> contract = ib.ContFuture("SPX",exchange="SMART",currency="USD")
> conn.reqContractDetails(contract)
> ```

I remember the CONT_FUT type of contract  is not accepted for every type of request, so probably better to create a new Future contract afterwards:

```python
fut = Future(conId=contract.conId)
conn.reqContractDetails(fut)
```
