### ISSUE TITLE
API docs incomplete on MktDepthData field definitions

### ISSUE THREAD

**Issue by Kagaratsch** [erdewit/ib_insync#279]
In the API docs the section on [MktDepthData objects](https://ib-insync.readthedocs.io/api.html#ib_insync.objects.MktDepthData) does not provide explanation for the different fields present in the object. Particularly the fields 'position', 'operation', or 'side' are not self-explanatory in the context of market data. Additionally, considering that DOMLevel entries are updated automatically in a ticker object, the purpose of the additionally included MktDepthData is not clear. Any clarification?

**Comment by Kagaratsch** [comment]
Perhaps the docs could link the following IB page for the definitions of these fields:
https://interactivebrokers.github.io/tws-api/interfaceIBApi_1_1EWrapper.html#ab0d68c4cf7093f105095d72dd7e7a912

**Comment by erdewit** [comment]
It's documented at the method level, with a link to the relevant IBKR entry:

https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.reqMktDepth
