### ISSUE TITLE
.placeOrder(contract, order).     multiple stocks in one time?

### ISSUE THREAD

**Issue by lamhoson** [erdewit/ib_insync#280]
contract=Stock(symbol='1', exchange='SMART', currency='HKD', primaryExchange='SEHK')
.placeOrder(contract, order).

Any method put an order for multiple stocks in one time?  Say symbol=['1', '2', '3'], 3 stocks in one time.

**Comment by erdewit** [comment]
Other than using a Bag contract with multiple legs, it's one instrument per order.
