### ISSUE TITLE
Change to raising exceptions on errors

### ISSUE THREAD

**Issue by Rizhiy** [erdewit/ib_insync#281]
Hi, currently when operation doesn't succeed most of the time an error is logged, but otherwise code executes correctly. This is a bit annoying since I have to add additional checks that operations succeed. For example if call to `qualifyContracts` fails, it logs as much, but continues as normal, so I have to check that contract is actually qualified afterwards.

Can you instead throw exception when something fails, so I can handle it properly?

**Comment by goodboy** [comment]
A big :+1: on me for this.
I was actually going to put up a PR.

It's really frustrating to not have errors from the API raised when you give bad or invalid input.

**Comment by Rizhiy** [comment]
Similar thing with orders, if order is rejected would be nice to throw exception.

**Comment by noobymcnoob** [comment]
It cannot always throw exceptions for all errors. For example, what happens if an order is cancelled for some random reason after control returns? When should it throw the exception? 

Instead, you should subscribe to `IB.errorEvent`

**Comment by Rizhiy** [comment]
@noobymcnoob Well obviously, shit happens and you can't check everything, but there are plenty of obvious places where it would be nice to use exceptions.

**Comment by erdewit** [comment]
> For example if call to `qualifyContracts` fails, it logs as much, but continues as normal, so I have to check that contract is actually qualified afterwards.

What if 10 contracts are supplied and only one fails? Should it throw or not....?

The philosophy is to only use exceptions for technical error situations, such as socket disconnects. 
While it would be possible to use exceptions for the request-response type of operations, it would still be necessary to check the result even if no exception was thrown. Exceptions are no good for the pub-sub parts of the API, which is were the real meat is with the order handling and realtime data.
