### ISSUE TITLE
Interaction with script

### ISSUE THREAD

**Issue by JSunRae** [erdewit/ib_insync#285]
How do you interact with this? I can run a python script no problem. But I cannot seem to find a way to then manually type in requests or cancel requests like for fundamental data, live ticks.

IE. At times I want to manually intervene, and make the script focus on other stocks. In terminal, it does not allow for inputs while running. If I run in Visual Code, and try to type something in the 'Debug Console' Most of the time I just get the variable is not defined.

What am I missing here?

**Comment by erdewit** [comment]
For interactive use I would suggest to use a notebook (like Jupyter Lab).
