### ISSUE TITLE
bracketOrder(), but start with a market order as parent

### ISSUE THREAD

**Issue by lamhoson** [erdewit/ib_insync#288]
Is there any means to place a bracket-order, but the master parent order is a market price buy-order instead?  It is no limit buy price.

def bracketOrder(
            self, action: str, quantity: float,
            **limitPrice**: float, takeProfitPrice: float,
            stopLossPrice: float, **kwargs) -> BracketOrder:
        """

**Comment by erdewit** [comment]
Please see #291
