### ISSUE TITLE
socket.send() raised exception !

### ISSUE THREAD

**Issue by lamhoson** [erdewit/ib_insync#289]
The program keeps on printing "socket.send() raised exception" to console but seems still running.

Does anyone know what I should do?  Stop the program or just let it run to continue the computer trading algorithm?

Vers:
- Python 3.7
- ib_insync-0.9.61

**Comment by erdewit** [comment]
A socket exception like that would mean that there is no API connection any more. The program should ideally try to reconnect by itself, or be restarted by a human.
