### ISSUE TITLE
TickType

### ISSUE THREAD

**Issue by vertangelx** [erdewit/ib_insync#29]
Hi there,

When listening to every tick as they come in using `self.ib.setCallback('pendingTickers', onPendingTickers)`, an example of a tick received is 

    TickData(time=datetime.datetime(2017, 12, 18, 22, 43, 25, 352791, tzinfo=datetime.timezone.utc), tickType=2, price=1.17828, size=4000000)

    TickData(time=datetime.datetime(2017, 12, 18, 22, 43, 25, 352791, tzinfo=datetime.timezone.utc), tickType=3, price=1.17828, size=4000000)

Why are there 2 `TickData` with the same properties, but differing only in `tickType`?

What are `tickType` 2 and 3 referring to?

Which one of the `TickData` gives me the last traded price?

**Comment by erdewit** [comment]
The tickType's are defined [here](https://interactivebrokers.github.io/tws-api/tick_types.html).

Type 2 and 3 are ask price and ask size respectively. The second tick is superfluous here but that is just what IB is sending. Personally I use a filter to cut these sort of redundant ticks.
