### ISSUE TITLE
BacketOrder with MarketOrder

### ISSUE THREAD

**Issue by vishr** [erdewit/ib_insync#291]
`bracketOrder()` has hard coded LimitOrder and there is not way to override it - sometimes limit orders doesn't get executed and there should be an option to make it MarketOrder. For now, I have copied the entire function.

**Comment by erdewit** [comment]
Copying this bit of code and adjusting it to your needs is perfectly fine.

The ``orderType`` can also be modified after creating the bracket but this is a little bit messy. It works fine though.

**Comment by luketychtrading** [comment]
Apologies for reopening this issue..

How would you suggest creating a TRAIL instead of a STOP?
