### ISSUE TITLE
coroutine 'IBC.terminateAsync' was never awaited

### ISSUE THREAD

**Issue by wircho** [erdewit/ib_insync#292]
Running `ibc.terminate()` will create the coroutine terminateAsync, but never `await` it, so it doesn't actually run.

Running Python 3.7.7.

**Comment by erdewit** [comment]
``ibc.terminate()`` is not an async function so ``await`` is not legal to use inside it. As goodboy mentioned, it uses ``util.run`` which is the equivalent of ``await`` for synchronous functions.
