### ISSUE TITLE
reqHistoricalData API doesn't work beyond 50

### ISSUE THREAD

**Issue by vishr** [erdewit/ib_insync#293]
I tried to use `reqHistoricalData` with `keepUpToDate=True` for more than 50 tickers and I get the following error:

> Error processing request:Only 50 simultaneous API historical data requests

With `keepUpToDate=False` there are no issues. What could be the reason?

**Comment by zdytch** [comment]
Hey, when you face an error, google it first.

"The maximum number of simultaneous open historical data requests from the API is 50."
https://interactivebrokers.github.io/tws-api/historical_limitations.html

**Comment by vishr** [comment]
> Hey, when you face an error, google it first.
> 
> "The maximum number of simultaneous open historical data requests from the API is 50."
> https://interactivebrokers.github.io/tws-api/historical_limitations.html

I did, and I know about it. However, the confusion came when I manually called `client.wrapper.startSubscription` for more than 50 it worked.

**Comment by zdytch** [comment]
The common principle is to rely on documentation. Even if something seems to work against documentation, it's not guaranteed on distance and may be broken at any time.

For your task it seems better to use realtime methods? reqRealTimeBars, reqMktData, etc?
