### ISSUE TITLE
Error: This event loop is already running

### ISSUE THREAD

**Issue by CausalTruth** [erdewit/ib_insync#295]
Hi, I executed the example code in jupyter lab: 
```
from ib_insync import *
util.startLoop()  # uncomment this line when in a notebook

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)

contract = Forex('EURUSD')
bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='30 D',
    barSizeSetting='1 hour', whatToShow='MIDPOINT', useRTH=True)

df = util.df(bars)
print(df)
```

It says **RuntimeError: This event loop is already running**

**Comment by erdewit** [comment]
It works for me. You can try ``pip install -U nest_asyncio`` to see if that helps.

**Comment by CausalTruth** [comment]
> It works for me. You can try `pip install -U nest_asyncio` to see if that helps.

thanks - that worked!
