### ISSUE TITLE
How to get the TWS' display groups?

### ISSUE THREAD

**Issue by tankorsmash** [erdewit/ib_insync#297]
Usually with [the standard API](https://interactivebrokers.github.io/tws-api/display_groups.html), you call `client.queryDisplayGroups(reqId)`, so I do something similar with ib_insync, although I never get a response, and I'm not sure where the TWS' response would get handled with ib_insyc.

```python
import time
from ib_insync import IB

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=5)

ib.client.displayGroupList = lambda self, reqId, groups: print("client", groups) #should be on the wrapper, but just in case its duplicated here
ib.wrapper.displayGroupList = lambda self, reqId, groups: print("wrapper", groups)

results = ib.client.queryDisplayGroups(ib.client.getReqId())

time.sleep(5) #with a sleep or commented out
print(results)
print(ib.wrapper._results)
>>> None
>>> {}
```
These are just a few stabs in the dark, but the assertion fails because `ib.wrapper._results` is empty, and either print callback isn't called. 

Since `queryDisplayGroups` isn't given its own override in `ib.py`, is this simply not possible even using the client directly? 

---

I've never used async in python, so this could be totally nonsensical, but this just times out. I based it on how reqHistoricalData works, but I must be doing something wrong.

```python
class TempContainer:
    pass


async def query_display_groups():
    reqId = ib.client.getReqId()

    temp_container = TempContainer()
    future = ib.wrapper.startReq(reqId, None, container=temp_container)
    timeout = 5
    ib.client.queryDisplayGroups(reqId)
    task = asyncio.wait_for(future, timeout) if timeout else future
    await task

    return temp_container

results = ib._run(query_display_groups())
print(results)
print(ib.wrapper._results)
```

**Comment by erdewit** [comment]
```python
> ib.wrapper.displayGroupList = lambda self, reqId, groups: print("wrapper", groups)
```
Monkey patching can be done on the class level, in this case ``Wrapper.displayGroupList = lambda ...``.

It should happen before creating an IB instance, since the wrapper methods are gathered once during construction and the patched method must be present at that point.

**Comment by tankorsmash** [comment]
Awesome thank you. I also needed to call `_endReq` to not have the timeout. This is now resolved!

Here's the code for anyone else learning async


```python
import asyncio

from ib_insync import IB, Wrapper

def displayGroupList(self, reqId, groups):
    print("class wrapper", groups)
    self._endReq(reqId)

Wrapper.displayGroupList = displayGroupList

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=6)


class TempContainer:
    pass

async def query_display_groups():
    reqId = ib.client.getReqId()

    temp_container = TempContainer()
    future = ib.wrapper.startReq(reqId, None, container=temp_container)
    timeout = 2
    ib.client.queryDisplayGroups(reqId)
    print("awaiting")
    task = asyncio.wait_for(future, timeout) if timeout else future
    try:
        await task
        print("done awaiting")
    except asyncio.TimeoutError:
        print("timed out")

    return temp_container

try:
    results = ib._run(query_display_groups())
    print("results", results)
except Exception as e:
    print("error:", e)
```
