### ISSUE TITLE
Reduce Verbosity

### ISSUE THREAD

**Issue by vertangelx** [erdewit/ib_insync#30]
Is there a way to reduce the verbosity, especially when doing `ib.placeOrder`?

Calling that function prints a lot of `DEBUG` level details that I will like to disable.

Eg:  `2017-12-22 01:27:51 - DEBUG - decoder.py:1121 - arg USD type <class 'str'>`

**Comment by erdewit** [comment]
It's the IB API that's doing all this excessive logging on the root logger. 

In the util.logTo{Console, File} methods there is some attempt to filter this away, like

```python
def logToConsole(level=logging.INFO):
    """
    Create a log handler that logs to the console.
    """
    logger = logging.getLogger()
    logger.setLevel(level)
    formatter = logging.Formatter(
            '%(asctime)s %(name)s %(levelname)s %(message)s')
    handler = logging.StreamHandler()
    handler.setFormatter(formatter)
    handler.addFilter(lambda record: record.name != 'root')
    logger.addHandler(handler)
```
