### ISSUE TITLE
Finding order details using OrderId

### ISSUE THREAD

**Issue by athenawisdoms** [erdewit/ib_insync#31]
After using `ib.placeOrder` to place a Limit order, I get back an object containing an `orderId`.

How can the order details be retrieved again using it's `orderId`? For example, I can have a new script that check the order status every 5 minutes.

**Comment by erdewit** [comment]
You can either hold on to the trade object that ib.placeOrder returned, or find the trade in ib.trades() by orderId. The new script must use the same cliendId that the order was placed with (this is an IB API limitation).
