### ISSUE TITLE
Set CONTFUT conId to -1* conId of front contract to enable hashing

### ISSUE THREAD

**Issue by TheAIArchitect** [erdewit/ib_insync#310]
The Contract class currently doesn't allow hashing of CONTFUT Contracts because they get the same conId as the front contract, but if ib_insync set all conIds for CONTFUT to -1*conId (of the front contract), you could hash the CONTFUT, and it could make working with those sorts of contracts more streamlined.

Other than needing to set the conId to the empty string to actually request CONTFUT historical data (which I believe needs to be manually done at the moment anyway), I don't think that this would cause any trouble.

**Comment by erdewit** [comment]
Sure, that's a good idea.
