### ISSUE TITLE
reqHistoricalTicks() missing required 'startDateTime' when 'endDateTime' provided

### ISSUE THREAD

**Issue by dvasdekis** [erdewit/ib_insync#312]
Hi Ewald! Thanks again for an awesome library.

I'm using reqHistoricalTicks() to get data prior to 'now', and the [docs for reqHistoricalTicks](https://ib-insync.readthedocs.io/api.html?highlight=reqHistoricalTicks#ib_insync.ib.IB.reqHistoricalTicks) say that `One of startDateTime or endDateTime can be given, the other must be blank.`

However, I'm getting `TypeError: reqHistoricalTicks() missing 1 required positional argument: 'startDateTime'` when I use the function (I have imported `datetime` so `endDateTime=datetime.datetime.now()` should be valid). Error below: 
```
  File "/home/appuser/docker/src/hcp_ib_fetcher.py", line 19, in get_ticks
    return ib_conn.reqHistoricalTicks(contract=con_obj, endDateTime=datetime.datetime.now(), numberOfTicks=10, whatToShow='Bid_Ask', useRth=False, ignoreSize=True)
TypeError: reqHistoricalTicks() missing 1 required positional argument: 'startDateTime'
```

Any ideas? Thanks!

**Comment by erdewit** [comment]
So both start and end are required, and one of them must be an empty string.

**Comment by dvasdekis** [comment]
Thanks Ewald!
