### ISSUE TITLE
Capture realtime message from IB gateway

### ISSUE THREAD

**Issue by lamhoson** [erdewit/ib_insync#313]
Which API can my Python capture the message from IB?  Right now, it prints to console directly and my program cannot know it.

Error 201, reqId 210: Order rejected - reason:Account is closed
Canceled order: Trade(contract=Stock(symbol='1836', exchange='SEHK', currency='HKD'), order=LimitOrder(orderId=210, clientId=1, permId=2070433797, action='BUY', totalQuantity=3000.0, lmtPrice=7.949999999999999, transmit=False), orderStatus=OrderStatus(orderId=210, status='Cancelled', filled=0.0, remaining=3000.0, avgFillPrice=0.0, permId=2070433797, parentId=0, lastFillPrice=0.0, clientId=1, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(time=datetime.datetime(2020, 11, 9, 5, 0, 1, 255546, tzinfo=datetime.timezone.utc), status='PendingSubmit', message=''), TradeLogEntry(time=datetime.datetime(2020, 11, 9, 5, 0, 3, 271130, tzinfo=datetime.timezone.utc), status='Inactive', message=''), TradeLogEntry(time=datetime.datetime(2020, 11, 9, 5, 0, 4, 130527, tzinfo=datetime.timezone.utc), status='Cancelled', message='Error 201, reqId 210: Order rejected - reason:Account is closed')])

**Comment by erdewit** [comment]
There's the ``ib.errorEvent`` for that.

**Comment by lamhoson** [comment]
Hello,
            Any sample code on how to use this API?
            I need to capture the error message send from IB and email the message string out.

Hoson

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
