### ISSUE TITLE
QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

### ISSUE THREAD

**Issue by romanrdgz** [erdewit/ib_insync#314]
I am working with a pyqt5 application with ib_insync. I am loading a set of open orders and showing them in a table one I press the connect button. Worked fine so far.

I increased the number of open orders to around 50-60. Now, once I press the connect button, I get an endless stdout of messages with the text:
`QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)`

I have found no info on this. It seems that the "not enough quota" happens to some people while trying to copy large amounts of data from a local network, but not related to Qt5.

Is it possible that Qt is getting saturated by the amount of ib_insync events (or the amount of data received through them), and hence it has not enough quota to update the GUI?

**Comment by erdewit** [comment]
I don't know.
