### ISSUE TITLE
Forex('EURUSD') or Forex('CHFUSD') gets no market data or historical data : please help on how to use FOREX w ib inSync?

### ISSUE THREAD

**Issue by markmark1** [erdewit/ib_insync#316]
Error 162, reqId 53050: Historical Market Data Service error message:No historical market data for CHF/CASH@FXSUBPIP Last 300, contract: Forex('CHFUSD', conId=12087802, exchange='IDEALPRO', localSymbol='CHF.USD', tradingClass='CHF.USD')

**Comment by Shellcat-Zero** [comment]
From the error it sounds like there might not be data available for the date(s) specified in your request, but it's hard to tell without seeing the code you used for the request. The currencies work fine for me as long as there is data available for the specified timeframe. 

I would highly recommend following the code recipes provided for the API:
https://ib-insync.readthedocs.io/recipes.html
