### ISSUE TITLE
errorevent(). Sample code or tutorial

### ISSUE THREAD

**Issue by lamhoson** [erdewit/ib_insync#318]
Any sample code on how to use errorevent() in capture the error messages from IB ?

A bit confused after reading the document of these in "ib_insync - Release 0.9.61"

**Comment by erdewit** [comment]
This has been answered [here](https://groups.io/g/insync/message/5484).

**Comment by lamhoson** [comment]
My Python knowledge may be poor and sorry cannot understand it.

How the following work and passing parameters into the function call ExecutionErrors()?  Any reference book or else I should study first?

**_ib.errorEvent += ExecutionErrors_**


==============================================
def ExecutionErrors(reqId, errorCode, errorString, contract):
    print("In Error function")
    print(reqId, errorCode, errorString, contract)

ib = IB()
ib.errorEvent += ExecutionErrors
ib.connect('127.0.0.1', 7497, clientId=0)

**Comment by erdewit** [comment]
``+=`` is a synonym for the connect method for adding a callback to an event.

**Comment by lamhoson** [comment]
Thank you very much!

The syntax look very similar to the assignment operator, a +=1 (a = a +1) !!   Is this kind of syntax defined by the following library?

https://pypi.org/project/Events/

**Comment by erdewit** [comment]
The inplace-add is defined [here](https://github.com/erdewit/eventkit/blob/b7f424ed18a650d25fc3bd2b032280bdb4d42381/eventkit/event.py#L364) in the eventkit package. The syntax is inspired by DotNet.

**Comment by lamhoson** [comment]
Umderstand. Thank you very much !

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lamhoson** [comment]
Thank you very much!

Could I pass parameter into the inplace-add connect method ? The ‘logFileHandler’ in below:

    def errHandler(reqId, errorCode, errorString, contract):
        print(f" ErrorEvent Id:Code:Msg- {reqId}: {errorCode}: {errorString}: {contract}", file=logFileHandler)
        return

    ib.errorEvent += errHandler
================================================
