### ISSUE TITLE
RT Trade Volume

### ISSUE THREAD

**Issue by gsvijayraajaa** [erdewit/ib_insync#32]
Hi,

I would like to access RT Trade Volume from real time Ticker data . I couldn't find the field as a param in the code. So was wondering how to extract the same?

Regards,
Vijay Raajaa G S

**Comment by erdewit** [comment]
Can't you use ticker.volume?

**Comment by gsvijayraajaa** [comment]
As per the documentation;

Volume - Trading volume for the day for the selected contract (US Stocks: multiplier 100).
RT Trade Volume - Last trade details that excludes "Unreportable Trades"

I would like to know the traded volume at that moment. I hope volume gives a cummulative value over the day.

Please correct me if I am wrong.

**Comment by erdewit** [comment]
Yes, the ticker.volume should be cumulative.

I don't really understand the difference between the 'regular' volume and RTVolume. Both should be cumulative and updated snapshot wise. If you know of any difference please feel free to explain.

**Comment by erdewit** [comment]
Ticker.rtVolume has been added in v0.9.0.
