### ISSUE TITLE
API for day-end liquidation

### ISSUE THREAD

**Issue by lamhoson** [erdewit/ib_insync#320]
Any API for liquidation of all stocks on-hand before a trading day's end?

**Comment by hmate9** [comment]
No, there isn't a direct API for that. 

But you can just get your current positions: `ib.positions()`
Iterate over them and send a `MOC` order 15 minutes before trading closes.

If you want to see examples of how to see your current positions and send in orders see: https://nbviewer.jupyter.org/github/erdewit/ib_insync/blob/master/notebooks/ordering.ipynb

This issue should be closed.
