### ISSUE TITLE
consistently retrieving last price

### ISSUE THREAD

**Issue by satyan-g** [erdewit/ib_insync#321]
I see 'last' price cannot be retrieved after market close. I tried reqMktData(233), reqTickers() and even reqTickByTickData("AllLast"). I cannot use 'close' because it is close of the previous day and IB seems to be updating close way later as it waits for corp action processing. For instance, as of Saturday 4pm the close is still reflecting Thursday close.

Example contract: Contract(secType='CONTFUT', conId=383974339, symbol='ES', lastTradeDateOrContractMonth='20201218', multiplier='50', exchange='GLOBEX', currency='USD', localSymbol='ESZ0', tradingClass='ES')

I suppose I could use reqHistoricalTicks as a backup, but it seems weird that the most obvious field is not available with simple call. I suppose this is all on the IB side. Is there any straight forward way to fetch last price consistently at all times?

**Comment by satyan-g** [comment]
By extension, tkr.marketPrice() is also returning wrong value since it is using close from previous day.

**Comment by erdewit** [comment]
> I suppose this is all on the IB side.

Yes.
