### ISSUE TITLE
Unable to fetch data for metals

### ISSUE THREAD

**Issue by Shellcat-Zero** [erdewit/ib_insync#322]
I am so far unable to fetch data for metals, using the product listing located [here](https://www.interactivebrokers.com/en/index.php?f=2222&exch=idealpro_metals&showcategories=) for gold. There is sparse documentation on this, but I have tried:

```python
contract = Commodity('XAUUSD','IDEALPRO','USD')
```
and, 
```python
contract = Contract(conId=69067924,exchange='IDEALPRO')
```
along with,
```python
bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='30 D',
    barSizeSetting='1 hour', whatToShow='MIDPOINT', useRTH=True)
```
In either case, I receive an error stating that "No security definition has been found for the request".

Changing the exchange name to 'IDEALPRO Metals' gives me a `Invalid destination exchange` error. 

Please advise.

**Comment by erdewit** [comment]
It works for me with ``Commodity('XAUUSD', exchange='SMART)``.
