### ISSUE TITLE
Trailing stop order

### ISSUE THREAD

**Issue by lamhoson** [erdewit/ib_insync#324]
Seems that the current library does not support trailing stop order. If I would like to contribute to the code base instead, what should I do ?

Something like following:
![image](https://user-images.githubusercontent.com/34258914/103474319-b8e41a80-4ddd-11eb-9336-31c27e562b4e.png)

**Comment by erdewit** [comment]
For Trail orders it works exactly as in the IB documentation for the native ibapi.
