### ISSUE TITLE
ib.reqTickers problem :: Not able to get option chain data for any stock in NSE(National Stock Exchange, India)

### ISSUE THREAD

**Issue by jeherul** [erdewit/ib_insync#325]
I tried to get the option chain data for TATASTEEL listed in NSE. But when I execute ib.reqTickers(*contracts), it shows follwoing errors 
"Error 200, reqId 38: No security definition has been found for the request, contract: Option(conId=454836693, symbol='TATASTEEL', lastTradeDateOrContractMonth='20210128', strike=630.0, right='P', multiplier='1', exchange='SMART', currency='INR', localSymbol='TATASTEEL21JAN630PE', tradingClass='TATASTEEL')" 

![Screenshot from 2021-01-04 13-17-55](https://user-images.githubusercontent.com/59734548/103512721-4af82b80-4e8f-11eb-9f1f-88cbf79799db.png)
kinldy help.

**Comment by erdewit** [comment]
You can search the option in TWS to see what's wrong with it.
