### ISSUE TITLE
Flex Reports from custom time?

### ISSUE THREAD

**Issue by tankorsmash** [erdewit/ib_insync#326]
I'd like to be able to download a report from say, last quarter, rather than whatever the default is. I didn't see a mention of how to do it from [the ib_insync docs](https://ib-insync.readthedocs.io/api.html#ib_insync.flexreport.FlexReport), and the [code ](https://ib-insync.readthedocs.io/_modules/ib_insync/flexreport.html#FlexReport) seems to use some sort of non-public URL. I don't see anything about custom dates in the [FlexReportV3 docs](https://www.interactivebrokers.com/en/software/am/am/reports/flex_web_service_version_3.htm) either

It seems like IBKR supports some sort of customization, given that when you download the flex report for their site, it sends the custom timeframe via query:

    runOptions: {"queryId":"12345","queryType":"TCF","outputFormat":"XML","period":"LastQuarter","fromDate":"2021-01-04","toDate":"2021-01-04","noOfDays":1}

but appending `            f'&period=LastQuarter&fromDate=2021-01-04&toDate=2021-01-04&noOfDays=30
` to the download() url doesn't seem to change anything either.

Is it possible to somehow download a flex report with a custom period, rather than the default 1 day?

**Comment by tankorsmash** [comment]
Ah, this might be to do with Trade Confirmation Flex Reports being customizable on download, but Activity Reports don't have the hardcoded "Today" on the page.

**Comment by erdewit** [comment]
Feel free to ask IB about this.
