### ISSUE TITLE
reqHistoricalData not fetching correct data when datetime.datetime /w timezone is used

### ISSUE THREAD

**Issue by Peppershaker** [erdewit/ib_insync#329]
```
>>> dateTime
datetime.datetime(2021, 1, 4, 8, 51, tzinfo=tzoffset(None, -18000)) 
```

Note: -18000 is UTC -5, which is NY time. Expect data to be returned for 8:51 AM market time.

```
>>>contract = Stock('TSLA', 'SMART', 'USD')

>>>bars = ib.reqHistoricalData(contract, 
                                endDateTime=dateTime, 
                                durationStr='1800 S',
                                barSizeSetting='1 min', 
                                whatToShow='TRADES', 
                                useRTH=False,
                                formatDate=2)
```

```
>>>bars[-1]
BarData(date=datetime.datetime(2021, 1, 4, 15, 50, tzinfo=datetime.timezone.utc), open=736.58, high=737.77, low=736.35, close=737.27, volume=750, average=737.014, barCount=328)
```

That is, the data returned is 2021, 1, 4 10:50AM, not 8:50 AM as requested.

I suspect it has something to do with my local time, which is 2 hours behind NY time. 8:50 of my local time would be 10:50 NY time.

In fact, same data is returned if datetime obj is constructed without time zone, which makes me believe reqHistoricalData is ignoring the tzinfo object, or can't work with pytz.tzoffset
```
>>>dateTime = datetime.datetime(2021, 1, 4, 8, 51) 

>>>bars[-1]
BarData(date=datetime.datetime(2021, 1, 4, 15, 50, tzinfo=datetime.timezone.utc), open=736.58, high=737.77, low=736.35, close=737.27, volume=750, average=737.014, barCount=328)
```

strftime also gives same result
```
>>>dateTime = datetime.datetime(2021, 1, 4, 8, 51).strftime("%Y%m%d %H:%M:%S")

>>>bars[-1]
BarData(date=datetime.datetime(2021, 1, 4, 15, 50, tzinfo=datetime.timezone.utc), open=736.58, high=737.77, low=736.35, close=737.27, volume=750, average=737.014, barCount=328)
```

**Comment by Peppershaker** [comment]
restarted the machine and it seems like the error is gone. Not sure how to reproduce for now.

**Comment by erdewit** [comment]
Probably the local timezone differed from the TWS/gateway timezone (as set in the login window). There is no way for ib_insync to know the timezone that is set in TWS and it makes the assumption that is the local timezone.

**Comment by erdewit** [comment]
If forgot to mention that there is [IB.TimeZone](https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.TimezoneTWS) to set the TWS timezone explicitely.

**Comment by Peppershaker** [comment]
thank you very much! That make sense!
