### ISSUE TITLE
there is a exception if i use threading to concurrent

### ISSUE THREAD

**Issue by codcodog** [erdewit/ib_insync#33]
I use threading module on ib_insync, but it couldn't work, just throw a exception: RuntimeError, There is no current event loop in thread ‘Thread-1’. How do i use a concurrent on ib_insync?

**Comment by erdewit** [comment]
Create an event loop in the thread first:

```python
import asyncio
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
```

**Comment by codcodog** [comment]
I use this code in my thread function
```
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
```
but it couldn't work either. 
The python script is running but nothing output (no errors, no exceptions, and no print), just like in a loop but no ends.
And my code is [here](http://dpaste.com/3XZ296V). Maybe something wrong.
Anyway, thanks. 
Maybe i should try async program instead thread concurrent.

**Comment by erdewit** [comment]
Okay, the problem is that ib_insync is used in multiple threads. It should be used in it's own thread. The IB create and connect can be moved to get_codes_data and it will work fine.

> Maybe i should try async program instead thread concurrent.

This will save yourself a lot of trouble.

**Comment by MaanasPeri23** [comment]
> Create an event loop in the thread first:
> 
> ```python
> import asyncio
> loop = asyncio.new_event_loop()
> asyncio.set_event_loop(loop)
> ```

Wouldn't this just mean that we start a loop but never stops ending? I tried the same thing in my main but this wouldn't execute the functions below. I also referred the issue I'm having under the ib_insync Issues page where I go into detail the issues I'm having. Thanks!
