### ISSUE TITLE
reqHistoricalData incorrectly throws Error 200: No security definition when trading connection is lost

### ISSUE THREAD

**Issue by Peppershaker** [erdewit/ib_insync#330]
Seems like IB does nightly maintenance at around 2AM EST, which causes data connections to be lost. When this happens, reqHistoricalData can erroneously throw an error 200 when the ticker indeed does exist. Confirmed on my end today against 2 clients, 1 that has lost connection and 1 that has not.

[img](https://files.slack.com/files-pri/T017J9LTNS0-F01JSCM3YPN/image.png)

**Comment by erdewit** [comment]
What you see is what IB sends. If the data is returned empty then try again some other time.

**Comment by Peppershaker** [comment]
ty
