### ISSUE TITLE
infinite loop on Error 162

### ISSUE THREAD

**Issue by point049** [erdewit/ib_insync#331]
Trying to download the historical data, the ib_insync would go in an infinite loop and never stops.
It would be great if would break and move on.
As I run a loop on a list of contracts, so this infinite loop prevents makes the script stack and never moves on to try with the next contract on the list.

--- Test case to reproduce:
from ib_insync import *
import datetime
import os
import pandas as pd
from datetime import timedelta

inst = 'NG'
expiry = '20190926'
contract = Future(symbol='NG', lastTradeDateOrContractMonth='20190926', exchange='NYMEX', includeExpired=True)
datefrom = datetime.date(2014, 11, 27)

bars = ib.reqHistoricalData(contract,
                            endDateTime=datefrom,
                            durationStr='10 D',
                            barSizeSetting='1 day',
                            whatToShow='TRADES',
                            useRTH=True,
                            formatDate=1)

--- ib_insync version:'0.9.64'

**Comment by point049** [comment]
Trying to understand a bit further 
(disclaimer: I am not good with asyncio and event  driven dev at all, but trying to understand)

The errors seem to be managed here (util/run):
...
        def onError(_):
            task.cancel()

        globalErrorEvent.connect(onError)
        try:
            result = loop.run_until_complete(task)
        except asyncio.CancelledError as e:
            raise globalErrorEvent.value() or e
        finally:
            globalErrorEvent.disconnect(onError)
...

so if I understand it, there should be a disconnect after an error, but for some reason it doesn't happen
right?

**Comment by erdewit** [comment]
It's possible to set [IB.RequestTimeout](https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.RequestTimeout) to get a timeout exception.
