### ISSUE TITLE
Sometimes when using reqHistoricalData with keepUpToDate, data is missing for periods of time

### ISSUE THREAD

**Issue by Ughuuu** [erdewit/ib_insync#333]
Sometimes when using reqHistoricalData(especially when using it multiple times, like to collect data for multiple stocks), data is missing. In previous versions I would see an error message that subscription ended(and I assume the subscription was automatically restarted after some time, even though some data would be lost). Now, I don't get the error message anymore, but data is still lost.

I think the problem is not from ib_insync, however I am courious if anyone had this before. The problem might be from the client I am using, I am using TWS and will also try the new gateway API to see if it still happens.

If anyone has any idea why it is happening, I will be more than happy if you could point me in the right direction.

**Comment by Ughuuu** [comment]
This is how I'm using the api:

```
from ib_insync import *

def on5MinBarUpdate(bars, hasNewBar):
    print(bars)

symbols = ["TSLA","AAPL","ETSY","NVDA","PYPL"]
for symbol in symbols:
    bars5Min = self.ib.reqHistoricalData(
        contract,
        endDateTime='',
        durationStr='1 D',
        barSizeSetting='5 mins',
        whatToShow='TRADES',
        useRTH=True,
        formatDate=1,
        keepUpToDate=True)
    bars5Min.updateEvent += on5MinBarUpdate


self.ib.run()
```

**Comment by erdewit** [comment]
This is a known problem with keep-up-to-date bars subscriptions, in fact one of the notebooks explicitly warns about this.
