### ISSUE TITLE
NameError: name 'IB' is not defined

### ISSUE THREAD

**Issue by believeitcould** [erdewit/ib_insync#335]
I have installed ib_insync and I am using python3.6 on windows.
Code below

```
from ib_insync import *
# util.startLoop()  # uncomment this line when in a notebook

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)

contract = Forex('EURUSD')
bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='30 D',
    barSizeSetting='1 hour', whatToShow='MIDPOINT', useRTH=True)

# convert to pandas dataframe:
df = util.df(bars)
print(df)
```

```
Traceback (most recent call last):
  File "ib_insync.py", line 1, in <module>
    from ib_insync import *
  File "D:\TWS API\samples\Python\ib_insync.py", line 4, in <module>
    ib = IB()
NameError: name 'IB' is not defined
```

What is the problem?  Thanks!

**Comment by dragos-janea** [comment]
Can you make sure that you have done the Requirements step(From [github ](https://github.com/erdewit/ib_insync) page:

Requirements:

- Python 3.6 or higher;
- A running TWS or IB Gateway application (version 972 or higher). Make sure the API port is enabled and 'Download open orders on connection' is checked.

**Comment by erdewit** [comment]
>   File "ib_insync.py", line 1, in <module>

That's the problem right there. A local file should have a different name then any installed package.

**Comment by believeitcould** [comment]
My stupid!

**Comment by joecrawford1111** [comment]
Hi. I have the same error. I cannot see an installed package called IB? Please explain how to fix this in baby terms if you don't mind. Thanks.

**Comment by jlixfeld** [comment]
Rename your script something other than ib_insync.py

**Comment by evergreen2mdt** [comment]
Hi.  Brand new at this.  I got the same error.  I changed the name of the local file, and still received this error. 
 Any help would be great (in baby terms pls)

C:\Users\evergren\PycharmProjects\venv\Scripts\python.exe "C:\Users\evergreen\PycharmProjects\anotehr ib api.py" 
Traceback (most recent call last):
  File "C:\Users\evergreen\PycharmProjects\anotehr ib api.py", line 1, in <module>
    from ib_insync import *
  File "C:\Users\evergreen\PycharmProjects\ib_insync.py", line 4, in <module>
    ib = IB()
         ^^
NameError: name 'IB' is not defined

Process finished with exit code 1
