### ISSUE TITLE
Ib-insync takes longer time to load in Jupyter Notebook

### ISSUE THREAD

**Issue by Girish400** [erdewit/ib_insync#336]
Since last two days ib_insync is taking longer time to load (many times infinite time) and execute in Jupyter notebook

on Windows 10 Pro

I have tried disabling Antivirus, different browsers and a fresh windows 10 pro install, but the problem persists.

Not sure if this is a Jupyter notebook problem or something else. Same issue exists with Jupyter Notebook on VS code

C:\Users\user>jupyter troubleshoot
$PATH:
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\WINDOWS\System32\OpenSSH\
        C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\
        C:\Users\user\AppData\Local\Programs\Python\Python39\
        C:\Users\user\AppData\Local\Microsoft\WindowsApps

sys.path:
        C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\jupyter-troubleshoot.EXE
        c:\users\user\appdata\local\programs\python\python39\python39.zip
        c:\users\user\appdata\local\programs\python\python39\DLLs
        c:\users\user\appdata\local\programs\python\python39\lib
        c:\users\user\appdata\local\programs\python\python39
        c:\users\user\appdata\local\programs\python\python39\lib\site-packages
        c:\users\user\appdata\local\programs\python\python39\lib\site-packages\win32
        c:\users\user\appdata\local\programs\python\python39\lib\site-packages\win32\lib
        c:\users\user\appdata\local\programs\python\python39\lib\site-packages\Pythonwin

sys.executable:
        c:\users\user\appdata\local\programs\python\python39\python.exe

sys.version:
        3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.18362-SP0

where jupyter:
        C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\jupyter.exe

pip list:
        Package             Version
        ------------------- -------
        argon2-cffi         20.1.0
        async-generator     1.10
        attrs               20.3.0
        backcall            0.2.0
        bleach              3.3.0
        cffi                1.14.4
        colorama            0.4.4
        decorator           4.4.2
        defusedxml          0.6.0
        entrypoints         0.3
        eventkit            0.8.6
        ib-insync           0.9.64
        ipykernel           5.4.3
        ipython             7.20.0
        ipython-genutils    0.2.0
        ipywidgets          7.6.3
        jedi                0.18.0
        Jinja2              2.11.3
        jsonschema          3.2.0
        jupyter-client      6.1.11
        jupyter-core        4.7.1
        jupyterlab-pygments 0.1.2
        jupyterlab-widgets  1.0.0
        MarkupSafe          1.1.1
        mistune             0.8.4
        nbclient            0.5.1
        nbconvert           6.0.7
        nbformat            5.1.2
        nest-asyncio        1.5.1
        notebook            6.2.0
        numpy               1.20.0
        packaging           20.9
        pandas              1.2.1
        pandocfilters       1.4.3
        parso               0.8.1
        pickleshare         0.7.5
        pip                 21.0.1
        prometheus-client   0.9.0
        prompt-toolkit      3.0.14
        pycparser           2.20
        Pygments            2.7.4
        pyparsing           2.4.7
        pyrsistent          0.17.3
        python-dateutil     2.8.1
        pytz                2021.1
        pywin32             300
        pywinpty            0.5.7
        pyzmq               22.0.2
        Send2Trash          1.5.0
        setuptools          49.2.1
        six                 1.15.0
        terminado           0.9.2
        testpath            0.4.4
        tornado             6.1
        traitlets           5.0.5
        wcwidth             0.2.5
        webencodings        0.5.1
        widgetsnbextension  3.5.1

**Comment by Girish400** [comment]
Downgraded jupyter-client and few other modules and now everything is working as expected 

ipykernel==5.4.2
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.6.2
jedi==0.18.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.7.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0

**Comment by lgbongiolo** [comment]
Creating a python environment to use in VSCode and executing the notebook through the environment solved the issue for me.
