### ISSUE TITLE
KeyError when starting a new "reqTickByTickData"

### ISSUE THREAD

**Issue by milanster** [erdewit/ib_insync#337]
Error occurs once (and not every time) when starting a new tick by tick stream.
My code where it happens:
....
if tick_by_tick:
            ticker = self.ib.reqTickByTickData(contract=ibcontract, tickType="Last", numberOfTicks=1, ignoreSize=1)
            ticker.updateEvent += self._new_tick_by_tick
            self.tick_by_tick_contracts[symbol] = ibcontract
....

Error received:
`Error handling fields: ['98', '9', '0', '1']
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\lib\site-packages\ib_insync\decoder.py", line 190, in interpret
    handler(fields)
  File "c:\ProgramData\Anaconda3\lib\site-packages\ib_insync\decoder.py", line 739, in historicalTicksLast
    self.wrapper.historicalTicksLast(int(reqId), ticks, done)
  File "c:\ProgramData\Anaconda3\lib\site-packages\ib_insync\wrapper.py", line 571, in historicalTicksLast
    self._results[reqId] += ticks
KeyError: 9`

Using the debugger I can see that self._results is an empty dict right before the line that causes the error. (reqId 9 never existed in it as a key yet)

Versions:
ib-insync==0.9.64
ibapi==9.81.1.post1 (not sure if needed)
Python: 3.7.3

**Comment by erdewit** [comment]
Thank you for the bug report. The issue looks to be caused by an extraneous end-marker as sent by IB. I'll update the code to better deal with this.
