### ISSUE TITLE
Using util.startloop() in jupyter lab, have to restart kernel everytime

### ISSUE THREAD

**Issue by 9849842** [erdewit/ib_insync#339]
I am fetching historical data for the past 5 years. Everytime I finish and save the dataframe, I have to restart the kernel. Otherwise if I change th ticker to start pulling data for another ticker, I get the following error:

```
Peer closed connection
clientId 23 already in use?
API connection failed: TimeoutError()
```

Is there a way of stopping the loop? Or some way of avoiding having to restart the kernel for each data pull?

**Comment by erdewit** [comment]
> clientId 23 already in use?

This happens when TWS thinks there's still a client with that ``clientId`` connected.

**Comment by 9849842** [comment]
So how do I fix it? IB.Disconnect() doesn't work to solve this issue.
