### ISSUE TITLE
Does not detect newest version of ibapi

### ISSUE THREAD

**Issue by drSeeS** [erdewit/ib_insync#34]
When cloning the repo and doing 'python setup.py install' (on Windows, no pip) I get:
"Old version of ibapi module detected. The newest version from http://interactivebrokers.github.io is required". 
I have installed ibapi version 9.73.06 (as verified in API_VersionNum.txt), the docs say required is 'only' 9.73.03 
Thanks for this beautiful package!

**Comment by erdewit** [comment]
There must still really be an old ibapi installed for that python version. Check with

```python
import ibapi
print(ibapi.__version__)
```
