### ISSUE TITLE
Bulk Historical Data (for Multiple Contracts)?

### ISSUE THREAD

**Issue by windowshopr** [erdewit/ib_insync#345]
Trying to figure out an efficient way to keep multiple contracts up to date using the `reqHistoricalData` function with `keepUpToDate=True`.

What I have so far looks like this, but not sure if it's the BEST way to be doing it or not?:

```
from ib_insync import *
from IPython.display import display, clear_output
import matplotlib.pyplot as plt
util.startLoop()

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=1)

%matplotlib inline # For notebook

contracts = [Forex(pair) for pair in ('EURUSD', 'USDJPY', 'GBPUSD', 'USDCHF', 'USDCAD', 'AUDUSD')]
ib.qualifyContracts(*contracts)

def onBarUpdate(bars, hasNewBar):
    plt.close()
    plot = util.barplot(bars)
    clear_output(wait=True)
    df = util.df(bars)
    display(df.tail())
    display(plot)

for contract in contracts:
    bars = ib.reqHistoricalData(
        contract, endDateTime='', durationStr='600 S', #'1 D',
        barSizeSetting='1 min', whatToShow='MIDPOINT', useRTH=False, keepUpToDate=True)
    bars.updateEvent += onBarUpdate
```

So this does work, but it'll just keep updating forever, or until an `ib.disconnect()` is run. What's the best way to only let this run for say, 2 minutes, updating all contracts therein, before running `ib.cancelHistoricalData(bars)` on each contract to stop the pulling of data?? Thanks!

**Comment by erdewit** [comment]
A simple way is ``ib.sleep(120)`` before canceling the subscriptions.
