### ISSUE TITLE
ib.openTrades() inconsistency

### ISSUE THREAD

**Issue by fmellomascarenhas** [erdewit/ib_insync#346]
Hi, I am not sure if it is a bug. 

If I:
1) place an order and don't transmit it;
2) go to the client and discard them;
3) run ib.openTrades()

I can still see the order with status: 'PendingSubmit'. If I reset connections, then ib.openTrader() is empty.

```
from ib_insync import *
import nest_asyncio
nest_asyncio.apply()
util.startLoop()

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=14)

def myBracketOrder(
            action: str, quantity: float,
            limitPrice: float, trailling_pct: float, **kwargs) -> BracketOrder:

    assert action in ('BUY', 'SELL')
    reverseAction = 'BUY' if action == 'SELL' else 'SELL'
    
    parent = LimitOrder(
        action, quantity, limitPrice,
        orderId=ib.client.getReqId(),
        transmit=False,
        **kwargs)
    
    trail = Order(action = reverseAction,
                  totalQuantity = quantity,
                  orderType = "TRAIL",
                  trailingPercent = trailling_pct,
                  orderId=ib.client.getReqId(),
                  parentId=parent.orderId,
                  transmit=False,
                  **kwargs
                 )

    return [parent, trail]

order = myBracketOrder(action = 'BUY',
                        quantity = 10,
                        limitPrice = 200,
                        trailling_pct = 2)

contract = Stock('GME', 'SMART', 'USD')

for o in order:
    ib.placeOrder(contract, o)

ib.openTrades()
```

In my case, I don't want to use regular bracketorder, because I want to set a trailing stop as the child. Could you please advise about how to transmit the orders after creating them and also how to cancel them using the API? I saw that there are Events [here](https://ib-insync.readthedocs.io/api.html), but I couldn't find an example in the docs. Thanks in advance!!

**Comment by erdewit** [comment]
The last of the child orders to be placed must have ``transmit=True``; This will trigger the other orders in the bracket to be transmitted as well. It is a fail-safe to prevent the parent order from being executed while the child orders are not active yet.
