### ISSUE TITLE
Pass in Attributes to the onBarUpdate() Callback Function Possible?

### ISSUE THREAD

**Issue by windowshopr** [erdewit/ib_insync#353]
Is it possible to pass in features/variables to the onBarUpdate callback? I'm wanting to pass in the contract object to it so I can parse the contract's symbol from it. What I have so far looks like this:

```
contracts = [Forex(pair) for pair in ('EURUSD', 'USDJPY', 'GBPUSD', 'USDCHF', 'USDCAD')]
ib.qualifyContracts(*contracts)

def onBarUpdate(bars, hasNewBar):
            
        df = util.df(bars)
        df.to_csv("datasets/" + todays_date + "/" + TICKER/CONTRACT_HERE + ".csv", index=True)


for contract in contracts:
    bars = ib.reqHistoricalData(contract, endDateTime='', durationStr='3 D', barSizeSetting='5 mins', whatToShow='MIDPOINT', useRTH=False, keepUpToDate=True)
    bars.updateEvent += onBarUpdate
```

..and what I envision I'm after would look something like:

```
def onBarUpdate(bars, hasNewBar, contract):
....
bars.updateEvent += onBarUpdate(contract)
```

...however I'm having issues troubleshooting this to get it working. As I'm sure can be guessed, I'd like to replace the "TICKER/CONTRACT_HERE" with something like "contract.symbol" so I could save the .csv file with the ticker for the corresponding bars contract in the filename. I'm just getting used to async callback functions as well so not sure the correct syntax. Any help would be greatly appreciated! Thanks!

**Comment by windowshopr** [comment]
I guess to reframe my original question, what I'm after is a way of saving the dataframe, who's ticker the current bars belong to. Because I'm working with multiple contracts, I would like a way of knowing which ticker the current bars belong to, so that when I use the .to_csv to update each respective csv file, it's saving it with the symbol in the name of the file, so maybe my first course of action isn't the best option.

Is there a way to get the symbol from the BarData, some other way of getting the symbol from within the onBarUpdate function? Thanks!

**Comment by rundef** [comment]
You can use [partial from functools](https://www.blog.pythonlibrary.org/2016/02/11/python-partials/)

```
from functools import partial

bars.updateEvent += partial(onBarUpdate, contract)

def onBarUpdate(contract, bars, hasNewBar):
....
```

**Comment by windowshopr** [comment]
@rundef I sure can! Works perfectly, thanks for the tip!

**Comment by erdewit** [comment]
It's easier to use ``bars.contract``

**Comment by windowshopr** [comment]
That works perfect too. When I printed the "bars" objects out, I must have missed the "contract" attribute, but this makes it much easier. Thanks for the input!
