### ISSUE TITLE
reqAllOpenOrder

### ISSUE THREAD

**Issue by mr-lanholmes** [erdewit/ib_insync#356]
Hi helpful project!

I am trying to use the API for reqAllOpenOrder, however it return empty list. It does print the all the open orders in debug terminal. 

Read through the documentation but couldnt find something relate to returning value to variable. 

Hope anyone can help with this.

Have a good day ahead!

**Comment by mr-lanholmes** [comment]
self.wrapper.trades.values() returns dict_values([])

Anyone can advise on this? Thanks

**Comment by erdewit** [comment]
It works for me. If TWS is in read-only mode then the request may fail.
