### ISSUE TITLE
How to get account balance in ib_insync?

### ISSUE THREAD

**Issue by MattKarel** [erdewit/ib_insync#358]
Hi. When I try to get account balance using:

acc_vals = [v for v in ib.accountValues() if v.tag == 'CashBalance' and v.currency == 'USD']

I get a single-item list as output:

[AccountValue(account='DU3674319', tag='CashBalance', value='1001402.98', currency='USD', modelCode='')]

I would like to extract the actual account cash balance (value='1001402.98') from this list into a variable, so that I could calculate position size based on this information.

Is it somehow possible to do this? From the above mentioned single-item list it does not seem possible.

**Comment by RGLDN** [comment]
Use dot notation on the variable v for the attribute of interest (and then pass it to a float so it can be utilised for calculations).

For example: 

acc_vals = float([v.value for v in ib.accountValues() if v.tag == 'CashBalance' and v.currency == 'USD'])

**Comment by MattKarel** [comment]
Hi RGLDN,

I tested that, but I get the following error message:

TypeError: float() argument must be a string or a number, not 'list'

But without float() it seem to work though.

Thanks a lot RGLDN!

**Comment by RGLDN** [comment]
Sorry, I missed the zero index at the end. 

Try:

acc_vals = float([v.value for v in ib.accountValues() if v.tag == 'CashBalance' and v.currency == 'USD'][0])

**Comment by MattKarel** [comment]
Hi RGLDN,
Works perfectly, thanks again!
