### ISSUE TITLE
ib.trades() returns empty list

### ISSUE THREAD

**Issue by Kuromory** [erdewit/ib_insync#365]
I try to get all trades and orders from IB to log my trades.

So I tried with this code to get all trades and orders but both gives me an empty list fill works but there is not everything I need.

I even deselected read only in the IB software. Here is my code:

ib = IB()
ib.connect('127.0.0.1', 7496, 0)
fills = ib.fills() # works
trades = ib.trades() # does not work
orders = ib.orders() # does not work

**Comment by erdewit** [comment]
A recent version of TWS is required to fetch the completed orders.

**Comment by Kuromory** [comment]
TWS autoupdates as far as I konew but my version is: Build 983.2l that was updated the 5th of May.
I also added a picture of my settings in TWS

I hope you can help me out with ib.trades()  :)

![image_2021-05-07_232822](https://user-images.githubusercontent.com/38322904/117510182-e7d8eb80-af8b-11eb-9bcc-b59aa18ccc3b.png)
