### ISSUE TITLE
Failing to cancel orders starting from the second cancelling call at Windows 7/10

### ISSUE THREAD

**Issue by guangyu-shi** [erdewit/ib_insync#368]
I can cancel all the pending orders for the the first time; then after placing second batch orders, it starts to fail to cancel all the pending orders w/ only one order cancelled; then after 3rd batch placed, the second cancelled orders actually got removed w/ only one from  3rd batch orders cancelled per TWS reporting.

I use ib.placeOrder(contract, order) to place orders, use ib.cancelOrder( order) to cancel Orders, use ib.openOrders() to get open Orders; it does show trade.orderStatus.status ='Cancelled' after calling ib.cancelOrder( order); and the following ib.openOrders() shows no  open Orders after  cancelling call. 

This is reproducible on Windows 7/10; but linux host works well for the same code. So my workaround is placing a new order to trigger the previous cancelling call. But I'm looking forward to fixing the root cause.

This happens for version 0.9.61,  0.9.64,  0.9.66.

Pls advise.

Bliss.
--gs

**Comment by erdewit** [comment]
There's not much to make from this.
