### ISSUE TITLE
Disconnect not called anymore in Python 3.8 upon task cancellation

### ISSUE THREAD

**Issue by dmoklaf** [erdewit/ib_insync#370]
Starting with Python 3.8, asyncio.CancelledError has been promoted from being a regular Exception to becoming a "special" BaseException.

This key change allows for simpler and more robust interruption of asynchronous tasks, by separating them from "regular" exceptions that are often catched by end users through try...except Exception blocks.

However this also brings a side effect: the "special" BaseException class is not infrequent anymore and could be triggered quite often in fact, e.g. due to client-code timeout cancellations or cancellations required by the end-user through a UI.

Consequently the cleanup code here needs to be enlarged to be triggered by BaseExceptions and not only Exceptions:

https://github.com/erdewit/ib_insync/blob/006fcfc19bb7578e267096e61ae74fae6aff90e1/ib_insync/ib.py#L1667

**Comment by dmoklaf** [comment]
As a side note, I scanned quickly the eventkit and ib_insync projects (not distex that I am not using yet, kudos for the good work) for this bug and found only this line. However I am not expert there and maybe a deeper look could find one.

**Comment by erdewit** [comment]
That is a good point. This is fixed by explicitly catching ``asyncio.CancelledError``.

**Comment by dmoklaf** [comment]
The commit above seems to work fine - the test pipeline failed specifically for Python 3.6 (other versions were fine) due to the ib_insync evolution toward modern Python features unavailable in 3.6 - the failure has no relationship to the commit changes - consequently it shall be released
