### ISSUE TITLE
No module named pandas

### ISSUE THREAD

**Issue by emil45** [erdewit/ib_insync#373]
Install successfully the package,
When I run the first script in the "introduction" section, I got this error:

```
Traceback (most recent call last):
  File ".../ib-api/main.py", line 14, in <module>
    df = util.df(bars)
  File ".../ib_insync/util.py", line 32, in df
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

Python 3.8.7
Poetry

**Comment by RGLDN** [comment]
Looks like you don't have pandas installed.  See https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html

**Comment by erdewit** [comment]
Pandas is a soft dependency, it's required when using ``util.df()``.
