### ISSUE TITLE
Wrong type annotation for mypy

### ISSUE THREAD

**Issue by dmoklaf** [erdewit/ib_insync#374]
The` IB.reqMarketRuleAsync` method has a return type currently annotated as `Optional[PriceIncrement]`:

https://github.com/erdewit/ib_insync/blob/006fcfc19bb7578e267096e61ae74fae6aff90e1/ib_insync/ib.py#L1822

However runtime usage indicates the correct type is `List[PriceIncrement]` (maybe Optional[...], that I don't know).

This mismatch creates false alerts when running mypy over client API code.

**Comment by erdewit** [comment]
Thanks for the bug report, this has been fixed in the repo.
