### ISSUE TITLE
Rapid disconnection and reconnection to gateway creates clientId conflicts

### ISSUE THREAD

**Issue by dmoklaf** [erdewit/ib_insync#376]
When disconnecting and reconnecting very quickly to the gateway (i.e., without pauses), the IB gateway rejects the reconnection stating the the clientId (0 in this case) is already used.

Upon inspection of the code, it seems to come from the `IB.disconnect` which is a synchronous method but does not close synchronously the socket. Deep into the code it ends up calling the `Connection.disconnect` method, which calls the underlying asyncio socket `disconnect` method which, as the asyncio documentation states, does not synchronously close the connection. This asyncio method creates a hidden task that will asynchronously (i.e., sometime in the future but we can't guarantee when) flush the connection write buffer and only once it is flushed close it. Once it's done, the asyncio machinery will call the Protocol callback method, in our case the `Connection.connection_lost`method, with a None argument, to notify that the requested close is effective. This is an asyncio peculiarity, as most synchronous asyncio method do guarantee immediate effectiveness but here it is not guaranteed.

One clean solution could thus be to
(1) add an `IB.disconnectAsync`method which as today calls the deeper `disconnect` methods and then awaits the effective `Connection.disconnect` event (that is already triggered by the callback method)
(2) replace the`IB.disconnect` method code with simply an `asyncio.run` call to the previous asynchronous method

This way, both async and sync API users would get a guarantee that the connection is closed upon calling their favorite method.

**Comment by erdewit** [comment]
This issue should be fixed in v0.9.66. The relevant part is here: https://github.com/erdewit/ib_insync/blob/6f19e9d3d0e31ad43ef0a1bdafdb72849d4de8c6/ib_insync/connection.py#L32

But there is also the other side of the connection: TWS/gateway may not realize that the connection is closed when a new one comes in so fast. Best thing is to not do an immediate reconnect (what is the point?) but to stay connected, or at least add a small delay between reconnects.

**Comment by dmoklaf** [comment]
Ah yes the asynchronous TWS/gateway processing is a good point. Indeed the gateway might still think the connection is there. A small delay would help indeed. I will add a try/catch around my client connection block and, in case of clientId error, pause a little and retry
