### ISSUE TITLE
ib.openTrades() does not reflect uptoDate status

### ISSUE THREAD

**Issue by rajeshon21** [erdewit/ib_insync#377]
I have seen that after placing Bracket Orders ( which get instantly filled), if I call ib.openTrades() - it does not correctly reflect the status of the openTrades - It will still reflect the parent trade as not filled. For now, I have worked around by using the filledEvent to keep track of the open and filled statuses myself.

**Comment by erdewit** [comment]
When an order gets filled, it is by definition not an open order anymore. So it will not be available from ``ib.openTrades()`` anymore, but still is available from ``ib.trades()``.
