### ISSUE TITLE
 ib_insync.ibcontroller.IBC [Error: Could not find or load main class ibcalpha.ibc.IbcTws]

### ISSUE THREAD

**Issue by justingoheen** [erdewit/ib_insync#379]
I receive the following error when running the below shown script (modified, basic example from the docs).

```
Error: Could not find or load main class ibcalpha.ibc.IbcTws
```

I read your closed issue at https://github.com/IbcAlpha/IBC/issues/1; and am submitting here given I am using ib_insync and not IBC directly.

OS: MacOS BigSur 11.4
TWS/Gateway version: 978
ib_insync version: 0.9.66
IBC version: 3.8.6
Python Version: 3.7.10; and 3.9.4

```
import ib_insync
import os

os.chdir(os.path.expanduser("~"))

ibc = ib_insync.ibcontroller.IBC(
    978, 
    gateway=False, 
    tradingMode='live', 
    userid='my_user_id_string', 
    password='my_password_string', 
    ibcPath='opt/ibc', 
    ibcIni='opt/ibc/config.ini')

ibc.start()

ib_insync.IB.run()
```

**Comment by justingoheen** [comment]
I read in IBC that the offline version of TWS is required. I uninstalled TWS 978 and installed the latest offline version, TWS 984. This did not fix the error.

**Comment by erdewit** [comment]
IBC is a different project.

**Comment by justingoheen** [comment]
I understand IBC is a different project; the error arises when I use ib_insync.ibcontroller.IBC - so isn't this an ib_insync issue also?

**Comment by erdewit** [comment]
What you're getting is a Java error so that looks like IBC alpha is not installed right.
