### ISSUE TITLE
AttributeError: 'BracketOrder' object has no attribute 'orderId'

### ISSUE THREAD

**Issue by CollierKing** [erdewit/ib_insync#38]
Thank you for the great work on this package. 
Most order types seem to work fine but having some trouble submitting a new bracket order.

Do you have a working example for bracket orders or a workaround?

```
ticker = 'AAPL'
contract = Stock(ticker, 'SMART', 'USD')
ib.qualifyContracts(contract)
bracketOrder = ib.bracketOrder("BUY", 75,120,140,100)
bracketTrade = ib.placeOrder(contract, bracketOrder)
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-385-bad7c3c41b45> in <module>()
      3 ib.qualifyContracts(contract)
      4 bracketOrder = ib.bracketOrder("BUY", 75,120,140,100)
----> 5 bracketTrade = ib.placeOrder(contract, bracketOrder)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ib_insync/ib.py in placeOrder(self, contract, order)
    517         status changes, fills, etc.
    518         """
--> 519         orderId = order.orderId or self.client.getReqId()
    520         self.client.placeOrder(orderId, contract, order)
    521         now = datetime.datetime.now(datetime.timezone.utc)

AttributeError: 'BracketOrder' object has no attribute 'orderId'

Thank you!

**Comment by erdewit** [comment]
The three orders inside the bracket need to be placed individually, as described [here](http://rawgit.com/erdewit/ib_insync/master/docs/html/api.html#ib_insync.ib.IB.bracketOrder).

**Comment by rpateld** [comment]
Just do
```
contract = Stock('QQQ','SMART','USD')
bracket = ib.bracketOrder('BUY', 1, 311, 312, 309)

for o in bracket:
    trade = ib.placeOrder(contract,o)
    print(trade)
```
