### ISSUE TITLE
Changes: "How are bid, ask, and last size quotes displayed for stocks?"

### ISSUE THREAD

**Issue by JSunRae** [erdewit/ib_insync#382]
Did anyone else get this message today? I'm not entirely 100% sure what has changed.

![image](https://user-images.githubusercontent.com/61567145/122023285-4d0bd200-cdbf-11eb-85dc-8437199d3647.png)

Does this mean all reqHistoricalData, data feed subscriptions and order entry commands were previously in lots of 100. And now they must all be either given or will be returned in actual shares. So previously shares might have been shown as 100, and now it will be shown as 10,000?

"Effective in TWS version 985 and later, for US stocks the bid, ask, and last size quotes are shown in shares (not in lots). API users have the option to configure the TWS API to work in compatibility mode for older programs, but we recommend migrating to "quotes in shares" at your earliest convenience. To use compatibility mode, from the Global Configuration menu select API followed by the Settings page. Once there, check "Bypass US Stocks market data in shares warning for API orders.""

**Comment by eekremer** [comment]
Hi Chuck,
I actually have TWS 985.1, so I am experiencing some problems with data...
Please explain a little further about your recommendation of migrating to "quotes in shares"

**Comment by erdewit** [comment]
> So previously shares might have been shown as 100, and now it will be shown as 10,000?

Yes. No need to factor in the lot size anymore.
