### ISSUE TITLE
Empty Ticker.ticks

### ISSUE THREAD

**Issue by dmitriiweb** [erdewit/ib_insync#383]
Hello, I have the following function:

```
def get_underlying_price(
    symbol: str, ib: IB, currency: str, position: ib_insync.PortfolioItem
) -> float:
    contract = get_contract(symbol, position)
    print(f"{contract=}")
    ib.reqMktData(contract, "", False, False)
    ticker = ib.ticker(contract)
    ib.sleep(5)
    print(f"{ticker=}")
    print(f"{ticker.marketPrice()=}")
    print(ticker.ticks)
    ib.cancelMktData(contract)
```
And an output always this:
```
contract=Stock(symbol='AAPL', exchange='SMART', currency='USD')
ticker=Ticker(contract=Stock(symbol='AAPL', exchange='SMART', currency='USD'))
ticker.marketPrice()=nan
[]
```

So, I always get an empty list in `ticker.ticks`, but I can get data using 'BidAsk' and `last`

Please help,
Thank you.

**Comment by erdewit** [comment]
The ``ticker.ticks`` list is filled after tick data is received and is then cleared. Sampling it at a random time will find it emtpy most of the time.

How to use it in a proper event-driven fashion is described in the [Tick data notebook](https://nbviewer.jupyter.org/github/erdewit/ib_insync/blob/master/notebooks/tick_data.ipynb).
