### ISSUE TITLE
possible documentation error with updateEvent

### ISSUE THREAD

**Issue by luke-1993** [erdewit/ib_insync#387]
First thanks for developing this library. It has proved very useful.
The API documentation (https://ib-insync.readthedocs.io/api.html) states the following:

```
updateEvent (): Is emitted after a network packet has been handeled.

barUpdateEvent (bars: BarDataList, hasNewBar: bool): Emits the bar list that has been updated in real time. If a new bar has been added then hasNewBar is True, when the last bar has changed it is False.
```

However, in the code the BarDataList class only has an updateEvent attribute meaning that it's not possible to attach a barUpdateEvent to such an object.

It seems that the updateEvent is overloaded depending on the data type it is attached to. This is slightly confusing at first because it conflicts with the above documentation. Furthermore, the updateEvent when overloaded on a specific data type can actually take arguments, further contradicting with the documentation.

It seems the intention is to attach an updateEvent callback to a specific instance of a data type but if a generic behaviour is desired over all instances of such events then a callback can be attached to the instance of ib and the type of event the callback should be triggered by. For example:

```
        bars = self.ib.reqHistoricalData()
        # either of the below would work in triggering self.on_new_bar() when a barUpdateEvent occurs
        self.ib.barUpdateEvent += self.on_new_bar
        bars.updateEvent += self.on_new_bar
```

It's not obvious from the documentation which paradigm should be used and why.

**Comment by erdewit** [comment]
``IB.barUpdateEvent`` fires for any bar update, ``BarList.updateEvent`` only for that specific bar list.

``IB.updateEvent`` is fired after anything new arrived.
