### ISSUE TITLE
reqPnlSingle returning ridiculously high value for realizedPnL

### ISSUE THREAD

**Issue by Aaimek** [erdewit/ib_insync#388]
Hi,

So I am retrieving pnls for a signle contracts this way:
`pnls = ib.reqPnLSingle(<my account number>, '', <my contract's id>)`
When I look and the returned object, everything seems to be fine, values look normal, except for `realizedPnL`:
`realizedPnL=1.7976931348623157e+308`

Sadly this isn't the actual profit I've made trading this contract...
I haven't found anything looking like this issue on TWS's basic api, that's why I am posting an issue here.

Thanks for this tool.

**Comment by Aaimek** [comment]
I just saw that this is the max value allowed by default for a `float` in Python, this can maybe help

**Comment by markmark1** [comment]
yes i see this error as well, is there  a fix?

**Comment by erdewit** [comment]
The default value for ``realizedPnL`` is ``nan``. If it gets set to ``FLOAT_MAX``, this is done by IBKR to denote that they do not have a valid value.

**Comment by Aaimek** [comment]
Okay thanks for the help, I'll just wait until a normal value pops up. Thanks!
