### ISSUE TITLE
Error code triggering a trade cancellation is not accessible through trade object

### ISSUE THREAD

**Issue by dmoklaf** [erdewit/ib_insync#389]
Various IB trade errors (eg error 412 - the contract is not available for trading) are properly converted by the ib_insync framework into state changes in the Trade object and its various sub-objects (e.g., TradeLogEntry). However only the error message is tracked in these objects (a string) and not the error code itself. This makes proper error management (for example to decide whether to abandon a trade, report it to the user, trigger a user workflow, etc...) brittle as it forces the client code to parse strings that IB and/or ib_insync (which wraps the IB string into a higher level string with various ids as text) could change at any time.

A workaround for the client code is to separately track API errors, and correlate these errors with the trade errors by using custom data structures to "remember" which goes where. However this makes the code brittle too (unnecessary and assumes errors are posted as events in a specific order by ib_insync, which is not guaranteed either).

A clean solution would be to store error IDs alongside the error message string into the trade-related objects.

**Comment by erdewit** [comment]
The ``errorCode`` is now captured and will be available from one of the ``TradeLogEntry`` (generally the last one).

**Comment by dmoklaf** [comment]
Outstanding, thanks and have a great day!
