### ISSUE TITLE
Possible bug in historical bar ?

### ISSUE THREAD

**Issue by gengjun** [erdewit/ib_insync#391]
Today I noticed something wrong when requesting historical bar data with keepUpToDate=True. The latest bar keep gettting wrong value (around 4511) while the correct price is around 4480 for Sep ES fufure. the request i use is:

`es = ibi.Future('ES', '20210917', 'GLOBEX')
 ib_insync.reqHistoricalData(                                                                                                                                                                      
    es,                                                                                                                                                                                             
    durationStr='50 S',                                                                                                                                                                               
    barSizeSetting='5 secs',                                                                                                                                                                        
    useRTH=False,                                                                                                                                                                                 
    whatToShow='MIDPOINT',                                                                                                                                                                         
    keepUpToDate=True)
`
I print bars in onBarUpdate event, noticing the last bar keep getting wrong value (it was around 4511 2 hours ago) and getting corrected:

[..., BarData(date=datetime.datetime(2021, 9, 10, 10, 40, 45), open=4480.375, high=4480.625, low=4479.875, close=4479.875, volume=-1, average=-1.0, barCount=-1), BarData(date=datetime.datetime(**2021, 9, 10, 10, 40, 50**), open=4511.375, high=4511.375, low=4511.375, close=**4511.375**, volume=-1, average=-1.0, barCount=-1)]

in the next onBarUpdate, last price was corrected:
[..., BarData(date=datetime.datetime(2021, 9, 10, 10, 40, 40), open=4480.375, high=4480.625, low=4480.125, close=4480.375, volume=-1, average=-1.0, barCount=-1), BarData(date=datetime.datetime(2021, 9, 10, 10, 40, 45), open=4480.375, high=4480.625, low=4479.875, close=4479.875, volume=-1, average=-1.0, barCount=-1), BarData(date=datetime.datetime(**2021, 9, 10, 10, 40, 50**), open=4479.875, high=4480.125, low=4479.625, close=**4479.875**, volume=-1, average=-1.0, barCount=-1)]

it was wrong again in the nex onBarUpdate call:
[..., BarData(date=datetime.datetime(2021, 9, 10, 10, 40, 45), open=4480.375, high=4480.625, low=4479.875, close=4479.875, volu
me=-1, average=-1.0, barCount=-1), BarData(date=datetime.datetime(2021, 9, 10, 10, 40, 50), open=4479.875, high=4480.125, low=4479.625, close=4479.875, volume=-1, average=-1.0, barCount=-1), BarD
ata(date=datetime.datetime(**2021, 9, 10, 10, 40, 55**), open=4511.375, high=4511.375, low=4511.375, close=**4511.375**, volume=-1, average=-1.0, barCount=-1)]

I checked charts on IB, it seems fine. I wonder if this is a bug from ib_insync ?

**Comment by gengjun** [comment]
this is due to delayed (real time) market data, the historical bar is not delayed.

**Comment by zdytch** [comment]
@gengjun could you please explain more detailed? 

I get the same issue with very first bar of every new period. 
E.g. if I have `barSizeSetting='5 mins'` I get that buggy bar when new 5-min period starts
After that all other bars are good, until the next 5-min period starts
It seems to happen when `hasNewBar == True`

**Comment by erdewit** [comment]
> It seems to happen when hasNewBar == True

The latest bar is still forming. A new bar only has a definite open price, since one can't look into the future what the whole bar will be.

**Comment by zdytch** [comment]
@erdewit that's reasonable, thank you!

fair to notice, open prices of new bars are invalid as well, maybe there's a bug indeed?
my current workaround is to ignore bar if `hasNewBar == True`, that works for me
