### ISSUE TITLE
"Error handling fields" on option tick 

### ISSUE THREAD

**Issue by andrew20190** [erdewit/ib_insync#393]
This is unfortunately an intermittent bug, so I will work more to isolate exactly what is happening to narrow down this report a bit and update in a comment if I become any smarter (though that is unlikely...)

Here's the traceback:

```
    Error handling fields: ['21', '6', '52', '11', '0.12502290549746', '', '', '\x0c2', '6', '39', '3', '20', '', '', '', '\x0b2', '6', '39', '0', '2', '', '', '', '\x0c2', '6', '39', '3', '13', '', '', '', '\x0b2', '6', '39', '0', '5', '', '', '', '\x0c2', '6', '39', '3', '20', '', '', '', '\x1646', '6', '39', '45', '1631702490', '', '', '', '\x0f2']
    Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/ib_insync/decoder.py", line 191, in interpret
        handler(fields)
    File "/usr/local/lib/python3.9/site-packages/ib_insync/decoder.py", line 481, in tickOptionComputation
        _, _, reqId, tickTypeInt, impliedVol, delta, optPrice, \
    ValueError: too many values to unpack (expected 12)
```

TWS version 10.10.21 (September 9th) on Linux (Debian 11, on x64).

`ib_insync.__version__`, installed via pip, reports '0.9.66'.

Python v 3.9.7 from Debian's apt. 

I suspect this may be because some extra option Greek is being transmitted that wasn't previously.

**Comment by erdewit** [comment]
It looks like IBKR is sending malformed data. This must be a regression in the new TWS.
