### ISSUE TITLE
ib_insync.flexreport.FlexReport fails due to non-existent host gdcdyn.interactivebrokers.com

### ISSUE THREAD

**Issue by papakipos** [erdewit/ib_insync#394]
A new error just appeared today. 

I'm making a call to ib_insync.flexreport.FlexReport. I get the error: 
> socket.gaierror: [Errno 8] nodename nor servname provided, or not known

I can see in flexreport.py:download() that the hostname gdcdyn.interactivebrokers.com is used in the code.

It looks like ibkr got rid of the host gdcdyn.interactivebrokers.com.
ping gdcdyn.interactivebrokers.com gets "Unknown host".
This code probably just needs a corrected hostname in order to work again.

**Comment by papakipos** [comment]
I find the ability to download Flex reports very useful. I would hate to see it disappear. Are you seeing indication that IBKR is discontinuing supporting it? I just logged into my account and I still see all the info about Flex reports. It seems to still be supported from what I can tell. Is there are URL you can share?

**Comment by erdewit** [comment]
Thank you very much for your donation! And glad that the issue was just temporary - the FlexReport is left as-is then.
