### ISSUE TITLE
Attributes not found in the Ticker Object

### ISSUE THREAD

**Issue by bb10128** [erdewit/ib_insync#396]
Mimicking the "Dividends" example as shown in https://ib-insync.readthedocs.io/recipes.html#dividends,
I have the following code to get some auction-related data.  The dividends results are OK.  But the last line lead to err msg  -->  AttributeError: 'Ticker' object has no attribute 'auctionPrice'.

The expected should have been:
1) no error message at all times, 
2) with data for such attributes during the periods when imbalance messages are sent, 
3) without data otherwise.

Am I doing something wrong? Thanks for looking into this.

------- Code ----------

contract = Stock('C', 'NYSE', 'USD')
ticker = ib.reqMktData(contract, '225,456')
ib.sleep(4)
print(ticker.dividends)
print(ticker.auctionPrice)

----------------------------

**Comment by erdewit** [comment]
``Ticker`` most certainly has an ``auctionPrice`` field, and the code works for me. Can you post the full stack trace?

**Comment by bb10128** [comment]
My ib_insync was on version 0.9.56.  Once I upgraded (to 0.9.66), everything indeed worked fine.  Sorry that I overlooked the most obvious.

I am sure you have heard this too many times --- but I really appreciate your work on ib_insync.  The native IB API documentation might as well have been written in Latin.

**Comment by bb10128** [comment]
Problem resolved.
