### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement ib_sync

### ISSUE THREAD

**Issue by spitzbubchen** [erdewit/ib_insync#398]
Unable to install by pip. Get the following error:

```
ERROR: Could not find a version that satisfies the requirement ib_sync (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for ib_sync (from -r requirements.txt (line 1))
```

Note that installing it as `pip install "git+https://github.com/erdewit/ib_insync.git"` works so it is not from my end.

**Comment by erdewit** [comment]
This is the ib_insync project, not ib_sync

**Comment by spitzbubchen** [comment]
My apologies, I should have done a better job paying attention. Before I dive deeper into ib_insync I have one question:

Can it handle simultaneous requests (orders, history, etc.) at the same time?

The reason I ask is that I have a strategy running in TradingView that sends out alerts using webhooks that I pick up using Flask. For example, thefollowing works for requests that are a few seconds apart, however, when requests get < 1 sec apart I get the following error: `Peer closed connection. clientId 1 already in use? API connection failed: TimeoutError()`.

```
from flask import Flask, request, abort
from ib_insync import *

import nest_asyncio
nest_asyncio.apply()

async def ib(data):

    ib = IB()
    ib.connect('127.0.0.1', 4002, clientId=1)

    contract = Forex('EURUSD')
    bars = ib.reqHistoricalData(
        contract, endDateTime='', durationStr='300 D',
        barSizeSetting='1 hour', whatToShow='MIDPOINT', useRTH=True)

    # convert to pandas dataframe:
    df = util.df(bars)
    print(df)

    ib.disconnect()

    return


app = Flask(__name__)

@app.route('/')
def root():
    return 'online'

@app.route('/webhook', methods=['POST'])
async def webhook():

    # Get data
    data = request.get_json()
    await ib(data)
    return '', 200

if __name__ == '__main__':
    app.run(debug=True, port=8000)
```
