### ISSUE TITLE
Unfilled params

### ISSUE THREAD

**Issue by Elektra58** [erdewit/ib_insync#4]
Intellij IDEA code inspection indicates incorrect call arguments for the following two methods:

- `def exerciseOptions` (ib.py, line 798): parameter 'override' unfilled
- `def reqHistogramDataAsync` (ib.py, line 1007): parameter 'timePeriod' unfilled

**Comment by erdewit** [comment]
In both cases the reqId parameter was absent - this is fixed in the next version.

Thank you for reviewing the code.

**Comment by Elektra58** [comment]
Thought so. 

BTW: did you get my branch commits on GitHub? I fixed a couple of typos (thought to start on something simple)

**Comment by erdewit** [comment]
Looks like there are no commits yet to your branch. If you commit then you can create a pull request and send that to me.
