### ISSUE TITLE
Getting the underlying ibapi instances

### ISSUE THREAD

**Issue by athenawisdoms** [erdewit/ib_insync#40]
After placing the order with

    limitTrade = ib.placeOrder(contract, limitOrder)

is it possible to get the underlying `ibapi.Order`?

**Comment by erdewit** [comment]
limitTrade.order is the order.

**Comment by athenawisdoms** [comment]
Sorry, I meant to ask:

After creating the limit order with

    limitOrder = LimitOrder('BUY', 100, 0.05)

and before placing the order with

    limitTrade = ib.placeOrder(contract, limitOrder)

is it possible to get the `ibapi.Order`?

**Comment by erdewit** [comment]
There is no ibapi.Order, it is replaced by ib_insync.Order which is backwards compatible with it.

Not sure why you're interested in the ibapi object.
