### ISSUE TITLE
News_api

### ISSUE THREAD

**Issue by sudhanshu8833** [erdewit/ib_insync#405]
Hey, I have actually subscribed to the Dowjones API, but unable to fetch tick data for the API, if anyone is having code for news API, for interactive broker please let me know

**Comment by sudhanshu8833** [comment]
> please read https://interactivebrokers.github.io/tws-api/news.html

I actually, tried everything in that article, still I am yet to get the solution, I have a feeling that, TWSAPI, probably have not updated the documentation... I was looking for actually looking for code to subscribe news api

**Comment by erdewit** [comment]
A better place to ask is the TWSAPI group:
https://groups.io/g/twsapi
