### ISSUE TITLE
Discrepancies in getting recent data through ib_insync vs what is displayed in TWS

### ISSUE THREAD

**Issue by ksrm0024** [erdewit/ib_insync#406]
Hi,

As the title says I am finding differences between what I see when pulling historical data through ib_insync vs what I see when I check Trader Workstation. Here is my code:

`    contract =  Future('MES, '202112', 'GLOBEX')'`

    `def last14bars():
    dt = ''
    barsList = []

    bars = ib.reqHistoricalData(
        contract,
        endDateTime=dt,
        durationStr='840 s',
        barSizeSetting='1 min',
        whatToShow='MIDPOINT',
        useRTH=True,
        formatDate=1)

    barsList.append(bars)
    return bars`

Checking highs, lows, opens, and closes of each bar not only shows me different values than what I see in TWS, but also seems to show me the information in multiples of an eighth of a point rather than 0.25. Has anyone else run into these things or figured out a solution?

**Comment by erdewit** [comment]
>     whatToShow='MIDPOINT',

TWS probably shows the 'TRADES'.
