### ISSUE TITLE
Crypto order requires cash quantity? 

### ISSUE THREAD

**Issue by booboothefool** [erdewit/ib_insync#407]
When trying to place an order for crypto using `totalQuantity` it seems to require `cashQty`.  I would like to use `totalQuantity` to buy to enter instead so I can eventually sell the position to exit using the `totalQuantity` later. 

```python
contract = Crypto('BTC', 'PAXOS', 'USD')
ib.qualifyContracts(contract)
order = MarketOrder(
  action='BUY',
  totalQuantity=1,
  # cashQty=60000,
  orderId=ib.client.getReqId(),
  tif='IOC',
  outsideRth=False,
  transmit=True,
)
ib.placeOrder(contract, order)
```
```
message='Error 10289, reqId 3510: You must set Cash Quantity for this order'
```

**Comment by booboothefool** [comment]
Also
```
tif='Minutes',
```
```
Error 201, reqId 54: Order rejected - reason:The crypto MKT order must be IOC
```
I thought it could be either `'Minutes'` or `'IOC'`.

**Comment by erdewit** [comment]
I can only refer to the IBKR docs:
https://www.interactivebrokers.com/lib/cstools/faq/#/content/192326112

It's a strange limitation that a crypto order can't have a quantity, this makes it hard to get rid of small quantities ('dust').

**Comment by booboothefool** [comment]
Oh that's interesting. So I have to market buy in USD, but I can still sell in BTC or ETH. Strange indeed, but I can work with it. Thanks.
