### ISSUE TITLE
The list returned by reqRealTimeBars->barUpdateEvent can grow to infinite until system out of memory crash

### ISSUE THREAD

**Issue by bullhunter7** [erdewit/ib_insync#409]
Greetings,

I am using `reqRealTimeBars`->`barUpdateEvent` to get 5 second bars for a large list of contracts.

I am noticing that the list returned by the `barUpdateEvent` has the parameter `BarDataList` of type list and the following code adds new bars to the list:

https://github.com/erdewit/ib_insync/blob/10ee98a2a3c07de905bc0ff75b0065ff1994c699/ib_insync/wrapper.py#L529

If I run my code for a long period of time, the list will grow to infinite until system out of memory crash.

Am I missing anything? Is this by design or could be a bug?

Thank you,

**Comment by erdewit** [comment]
As answered in the insync group here:
https://groups.io/g/insync/message/7040
