### ISSUE TITLE
reqCompletedOrders generates different trade instances

### ISSUE THREAD

**Issue by dmoklaf** [erdewit/ib_insync#410]
**Bug description:**

Upon IB server reavailability (IB status code 1101 and 1102), my server (which is always run with clientid = 0 to catch everything) calls these methods to retrieve missing order updates (for orders that have changed during the unavailability or have be submitted by another client during that time):
- reqOpenOrdersAsync
- reqCompletedOrdersAsync
- reqExecutionsAsync

The second call generates new ib_insync Trade instances, different from the instances that were previously available. This corrupts my tracking as I assume, as most of the ib_insync library, that a Trade object is instantiated only once for a given order.

**Root cause analysis:**

The Wrapper class handles the main logic to update the ib_insync data structures upon reception of the reqCompletedOrders information:
https://github.com/erdewit/ib_insync/blob/10ee98a2a3c07de905bc0ff75b0065ff1994c699/ib_insync/wrapper.py#L378

This code does not try to retrieve existing Trade instances in the self.trades dictionary. It directly creates a new Trade instance.

**Fixes:**
Update this code to reuse existing Trade instances whenever they pre-exist.

**Versions:**
MacOS 11.6
Conda 4.10.3
Python 3.9.5
ib_insync 0.9.69

**Comment by erdewit** [comment]
It is intentional that doing an explicit ``reqCompletedOrders`` request just passes on the data directly as it is received, and not the already synced completed orders.

**Comment by dmoklaf** [comment]
This is not what `reqCompletedOrders` is doing: it does not only return trades as it receives them. It also, as a side effect, erases live Trade instances being tracked in parallel by the engine by replacing them in the Wrapper.trades and Wrapper.permId2Trade dictionaries, making any listener on these previous Trade instances going deaf (they don't receive events anymore).

It could be argued that these listeners had nothing to listen to (as the trades have just been completed) but this is not the case: there is a race condition there that depends on the order during which the client code calls reqCompletedOrders versus how the IB server sends back trade completion events.

**Comment by erdewit** [comment]
> It also, as a side effect, erases live Trade instances being tracked in parallel by the engine by replacing them in the Wrapper.trades and Wrapper.permId2Trade dictionaries

When going over the code, I don't see how trades can be replaced,

```python
        if order.permId not in self.permId2Trade:
            self.trades[order.permId] = trade
            self.permId2Trade[order.permId] = trade
```

In any case, there's not really a practical need to explicitly request the completed orders as they are already available in synced form.

**Comment by dmoklaf** [comment]
Hmm you are correct this could not explain my issue. There could be a edge case, a very exotic race condition, for just-submitted orders (that didn't have a permid yet and are stored with the orderid in the self.trades dictionary). But this is not what I observe in my logs. I need to investigate more my case, sorry for the noise
