### ISSUE TITLE
Connection listeners initialization shall be isolated as a separate IB object method

### ISSUE THREAD

**Issue by dmoklaf** [erdewit/ib_insync#411]
**Description:**

Upon IB server reavailability (IB status code 1101 and 1102), my server needs to re-subscribe to the standard account/positions/orders/executions events, following some code exactly like the standard ib_insync connection code:
https://github.com/erdewit/ib_insync/blob/20180813c2c768c408f1febe7e1373423dd9d0f0/ib_insync/ib.py#L1628

This replication exposes my server to code fragility: I am replicating highly-sensitive ib_insync code that could evolve later on due to newly discovered IB API bugs or API evolutions, and I might miss these later evolutions. These bugs would be even more subtle to catch as they would occur only after reavailability.

**Fixes:**

2 alternatives in ib_insync:

- Simple one: refactor this initialization code out of the ib.connectAsync method into a dedicated (public) ib.setupListenersAsync method, that client users can call themselves upon 1101/1102 reavailability events.

- More involved one: handle transparently 1101/1102 reavailability events within ib_insync. This ALSO requires a detailed tracking of pending market data subscriptions to be able to reset them upon a 1101 event (good news is my server code does handle that and it works well, I can show you the code if needed - it only requires to maintain a simple dictionary of live subscriptions:
contract -> genericTickList)

The first alternative seems an easy step forward.

**Versions:**
MacOS 11.6
Conda 4.10.3
Python 3.9.5
ib_insync 0.9.69

**Comment by erdewit** [comment]
All these issues can be bypassed by simply reconnecting the API connection.

The synchronization code in ``connectAsync`` is dependent on starting from a clean slate (i.e. directly after a fresh connection) and I don't think it's a good idea to expose this as a separate public method.

**Comment by dmoklaf** [comment]
I understand, this is an ib_insync design decision. You are correct that the client needs anyway to perform a reconciliation upon reavailability, so why not performing it through the same code that handles post-connect initialization by handling that as a disconnect/reconnect.

However, just in case some day other reasons unknown to us today lead you to revisit this decision, a few feedbacks:

(1) When submitting this issues, I had checked in detail the ib.py code (lines 1628 to 1658), and this initialization procedure is state-free, from what I have read it does not depend on starting from a clean slate or any specific state:
- It is a very thing wrapper around Client method to calls IB
- It does not depend on the IB object, or any other object, being in a particular state (no state variable consulted as an input)
- It does not leave any state change in the ib_insync IB object once it has completed (no state variable modified after completion)
- It does not have any side effect in any other ib_insync object once it has completed

(2) Second, I have been running for more than a year this simple reactivation procedure upon 1101/1102 events:
- It works well - I have not run over the last 12 months into the IB Gateway freeze that you had mentioned in the ib_insync discussion group once (the IB software just runs smoothly every time)
- It is very simple (a few lines of code)
