### ISSUE TITLE
IB socket protocol function codes

### ISSUE THREAD

**Issue by stucash** [erdewit/ib_insync#412]
we are blessed to have such a great tool, thanks very much, I once thought to write something to the same effect (though it would be a much smaller counterpart for myself only), but I reckoned it was a pretty involved task. I didn't see it to be this involved :P 

I have a side question here, I can see that you are sending a message over `TCP` protocol and the params (i.e., `fields` in your terminology) are easy to understand; however, I failed to see which functions in IB API these `fields` are matched for. e.g., 
```

def cancelOrder(self, orderId):
        self.send(4, 1, orderId)

def reqOpenOrders(self):
       self.send(5, 1)

def reqAccountUpdates(self, subscribe, acctCode):
       self.send(6, 2, subscribe, acctCode)
```

It seems to me that the first two digits represent the function code in IB socket protocol (such that the fields know where to go once they get sent off). 

I couldn't find any reference or source where these functions codes are, is that on IB API website? It'd be great if you could share that. Thanks very much.

**Comment by erdewit** [comment]
The IB socket protocol is not formally documented (that I know of) but there are reference implementations in various languages: https://interactivebrokers.github.io/
