### ISSUE TITLE
ib.openTrades() does not reflect updated information

### ISSUE THREAD

**Issue by PalmDr** [erdewit/ib_insync#415]
I constently encounter the issue:

I submitted an open trade on TWS but ib.openTrades() does not update to include the open trade.

And, when an open trade gets filled, ib.positions() instantly updates my position with the filled trade, but the filled trade (not open any more) is still in ib.openTrades().

**Comment by yarimiz** [comment]
I'm facing the same exact issue.

**Comment by gveneyjr** [comment]
This library has an active user forum here where I recommend reposting the question: https://groups.io/g/insync/topics

**Comment by erdewit** [comment]
A ``clientId=0`` is needed to see orders manually placed from TWS.

https://interactivebrokers.github.io/tws-api/open_orders.html
