### ISSUE TITLE
Error 322 

### ISSUE THREAD

**Issue by rezaa1** [erdewit/ib_insync#418]
When  I try to connect to gateway:
```
ib = IB()
ib.connect('127.0.0.1', 4001, clientId=11)
```

I get this error:
```
Error 322, reqId 2: Error processing request.-'cc' : cause - jextend.cc.n(cc.java:310)
<IB connected to 127.0.0.1:4001 clientId=11>

```
It was working before, it started all of the sudden, no change to anything!
Anyone had this issue?
Thanks

**Comment by August1328** [comment]
Hi @rezaa1,

I had a same resp. similar error message suddenly appearing a few months ago. I couldn´t find this this error on the internet, but I stumbled upon a post which said like try switching to the stable version of the TWS.

When you start the TWS, the login window appears. At the bottom there should be a dropdown menu called "More Options". The very first option is "Version". Try using "STABLE".

This solved this problem for me a few months ago...

**Comment by rezaa1** [comment]
Thanks for reply.

When I click on more options, there are some questions about them and path and browser,... but no version related questions.
I am on version 10.112e

**Comment by August1328** [comment]
Judging from the version you provided, we both talk about the TWS = Trader Work Station from IB.

I checked the IBKR website, Your version seems to be the LATEST version: [https://www.interactivebrokers.com/en/index.php?f=1657](url)

When I start the TWS login (on Windows 10) there comes a small window up, stating "Loading Trading (stable) ...":

![TWS_startup_stable](https://user-images.githubusercontent.com/78689005/145463358-2a81223d-60b3-4065-b085-e1c7b96269d0.jpg)

Then the login window appears. At the bottom, there´s the menue I mentioned:

![TWS_login_1](https://user-images.githubusercontent.com/78689005/145464194-145728d2-4972-4a30-a925-6b62c0949bca.PNG)

When opened, this menu looks like this, on the very top, you can select STABLE or LATEST:

![TWS_login_2](https://user-images.githubusercontent.com/78689005/145464328-aab09898-3a07-4a9f-b0c5-5989ad70a606.jpg)

What OS are you using?

**Comment by rezaa1** [comment]
Oh, sorry. I didn't realize TWS is diffrent. I am using IB Gateway, and there is no option for changing version in that.

**Comment by erdewit** [comment]
> Error 322, reqId 2: Error processing request.-'cc' : cause - jextend.cc.n(cc.java:310)

This is an internal TWS error.

**Comment by nono-london** [comment]
same issue here using Windows 10, Python 3.7 or 3.9.
and TWS:
Build 10.18.1e, Sep 20, 2022 4:11:21 PM Jolt Build 1.18.9, Jul 5, 2022 05:27:19 PM Nia Build 2.24.2, Jan 17, 2022 05:48:10 PM ModelNav Build 1.13.2, Jan 24, 2022 04:59:21 PM Riskfeed Build 2.45.3, Jul 25, 2022 06:42:42 PM  

Java Version: 1.8.0_202, OS: Windows 10 (amd64, 10.0), Memory: heap max 6144Mb, current 577Mb

Problem is on and off, and sometimes I get issues with "no internet connection" when actually connection works properly

Did notice answer TWS issue, but just in case someone knows what to do (IB customer service is terrible)
I have reinstall TWS and Java already
