### ISSUE TITLE
Unable to pull streaming data for future combo contracts

### ISSUE THREAD

**Issue by starovp** [erdewit/ib_insync#420]
Hi, long time user of insync. Recently I've had an issue where I'm unable to grab streaming market data for multi-leg futures contracts (calendar spreads). Am I doing something wrong or is this an IBKR issue?

Looking through the time and sales data, the contract is definitely liquid, and I've seen the contract itself trade live, with no updates on my end.

e.g. 

```python
import math
from ib_insync import *

ib = IB()
ib.connect('127.0.0.1', 7496, clientId=123, readonly=True)

symbol = 'CL'

contract = Contract()
contract.symbol = symbol
contract.currency = 'USD'
contract.exchange = 'SMART'
contract.secType = 'BAG'

leg1 = ComboLeg()
con1 = Contract(conId=256019290)
ib.qualifyContracts(con1)
leg1.conId = con1.conId
leg1.ratio = 1
leg1.action = 'BUY'
leg1.exchange = 'NYMEX'

leg2 = ComboLeg()
con2 = Contract(conId=256019295)
ib.qualifyContracts(con2)
leg2.conId = con2.conId
leg2.ratio = 1
leg2.action = 'SELL'
leg2.exchange = 'NYMEX'

contract.comboLegs = [leg1, leg2]

ib.reqMktData(contract, '', False, False)
ticker = ib.ticker(contract)

last_val = ticker.marketPrice()
while math.isnan(last_val):
    last_val = ticker.marketPrice()
print(last_val)
```

Followed the instructions as per the recipe regarding streaming FX ticks, and the combo's set up properly regarding exchanges, contract IDs, actions, etc as per IBKR support. Would appreciate some insight, or if there's a more proper way to do this.

Also, historical ticks aren't supported with futures combos, have tried that too.

**Comment by erdewit** [comment]
The while loop should give the framework a chance to update, for example like:
```python
last_val = float('nan')
while math.isnan(last_val):
    ib.waitOnUpdate()  # <<<< This will update the framework (and also avoid using 100% CPU)
    last_val = ticker.marketPrice()
```

**Comment by starovp** [comment]
Fantastic, that worked. Thank you! Appreciate it.
