### ISSUE TITLE
with reqTickers data is incomplete

### ISSUE THREAD

**Issue by tjhgit** [erdewit/ib_insync#423]
If I compare the convenience function:
`tickers = ib.reqTickers(*contracts)`

with:
ticker = ib.reqMktData(details[0].contract, snapshot=False, regulatorySnapshot=False)
and checking in a while loop for completeness of data ('bid', 'ask', 'delta' ...)

the second approach leads complete data , while reqTickers often returns nan for delta or -1 for bid, ask.

When looking at the implementation of reqTickers, I see that snapshot=True is used. Why?

**Comment by showalan** [comment]
I have experienced your case "... reqTickers often returns nan for delta or
-1 for bid, ask", please it will work at trade time.

**Comment by erdewit** [comment]
The data that you see is the data as sent by IB.
