### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-1'.

### ISSUE THREAD

**Issue by MaanasPeri23** [erdewit/ib_insync#424]
There were two ways I went about going to write my accountSummary function: 
@app.route('/accountSummary')
`def accountSummary():
    acctSumm = ib.accountSummary()
    temp = None
    for item in acctSumm: 
        if item.tag == 'GrossPositionValue':
            temp = item
            print(temp)
    #need to print the tag value of 'GrossPositionValue' (for example) 
    return acctSumm`

From which I am trying to query data using flask servers onto a new endpoint. I'm relatively to this, and got the following error as a result of running the function accountSummary() in my main. 

RuntimeError: There is no current event loop in thread 'Thread-1'.
127.0.0.1 - - [28/Dec/2021 13:14:17] "GET /accountSummary HTTP/1.1" 500 -
^Csys:1: RuntimeWarning: coroutine 'IB.accountSummaryAsync' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

I pretty much got the same error when I tried the direct source code in the ib_insync documentation: 
`
@app.route('/accountSummary')
async def accountSummaryAsync(self, account: str = ''):
        if not self.wrapper.acctSummary:
            # loaded on demand since it takes ca. 250 ms
            await self.reqAccountSummaryAsync()
        if account:
            return [v for v in self.wrapper.acctSummary.values()
                    if v.account == account]
        else:
            return list(self.wrapper.acctSummary.values())
`

I've checked into other forums that refer to the use of loop events but even after trying this I'm not having much luck. Any direction provided would be greatly appreciated:)

**Comment by erdewit** [comment]
You can follow for example this article:

https://testdriven.io/blog/flask-async/
