### ISSUE TITLE
Option Order 

### ISSUE THREAD

**Issue by djangodissilent** [erdewit/ib_insync#425]
I'm trying to create the following options contract and getting the following Output: 

Error 200, reqId 3: No security definition has been found for the request, contract: Option(symbol='SPY', lastTradeDateOrContractMonth='201701', strike=240, right='C', exchange='SMART')
[]

``` python from ib_insync import *

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=90)

opt_contract = Option('SPY', '201701', 240, 'C', 'SMART')

det = ib.reqContractDetails(opt_contract)


print(det)
ib.disconnect()

```
The code is taken from the docs notebook page

**Comment by erdewit** [comment]
Expired option contracts are not kept by IB, so better try with current options.
