### ISSUE TITLE
Getting portfolio share positions omits or rounds all fractional shares?

### ISSUE THREAD

**Issue by TechniumUnlimited** [erdewit/ib_insync#433]
Hello it seems that either the ib_insync api or ibkr tws api seems to round or omit (if rounding leads to 0) fractional shares. For some positions fractional shares that round to 0 can be worth thousands of dollars, is there a way to keep it from rounding?

Also if I have for instance, 57.68 shares, it rounds to 58.0 shares - which can end up leveraging a short if I were to sell what it tells me I have.

**Comment by erdewit** [comment]
Probably you have an older version of ib_insync - there's no position rounding in the current one.

**Comment by TechniumUnlimited** [comment]
I'm using 0.9.70 that pycharm finds when it searches for packages, says its the latest, do I need to clone the repo to get a newer version?

**Comment by erdewit** [comment]
That's the latest version which is good. The position data must then be sent already rounded by IB. I think a recent gateway/TWS is needed as well.

**Comment by TechniumUnlimited** [comment]
Ok, I'll just try to take proper precautions into account in my program. Thanks.
