### ISSUE TITLE
Support for new fundamental data interface

### ISSUE THREAD

**Issue by mdelvaux** [erdewit/ib_insync#434]
In the main IB API, reqFundamentalData() is now marked as deprecated, see https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#ac7862d96b6d5f045eaf4bf74ea2eda6f.  This interface still works as of now, but it is possible that IB will stop honoring these requests in the future

Fundamental data is still available via two new methods of the client:
- reqWshEventData https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#ae0e8c44f2e66705517df087c702bc621
- reqWshMetaData https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html#a66b482661e36604c43c4a7087bd7840f
apparently because the data provider has changed.

It would be nice for ib_insync to add support for the new interface, however it seems that access to the fundamental data using this new interface requires an expensive subscription, making testing more of a challenge.  The documentation says "It is necessary to have the Wall Street Horizon Enchilada Pro research subscription activated first in Account Management", checking that shows a rather steep monthly subscription of $250, with a trial available.

**Comment by erdewit** [comment]
Some basic support for the WSH methods has just been added. This is on the protocol level, bringing the support on par with what the official IBAPI is offering. Higher level integration within IB-insync is not likely to happen, given the high price of the subscription.

**Comment by volconst** [comment]
Hi,
In TWS Fundamentals Explorer window, tab 'Analyst Forecast' I can see EPS estimates.
I think this was accessible with the deprecated reqFundamentalData('RESC').
Is there a way to access the GUI data with API?
I am not subscribed to Enchilada, but see the estimates in GUI.
Source of these estimates is 'Refinitiv I/B/E/S'. Is it available with API?
