### ISSUE TITLE
Support for new SCHEDULE in reqHistoricalData

### ISSUE THREAD

**Issue by mdelvaux** [erdewit/ib_insync#435]
IB has introduced a new type of historical bar data, SCHEDULE, https://interactivebrokers.github.io/tws-api/historical_bars.html that seems to be the trading times for each trading day.  IB being IB also decided to use a different callback, probably because the format of the data returned is different.

It is possible to send the correct request using ib_insync, but the TWS side then makes the usual compatibility check and returns an error message.

1091 321 Error validating request.-'bS' : cause - Your client version is too low for:Historical Schedule requests NVDA

**Comment by erdewit** [comment]
This is supported in the repo version now in the form of ``IB.reqHistoricalSchedule``. I decided to use a new method for this as both the parameters and the returned result are very different from reqHistoricalBars.
