### ISSUE TITLE
Running ib_insync inside a thread (pull request)

### ISSUE THREAD

**Issue by romanrdgz** [erdewit/ib_insync#436]
So, I have been trying to run ib_insync inside a thread, so it doesn't interfere with the rest of the application and keep everything as tidy as possible.

Whenever I tried to create a Thread, and call ib_insync from there, I got the usual asyncio RuntimeError "There is no current event loop in thread 'IB-Thread'".

I am aware that asyncio only has an event loop in the main thread, so I tried creating a new loop and setting it as the event loop in the Thread class contructor with just asyncio.set_event_loop(asyncio.new_event_loop()). Nevertheless, although this is supposed to be executed before any ib_insync call is used, the error persisted.

So I though, why not changing it directly at util.py run function?

So instead of just requesting the loop at the first line of run funcion with asyncio.get_event_loop(), now I check for the RuntimeError and fix it by creating a new event loop if required:
```
    loop = None
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError as ex:
        if "There is no current event loop in thread" in str(ex):
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
        loop = asyncio.get_event_loop()
```

Works like a charm. I see no point for not pulling this to the library: if just using the main_loop, it will work without executing the exception code lines. And if anyone tries to work with threads, then the exception is executed and everything is carried out.

Any comments/variations on this?

**Comment by erdewit** [comment]
While it's possible to run ib_insync in its own thread, it's not something that I would advocate or facilitate.

Most ppl that use multi threading don't fully realize what they're doing, especially if they think they do...

**Comment by romanrdgz** [comment]
So, just because most people don't understand multithreading, you are not willing to include a small 8-line fix which does not interfere with those not using it?

As far as I know, most people don't understand asyncio and that hasn't stopped you from writing a whole library on it

**Comment by erdewit** [comment]
That's right.
