### ISSUE TITLE
ib.portfolio() returns empty list after changing from paper to live trading account

### ISSUE THREAD

**Issue by marksandstrom** [erdewit/ib_insync#438]
ib.portfolio() had returned the portfolio items properly while logged in to the paper trading account, but after logging out and re-logging in to the live trading account -- while ib.positions() returns the live account open positions properly -- ib.portfolio() returns an empty list, per below:

from ib_insync import *
util.startLoop()
ib = IB()
ib.connect()
<IB connected to 127.0.0.1:7497 clientId=1>

len(ib.positions())
7

ib.portfolio()
[]

Any idea for getting also ib.portfolio() to return the items of the live trading account?

Thanks!

![image](https://user-images.githubusercontent.com/7817913/152652378-e939a79a-27b5-4b94-8004-ce37d451f50d.png)

**Comment by erdewit** [comment]
The paper account is independent of the trading account.
