### ISSUE TITLE
Problem using reqHistoricalData within class method

### ISSUE THREAD

**Issue by cono6987** [erdewit/ib_insync#440]
Hi all,

I'm having a problem using reqHistoricalData when instantiating the IB client within a class.  The following code works perfectly and returns data as expected.

------
import datetime
from ib_insync import *
util.startLoop()

ib = IB()
ib.connect('127.0.0.1', 7496, clientId=14)

contract = Future('CL','202212','NYMEX')
end_date = datetime.datetime(2022,2,8).strftime("%Y%m%d %H:%M:%S")
data_span = '2 Y'
bar_size = '1 day'
bars = ib.reqHistoricalData(
        contract,
        endDateTime=end_date,
        durationStr=data_span,
        barSizeSetting=bar_size,
        whatToShow='TRADES',
        useRTH=True,
        formatDate=1)
--------

But when I attempt to instantiate the client within a class as in the script below, I get this error: 

Error 320, reqId 3: Error reading request.Message id 3.  Unable to parse data. java.lang.NumberFormatException: For input string: "False", contract: Future(symbol='CL', lastTradeDateOrContractMonth='202203', exchange='NYMEX')
Peer closed connection.

-----
import datetime
from ib_insync import *

client = GetPriceData(7496, clientId=25)

class GetPriceData(IB):

    def __init__(self, port, clientId):
        util.startLoop()
        IB.__init__(self)
        self.connect('127.0.0.1', port, clientId)
    
     def get_hist_bar_data(self, symbol, month, end_date, data_span = '2 Y', bar_size = '1 day', exchange='NYMEX', currency='USD', 
            type='TRADES', useRTH = 'False'):

         contract = Future(symbol,month,'NYMEX')
         bars = self.reqHistoricalData(
            contract=contract,
            endDateTime=end_date,
            durationStr=data_span,
            barSizeSetting=bar_size,
            whatToShow=type,
            useRTH=useRTH,
            formatDate=1,
            keepUpToDate=False,
            chartOptions=[]
            )

symbol = 'CL'
month = '202212'
end_date = datetime.datetime(2022,2,8).strftime("%Y%m%d %H:%M:%S")
hist_data = client.get_hist_bar_data(symbol, month, end_date)
-----

Other data retrieval methods such as reqMktData work as expected when the client connection is instantiated within the class in this way.    Thank you so much in advance for any suggestions.

**Comment by erdewit** [comment]
`useRTH = 'False'`

The problem is the quotes which makes it a string. It should be a bool.
