### ISSUE TITLE
positions() and portfolio() inconsistent

### ISSUE THREAD

**Issue by marksandstrom** [erdewit/ib_insync#442]
For our live trading account, ib.positions() and ib.portfolio() return inconsistent results, per below:
>>
from ib_insync import *
util.startLoop() 
ib = IB()
ib.connect('127.0.0.1', 7496, clientId=1)
<IB connected to 127.0.0.1:7496 clientId=1>
len(ib.positions())
5
len(ib.portfolio())
0
>>

Why is len(ib.portfolio()) 0, while len(ib.positions())  is 5?

The true number of portfolio items is 5.

Thanks for advice!

![image](https://user-images.githubusercontent.com/7817913/153677880-b92f5d22-2d35-4988-ac9c-0c60fe06b72f.png)

**Comment by erdewit** [comment]
You probably have multiple accounts. ``portfolio`` is for the default account, ``positions`` is for all accounts.
