### ISSUE TITLE
How to use `reqPositionsMulti`

### ISSUE THREAD

**Issue by stockviva-davidvv** [erdewit/ib_insync#447]
I want to subscribe to the position update for an individual account

```
async def get_managed_accounts(ib: IB):
    reqId = 999
    subaccounts = ib.managedAccounts()
    account = subaccounts[1]
    ib.client.reqPositionsMulti(reqId, account, "")
    while True:
        data = await ib.positionEvent
        if data.account == account:
            print(data)
```

The error occur as follow:
`AttributeError: 'Wrapper' object has no attribute 'positionMulti'`

It is a proper way to do this?

**Comment by erdewit** [comment]
``positionsMulti`` is not implemented (and is not planned to be).

**Comment by piotrgolawski** [comment]
Guys, this method is pretty important. Could you share other way of calculating profit or loss from trade?
