### ISSUE TITLE
nan in reqMktData or reqTickers snapshot

### ISSUE THREAD

**Issue by dafa321** [erdewit/ib_insync#451]
It had been working months ago, I have updated IBGateway 10.14(not sure it is
the issue)

dafa2$ cat test.py
from ib_insync import *
util.startLoop()

ib = IB()
ib.connect('127.0.0.1', 7496, clientId=15)

contracts = [Forex(pair) for pair in ('EURUSD', 'USDJPY', 'GBPUSD', 'USDCHF', 'USDCAD', 'AUDUSD')]
ib.qualifyContracts(*contracts)

eurusd = contracts[0]

for contract in contracts:
    ib.reqMktData(contract, '', False, False)
ticker = ib.ticker(eurusd)
ib.sleep(8)
print(ticker.marketPrice())
dafa2$ python3 test.py
nan

**Comment by erdewit** [comment]
> ib.sleep(8)

It can take 12 seconds for the ticker to be filled, so try sleeping a bit longer.
