### ISSUE TITLE
Good way to calculate indicators from streaming ib.reqTickByTickData(eurusd, 'BidAsk')

### ISSUE THREAD

**Issue by flare9x** [erdewit/ib_insync#452]
I was curious if there was a low latency way to calculate indicators or perform other functions to the incoming streaming data produced by ticker = ib.reqTickByTickData(eurusd, 'BidAsk'). 

I have tried to append to a pandas dataframe however only works with time.sleep(1 or 2). 

The time and sales window can come in very quick blocks / bursts. 

Curios to hear of any potential solutions. 

Andrew

**Comment by mattsta** [comment]
The ibkr data feeds are not great for algo indicators because they are, as you noted, delayed (or bundled) and can burst randomly to catch up on backlogs.

External data providers who specialize in full market data low latency feeds will be easier to program against.
