### ISSUE TITLE
Q: Possible to get individual futures contract's details (i.e. margin requirements)?

### ISSUE THREAD

**Issue by Paw2Pom** [erdewit/ib_insync#456]
Instead of account level's margin requirements, is it possible to get individual instrument's details?

For example - "MNQ" futures' initial and maintenance margin, is it possible?

Thank you so much!

**Comment by mattsta** [comment]
the IBKR API doesn't provide per-instrument margin details in the API, but you can preview an order to see how it would change your account's margin requirements with "`whatIf`" orders: https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.whatIfOrder

The only place I've seen IBKR publish their actual margin rates is at this page (which seems to update live or at least daily as needed): https://www.interactivebrokers.com/en/index.php?f=26662

If you still need actual margin prices per instrument, the tables on the IBKR margin page are structured well enough for pandas to read, then you can filter directly:

```python
In [1]: table = pd.read_html("https://www.interactivebrokers.com/en/index.php?f=26662")

In [2]: globex = table[9]

In [3]: globex[globex.Underlying == "MNQ"]
Out[3]: 
   Exchange GLOBEX Underlying            Product description Trading Class  ...  Currency  Has Options  Short Overnight Initial  Short Overnight Maintenance
65          GLOBEX        MNQ  Micro E-Mini Nasdaq-100 Index           MNQ  ...       USD          Yes                  3144.07                      2858.24

[1 rows x 12 columns]

In [4]: globex[globex.Underlying == "MNQ"].to_dict()
Out[4]: 
{'Exchange GLOBEX': {65: 'GLOBEX'},
 'Underlying': {65: 'MNQ'},
 'Product description': {65: 'Micro E-Mini Nasdaq-100 Index'},
 'Trading Class': {65: 'MNQ'},
 'Intraday Initial 1': {65: 2200.85},
 'Intraday Maintenance 1': {65: 2000.77},
 'Overnight Initial': {65: 3144.07},
 'Overnight Maintenance': {65: 2858.24},
 'Currency': {65: 'USD'},
 'Has Options': {65: 'Yes'},
 'Short Overnight Initial': {65: 3144.07},
 'Short Overnight Maintenance': {65: 2858.24}}
```
