### ISSUE TITLE
SPX value via  ticker in real time . 

### ISSUE THREAD

**Issue by ravijagan** [erdewit/ib_insync#457]
I have the ticker for SPX index . Want to get the current real time value.  I am subscribed and can see it in my TWS 

Ticker(contract=Index(conId=416904, symbol='SPX', exchange='CBOE', currency='USD', localSymbol='SPX'), time=datetime.datetime(2022, 3, 24, 17, 16, 47, 158314, tzinfo=datetime.timezone.utc), high=4505.48, low=4465.17, close=4456.24)

Problem :  The time is correct , it has yesterdays close . There is no "last value" it has high low etc 
tkrspx.last is "nan" 

Debug step 1 Nothing wrong with subscription: 
In fact I can get a ticker for any option contract  forSPX (any expiry/right/strike) and get the model greeks and underlying value and it give the real time value 

why this is problem : 
Because IBKR rep says so  . Confirmed with the rep twice that the "last" value of the ticker is not traded price but last value for SPX Index since index is not traded. 
" I am definitely not able to troubleshoot he behavior of ib_insync, so I am not sure what kind of calls it is using
But SPX will absolutely return a Last value
This can be seen in TWS itself
Now of course this doesn't mean a "last trade" !
But that is field used to show the present value of the index
And the index
sorry -- And the index value returns to the same Last price as any tradable instrument
"

Just for fun compare this to ES Spx mini  Ticker(contract=ContFuture(conId=477836957, symbol='ES', lastTradeDateOrContractMonth='20220617', multiplier='50', exchange='GLOBEX', currency='USD', localSymbol='ESM2', tradingClass='ES'), time=datetime.datetime(2022, 3, 24, 17, 16, 47, 393571, tzinfo=datetime.timezone.utc), bid=4487.75, bidSize=36.0, ask=4488.25, askSize=34.0, last=4488.0, lastSize=5.0, prevBid=4488.0, prevBidSize=1.0, prevAsk=4488.0, prevAskSize=15.0, prevLast=4487.75, prevLastSize=20.0, volume=764889.0, open=4449.25, high=4498.5, low=4445.75, close=4447.5, halted=0.0)

**Comment by erdewit** [comment]
> There is no "last value" it has high low etc tkr spx.last is "nan"

It is filled for me:

```
Ticker(contract=Index(conId=416904, symbol='SPX', exchange='CBOE', currency='USD', localSymbol='SPX'), 
time=datetime.datetime(2022, 3, 24, 19, 36, 25, 281689, tzinfo=datetime.timezone.utc), minTick=0.01, 
last=4510.99, lastSize=0.0, prevLast=4511.02, high=4514.47, low=4465.17, close=4456.24, ticks=
[TickData(time=datetime.datetime(2022, 3, 24, 19, 36, 25, 281689, tzinfo=datetime.timezone.utc), tickType=4, 
price=4511.02, size=0.0), TickData(time=datetime.datetime(2022, 3, 24, 19, 36, 25, 281689, 
tzinfo=datetime.timezone.utc), tickType=4, price=4510.99, size=0.0)])
```

**Comment by ravijagan** [comment]
Thanks On upgrading to latest version It works for me too
