### ISSUE TITLE
reqHistoricalData not working for crypto

### ISSUE THREAD

**Issue by nirvana1122** [erdewit/ib_insync#459]
I cannot make it work for cryptos, though it works fine for CME crypto futures.

import pandas as pd, time, datetime as dt
from ib_insync import util, IB, Future, Crypto

ib = IB()
ib.connect('127.0.0.1', 7496, clientId=10)
contract = Crypto(symbol=ticker, exchange='PAXOS', currency='USD')

bars = ib.reqHistoricalData(contract, endDateTime='20220309 00:00:00', durationStr='1 D',
barSizeSetting='1 min', whatToShow='Trades', useRTH=False)

Error 321, reqId 3: Error validating request.-'bT' : cause - Please enter a valid security type, contract: Crypto(symbol='BTC', exchange='PAXOS', currency='USD')
No data for BTC

What am I doing wrong?

Thanks

**Comment by erdewit** [comment]
With a newer version of TWS it should work, it does for me and I don't even have crypto permissions.

```
[BarData(date=datetime.datetime(2022, 3, 8, 22, 1), open=38507.0, high=38565.0, low=38507.0, close=38565.0, volume=0.05448136, average=38542.0, barCount=25), ...]
```
