### ISSUE TITLE
doing loops to get historical data and execute order at specific time 

### ISSUE THREAD

**Issue by dccw** [erdewit/ib_insync#46]
Hello,

Wondering if there is an easy way to get historical data and execute order at specific time. For example, in the first second of every minute (e.g. 15:00:01, 15:01:01, 15:02:01, 15:03:01...) i want to get some data and execute orders. 

Thanks.

**Comment by erdewit** [comment]
This is possible with IB.timeRange:

```python
import datetime
from ib_insync import *

startTime = datetime.time(0, 0, 1)
endTime = datetime.time(22, 0, 1)
for t in IB.timeRange(startTime, endTime, 60):
    print(t)
```
