### ISSUE TITLE
Timestamps don't match, `Bars.date` and output of `util.df()`

### ISSUE THREAD

**Issue by goodboy** [erdewit/ib_insync#460]
Eg.

```python
# example single datum retreived from .reqHistoricalDataAsync
bars = [BarData(date=datetime.datetime(2022, 3, 28, 9, 38, 27), open=14839.75, high=14843.0, low=14839.5, close=14843.0, volume=57.0, average=14841.35, barCount=36)]

from ib_insync.util import df
frame = df(bars)

# seems to fail
assert frame['date'][0] == bars[0].date.timestamp()
```

Not sure exactly what the cause is (likely the pandas `Timestamp` casting and timezone stuff?) but the offset for me is `14400.0` with 1 second sampled OHLC.

**Comment by erdewit** [comment]
> assert frame['date'][0] == bars[0].date.timestamp()

That's comparing a pandas Timestamp with a float, so yeah that's not going to be equal.

**Comment by goodboy** [comment]
@erdewit i said there was an offset of `14400` 🤷🏼 

Anyway not using your `util.df()` routine and just doing it manually with `numpy` makes that assert work just fine, so anyone that has the same issue just ping me 😂

**Comment by goodboy** [comment]
As an example this (context specific) code passes just fine.

```python
        np_ready = []
        for bardata in bars:
            ts = bardata.date.timestamp()
            t = astuple(bardata)[:7]
            np_ready.append((ts, ) + t[1:7])

        nparr = np.array(
            np_ready,
            dtype=base_ohlc_dtype,
        )
        assert nparr['time'][0] == bars[0].date.timestamp()
```

the problem **was not** a floating point precision issue, there was a large offset as mentioned.

**Comment by erdewit** [comment]
My point was that the comparison was between incompatible types.

It seems that pandas ``TImestamp`` behaves a little different from Python's ``datatime`` when it comes to their ``timestamp()`` method: The first assumes UTC and the second assumes local timezone for tz-naive values.

Generally it's best to stick to explicit UTC times, which can be done by with ``reqHistoricalData(..., formatDate=2)``.

**Comment by goodboy** [comment]
> My point was that the comparison was between incompatible types.

Yeah because i made a typo 😂

**Comment by erdewit** [comment]
> the data you get from ib does not match the data output from that helper.

Not true at all. The dataframe returned from ``util.df`` has the same timestamps that the bar data has, but then in pandas form.
