### ISSUE TITLE
Realized PnL for single positions returning 1e308

### ISSUE THREAD

**Issue by starovp** [erdewit/ib_insync#462]
Hi, I'm trying to grab the pnl values for a given position. When doing so, the realized pnl returns an abnormally large number, if the position has not been traded in the current session. I'm guessing this has something to do with values being close to zero, or nan->inf, but wanted to make sure or see if there's a solution for this. 

to replicate:

```python
from ib_insync import *
import numpy as np

ib = IB()
port = 7496
clientId = 100
ib.connect("127.0.0.1", port, clientId=clientId, readonly=True)

acc = 'UXXXXXXX'
positions = ib.positions(acc)

for pos in positions:
    single_args = (acc, "", pos.contract.conId)
    pos_pnl = ib.reqPnLSingle(*single_args)
    while np.isnan(pos_pnl.dailyPnL):
        ib.sleep(0.1)
    ib.cancelPnLSingle(*single_args)
    print(pos_pnl.realizedPnL)
```

yields ```1.7976931348623157e+308```if the position has not been traded today (aka largest number possible to represent). This only occurs while using ```reqPnLSingle```, not the account-wide ```reqPnL```. The other values are properly set and have valid values, this only affects realizedPnL.

**Comment by mattsta** [comment]
Yeah, that's part of weird IBKR API decisions. Their docs say "unpopulated values are set to maximum double representation until generated": https://interactivebrokers.github.io/tws-api/pnl.html

**Comment by erdewit** [comment]
Note that the default value of these fields is "NaN" and that they get explicitly filled by IBKR as DOUBLE_MAX.
