### ISSUE TITLE
How can I make the trade order executed?

### ISSUE THREAD

**Issue by mikolaje** [erdewit/ib_insync#463]
Hi, I want to place an order whenever it's available including the pre-market and post-market. 
Here is my snippet:
```
contract = Stock(symbol, 'SMART', 'USD')


sell_order = LimitOrder("SELL", 1, 100)
trade = ib.placeOrder(contract, sell_order)
print(trade.orderStatus)
```

Why the trade status is `status='PendingSubmit'`, instead of `submitted`. BTW, I'm running with the live trading mode.

 I also set the RTH on TWS.

![image](https://user-images.githubusercontent.com/11773334/161243461-6efca0d4-20f7-4c2b-a4ee-0b883bd21b14.png)

I checked all the document, but can't find any solution. How can I achieve it? 

Thank you so much.

**Comment by mattsta** [comment]
Each individual order needs `.outsideRth = True` in addition to the TWS/Gateway settings: https://ib-insync.readthedocs.io/api.html#ib_insync.order.Order.outsideRth

**Comment by mikolaje** [comment]
> Each individual order needs `.outsideRth = True` in addition to the TWS/Gateway settings: https://ib-insync.readthedocs.io/api.html#ib_insync.order.Order.outsideRth

Thanks a lot, I take a try.
