### ISSUE TITLE
Cannot update limit price of Combo order

### ISSUE THREAD

**Issue by 4everlove** [erdewit/ib_insync#464]
Hi, I have no problem creating and cancelling a limit combo order. However, whenever I try to modify the price, I'm getting 

>  Error 105, reqId 5: Order being modified does not match original order.

Here is a code snippet for reproducing the issue:

```
from ib_insync import *
import datetime
import logging

def update_order(ib):
  spxw_contracts = [
      Option('SPX', '20220617', 1100, 'P', 'SMART', tradingClass='SPXW'),
      Option('SPX', '20220617', 1000, 'P', 'SMART', tradingClass='SPXW'),
  ]
  spxw_contracts = ib.qualifyContracts(*spxw_contracts)
  combo = Contract(
      secType='BAG',
      symbol='SPX',
      exchange='SMART',
      currency='USD',
      tradingClass='SPXW',
      comboLegs=[
          ComboLeg(
              conId=spxw_contracts[0].conId,
              ratio=1,
              action='SELL',
              exchange='SMART'),
          ComboLeg(
              conId=spxw_contracts[1].conId,
              ratio=1,
              action='BUY',
              exchange='SMART'),
      ])
  order = LimitOrder(action='BUY', totalQuantity=1, lmtPrice=-1.45, orderRef='spread_p_0.02_sto')
  trade = ib.placeOrder(combo, order)
  ib.sleep(5)
  order.lmtPrice = -1.40
  trade = ib.placeOrder(combo, order)
  ib.sleep(10)
  print(trade)


ib = IB()
ib.connect('127.0.0.1', 4001, clientId=37)
util.logToConsole(logging.DEBUG)

update_order(ib)
```

Even if I commented out the line of `order.lmtPrice = -1.40` I still got the error message.

I'm using
> ib_insync: `0.9.70` (this is also replicable in `0.9.66`)
> tws_gateway: `10.15` (this is also replicable in `10.12`)

Any thoughts? Thanks!

**Comment by volconst** [comment]
Are order and trade.order the same object?

**Comment by 4everlove** [comment]
Yes they are. I also tried to change the line `order.lmtPrice = -1.40` to `trade.order.lmtPrice = -1.40` and I was still getting the same error message.

**Comment by volconst** [comment]
@4everlove , comment/remove the line specifying tradingClass='SPXW' for the BAG contract

**Comment by rundef** [comment]
@volconst 's solution works

Here's my code:

```
order.lmtPrice = -1.40
trade = ib.placeOrder(dataclasses.replace(combo, tradingClass=''), order)
```

**Comment by 4everlove** [comment]
Sorry for the late response. Yes removing `tradingClass` works for me. Thanks @volconst for the solution and @rundef for verifying!
