### ISSUE TITLE
Can't find "make final" for American options.

### ISSUE THREAD

**Issue by hwu5** [erdewit/ib_insync#465]
The API's options trading worked fine, but how to make an option exercise "final" aka get the underlying stock right away? 
This is provided in the user interface but nowhere to be found in the API.

**Comment by mattsta** [comment]
https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.exerciseOptions

**Comment by erdewit** [comment]
There's also a global TWS setting to set the option exercises as either final or editable, this can't be done via the API.
