### ISSUE TITLE
ibc.terminate() doesn't work

### ISSUE THREAD

**Issue by majiayu000** [erdewit/ib_insync#466]
I want to use ibc or some other method close tws which is already started, this is my code
```
from ib_insync import *

    
ibc = IBC(981, gateway=False, tradingMode='paper')

ibc.terminate()

```
But nothing happened after runed it. What's wrong with me?

Thank you!

**Comment by erdewit** [comment]
IBC can't be used to terminate an already running TWS.
TWS needs to be started using IBC for it to be possible to terminate it via IBC.
