### ISSUE TITLE
Auto Reconnect when TWS Restarts

### ISSUE THREAD

**Issue by msacs09** [erdewit/ib_insync#469]
Folks,

Can anyone shed some light on how we code for auto reconnect, when TWS clients disconnected, effectively ending our API connectivity. Currently I need to restart my BOT daily when TWS restarts. I was wondering if anyone has done a similar code where it checks like heartbeat and reconnect, so that I don't have to restart my BOT every day when TWS restarts. I'm not sure if IB_Insync has any function out of the box?

Many Thanks

**Comment by mattsta** [comment]
I'm not sure about TWS, but the [standalone gateway](https://investors.interactivebrokers.com/en/index.php?f=16454) has an auto-restart time you can configure under menu options `Configure -> Settings -> Lock and Exit -> Auto restart`. The built-in auto-restart even caches your 2FA session for a week when it restarts (as long as your IP address doesn't change between runs).

For the ib_insync client, you can add your reconnect method to the `disconnectedEvent` event so ib_insync will automatically re-establish the connection after gateway restarts (and a _gateway restart_ is *different* than the nightly "system reset" where your connection remains active but the IBKR system goes offline and terminates all data feeds for 1-3 minutes).

I use the disconnected notification event like:

```python

ib = IB()
ib.disconnectedEvent += lambda: asyncio.create_task(reconnect())
```

where `reconnect()` is an `async` method running your `ib.connectAsync()` call and any other setup required like re-subscribing to quotes/feeds/updates.

**Comment by msacs09** [comment]
Thanks Matt. 

I have used as below and the console still prints "Not connected" when I force the Gateway/TWS to stop and restart. I'm I missing something for it to auto-reconnect please?

```
import nest_asyncio
nest_asyncio.apply()

ib = IB()
ib.connect('127.0.0.1', 7498, clientId=21)
ib.disconnectedEvent += lambda: asyncio.create_task(reconnect())
```

**Comment by msacs09** [comment]
Thank you very much
