### ISSUE TITLE
TWS connection lost

### ISSUE THREAD

**Issue by dccw** [erdewit/ib_insync#47]
hello

Just wondering if there is any good solution do deal with the issue of TWS losing connection when I am getting data and executing orders inside a loop. 

Thanks.

**Comment by erdewit** [comment]
There's a new Watchdog class that will restart TWS and then reconnect, you can check that out.

**Comment by dccw** [comment]
Thanks @erdewit . I have checked out the Watchdog class. Just wondering if there is any example on using the class?

**Comment by erdewit** [comment]
There is a test case at the bottom of the [ibcontroller.py](https://github.com/erdewit/ib_insync/blob/master/ib_insync/ibcontroller.py) file.
