### ISSUE TITLE
comboLegsDescrip missing on Positions Contract

### ISSUE THREAD

**Issue by alyahmady** [erdewit/ib_insync#470]
Hello.

I was facing an issue. I send some information with my contracts, using `comboLegsDescrip` field, during placeOrder. When I get it's position, I don't have my description in the positions contract anymore.

**Comment by erdewit** [comment]
The legs become individual and unrelated contracts when the order is filled.

**Comment by alyahmady** [comment]
Thanks erdewit for your quick response.

Actually I'm putting the notes on this field for all the contracts 1 Bag and 2 Options of its legs).

I was receiving the data when I was working with IB native callbacks, in the `position` callback function.

**Comment by erdewit** [comment]
``comboLegsDescrip`` is sent back for open orders but not for positions.
