### ISSUE TITLE
Repair after hours `.marketPrice()` logic

### ISSUE THREAD

**Issue by mattsta** [erdewit/ib_insync#471]
https://github.com/erdewit/ib_insync/blob/ddf86d398bef88a3877309fb74f37a08f493a0da/ib_insync/ticker.py#L151-L156

During non-market-hours the bid and ask are both -1 (or nan), so the range check fails, then the `.midpoint()` also fails (because bid and asks are combinations of -1 and nan), so `.marketPrice()` returns the previous day close instead of the most recent last price seen (example: currently for Sunday night, `.marketPrice()` is returning the Thursday close price because of how the IBKR quote/ticker system updates `open`/`close` only at new market sessions).

Looks like the logic could be updated to either:

- just change the nan override to `.last` instead of `.close`
- or check for full accuracy:
  - if (bid is nan or -1) and (ask is nan or -1), use `last`
  - if bids and asks are active, and if price is outside the spread, return synthetic `.midpoint()`

**Comment by mattsta** [comment]
Update...

so it appears the IBKR server returns a different three different kinds of ticker results depending on the time of day:

- live values during open market hours (good)
- after market closed, but before new market day, values remain populated as they were seen on the market day (this includes after market hours, the `.close` value returns the _prior day_ close until midnight the next market day).
- market-day, but before market open, all fields are set to nan except for `.close`, which is now the actual prior "most recent market day" close value.

With those three combinations, a safe order looks like:

- midpoint if `last` out of range
- `last` (if not nan)
- `close` (as a fallback if `last` is nan)

**Comment by erdewit** [comment]
Doesn't the existing code already follow the proposed order?

Note that for after-hours it is more of less essential to use frozen data (``ib.reqMarketDataType(2)``) to get a filled ticker. This will alter the ``marketPrice()`` result too.

**Comment by mattsta** [comment]
a quick example:

after market hours, bid and ask (both price and size) are -1 or nan.

so the check for `self.hasBidAsk()` fails, then the `self.midpoint()` returns nan because there's no bid/ask for midpoint calculation.

Now `price` is nan, so `price` becomes `self.close`, but `self.close` is the close of the _previous market day_ which is not related to the currently expected market price at all.

For example now, on the weekend, checking AAPL's `.marketPrice()` returns the closing price from Thursday, not the price from Friday.

**Comment by erdewit** [comment]
The behaviour of ``ticker.close`` is indeed very unfortunate and confusing and I will remove it from the market price calculation.

With frozen data for AAPL I do get the expected behaviour:

```python
ib.reqMarketDataType(2)
contract = Stock('AAPL', 'SMART', 'USD')
[ticker] = ib.reqTickers(contract)
print(f'{ticker.bid=}, {ticker.ask=}, {ticker.last=}, {ticker.close=}, {ticker.marketPrice()=}')
```
ticker.bid=157.0, ticker.ask=157.13, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=157.065

**Comment by mattsta** [comment]
that's an interesting result! I only use `.reqMktData()` for all quotes, so maybe there's a difference between the tickers snapshot and the live market data feed (even with type 2 data)?

I know after market hours all the big/ask values get set to nan or -1 when using `.reqMktData()`, but the results do look correct using the `.reqTickers()` snapshot.

**Comment by erdewit** [comment]
With a streaming ticker I get the same result:

```python
ib.reqMarketDataType(2)
contract = Stock('AAPL', 'SMART', 'USD')
ticker = ib.reqMktData(contract)
ib.sleep(2)
print(f'{ticker.bid=}, {ticker.ask=}, {ticker.last=}, {ticker.close=}, {ticker.marketPrice()=}')
```
ticker.bid=157.0, ticker.ask=157.13, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=157.065

**Comment by mattsta** [comment]
wow, still really interesting because it 100% doesn't do that for my data.

maybe it's a data package difference or maybe an API endpoint difference (my gateway is using `usfarm,usopt,usfuture` etc)?

I'm also subscribed to 10 different data packages ("value bundles," futures top level, options DOM across exchanges), so maybe some of those are causing IBKR to not retain last seen bid/ask values for my feed when the market day ends (I can watch it happen in real time: at exactly 8pm Eastern on market days, every equity bid/ask in my live quote viewer goes to NaN/-1 and they don't show values again until the next 0400 market open).

```python
>>> ib.reqMarketDataType(2)
>>> contract = Stock('AAPL', 'SMART', 'USD')
>>> ticker = ib.reqMktData(contract)
>>> ib.sleep(2)

>>> print(f'{ticker.bid=}, {ticker.ask=}, {ticker.last=}, {ticker.close=}, {ticker.marketPrice()=}')
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
>>> for i in range(30):
...   print(f'{ticker.bid=}, {ticker.ask=}, {ticker.last=}, {ticker.close=}, {ticker.marketPrice()=}')
...   ib.sleep(2)
... 
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
ticker.bid=nan, ticker.ask=nan, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
```


Running the regular public version:
```haskell
name         : ib-insync
version      : 0.9.70
description  : Python sync/async framework for Interactive Brokers API

dependencies
 - eventkit *
 - nest-asyncio *
```

**Comment by mattsta** [comment]
also for reference using `.reqTickers()`:

```python
>>> ib.connect(port=4001)
<IB connected to 127.0.0.1:4001 clientId=1>
>>> ib.reqMarketDataType(2)
>>> contract = Stock('AAPL', 'SMART', 'USD')
>>> [ticker] = ib.reqTickers(contract)
>>> print(f'{ticker.bid=}, {ticker.ask=}, {ticker.last=}, {ticker.close=}, {ticker.marketPrice()=}')
ticker.bid=-1.0, ticker.ask=-1.0, ticker.last=157.15, ticker.close=156.54, ticker.marketPrice()=156.54
```

**Comment by erdewit** [comment]
@mattsta What I notice is that you still get a last value even without bid/ask. So the last value is still useful by itself and I will update the logic to take this into account.

When I try today (Monday morning, European servers), I get a ticker with only ``ticker.close=157.28``. This is visible in TWS as well, there's no grayed-out bid/ask anymore.
