### ISSUE TITLE
ib.qualifyContracts() blocks endlessly on certain futures contracts but not others

### ISSUE THREAD

**Issue by tstreufert92** [erdewit/ib_insync#474]
ib.qualifyContracts blocking forever, not returning anything, on certain futures contracts but not others

For example this works just fine:
```
In [76]:contract = [Future(symbol='ZC', lastTradeDateOrContractMonth='202303', exchange='ECBOT')]
ib.qualifyContracts(*contract)
Out[76]: [Future(conId=460126199, symbol='ZC', lastTradeDateOrContractMonth='20230314', multiplier='5000', exchange='ECBOT', currency='USD', localSymbol='ZC   MAR 23', tradingClass='ZC')]
```

But this code blocks endlessly never returning anything, including no error message
```
contract = [Future(symbol='RB', lastTradeDateOrContractMonth='20220630', multiplier='42000', currency='USD', localSymbol='RBN2', tradingClass='RB')]
ib.qualifyContracts(*contract)
```
It also doesn't work if I specify only the known conId (same RB future)
```
contract = [Contract(conId=344035153)]
ib.qualifyContracts(*contract)

```

I recently updated form ib_insync 0.9.58, code was working before the update

Windows 10
Current stable version of TWS
```
ib_insync.__version__
Out[83]: '0.9.70'
```

**Comment by tstreufert92** [comment]
Still not working the next day. Log files not providing any clues

![snip](https://user-images.githubusercontent.com/69520140/166974436-9159986d-521f-49b4-b994-8eb2895e6cf3.png)

**Comment by tstreufert92** [comment]
Update 2:

I tested this on a separate username/login linked to the same F account. Same F account, different userid. qualifyContracts worked with the second user id

Inspecting the log files, the first user (qualifyContracts not working) is downloading ~25MB of messages upon connecting, mostly execution and commission details from trades made two days ago.

The second user (qualifyContracts working) is downloading about 1MB of messages. it does not download all the execution and commission details from previous trades on connection.

**Comment by erdewit** [comment]
I have no special insight into why IBKR does the things that they do and why a response is returned for one user and not the other. Could have to do with permissions, better ask them.
