### ISSUE TITLE
qualifyContractsAsync -> AttributeError: 'Forex' object has no attribute 'tag',  qualifyContracts -> Error 10225, reqId 29: Bust event occurred, current subscription is deactivated.

### ISSUE THREAD

**Issue by fritol** [erdewit/ib_insync#477]
when running 
`contract = await self.ib.qualifyContractsAsync(contract)`
from within an asyncio function i get

```
Task exception was never retrieved
future: <Task finished name='Task-375' coro=<App.run() done, defined at <ipython-input-70-3364dd0b01fc>:9> exception=AttributeError("'Forex' object has no attribute 'tag'")>
Traceback (most recent call last):
  File "c:\poop\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "<ipython-input-70-3364dd0b01fc>", line 37, in run
    self.ib.reqRealTimeBars(contract, 30, 'MIDPOINT', False)
  File "c:\poop\lib\site-packages\ib_insync\ib.py", line 986, in reqRealTimeBars
    self.client.reqRealTimeBars(
  File "c:\poop\lib\site-packages\ib_insync\client.py", line 776, in reqRealTimeBars
    self.send(
  File "c:\poop\lib\site-packages\ib_insync\client.py", line 250, in send
    s = ''.join(f'{v.tag}={v.value};' for v in field)
  File "c:\poop\lib\site-packages\ib_insync\client.py", line 250, in <genexpr>
    s = ''.join(f'{v.tag}={v.value};' for v in field)
AttributeError: 'Forex' object has no attribute 'tag'
```
it throws it for any asset

when i use 
``self.ib.qualifyContracts(contract)``
then `ib.reqRealTimeBars` works fine for stocks but Index() contract gives :

`Error 321, reqId 69: Error validating request.-'bT' : cause - Please enter exchange, contract: Index(symbol='TRIN-NYSE')
Error 10225, reqId 29: Bust event occurred, current subscription is deactivated. Please resubscribe real-time bars immediately., contract: Index(conId=26718743, symbol='TRIN-NYSE', exchange='NYSE', currency='USD', localSymbol='TRIN-NYSE')`

**Comment by erdewit** [comment]
> contract = await self.ib.qualifyContractsAsync(contract)

qualifyContracts returns a list. Leave out the "contract =" part and it will work.

**Comment by fritol** [comment]
Hey Ewald,
this accounts for the `"...tag..."` error but the TRIN-NYSE, TICK-NYSE persists:

`Error 321, reqId 69: Error validating request.-'bT' : cause - Please enter exchange, contract: Index(symbol='TRIN-NYSE') Error 10225, reqId 29: Bust event occurred, current subscription is deactivated. Please resubscribe real-time bars immediately., contract: Index(conId=26718743, symbol='TRIN-NYSE', exchange='NYSE', currency='USD', localSymbol='TRIN-NYSE')`

For example VIX CBOT works fine only these two do **NOT**.


thx for ur work!
