### ISSUE TITLE
coroutine 'Watchdog.watchAsync' was never awaited

### ISSUE THREAD

**Issue by AfroMetal** [erdewit/ib_insync#48]
```
/usr/lib/python3.6/socketserver.py:544: RuntimeWarning:

coroutine 'Watchdog.watchAsync' was never awaited
```

ib_insync 0.9.3

I am getting this warning when using new `Watchdog`. It uses one of 3 `IB`s that are connected all the time, to keep TWS alive with ib-controller.

`Watchdog` and other 2 `IB`s are run in separate `threading.Thread` that is the live algorithm using those clients.

First `IBController` is created:
```
self.controller = IBController(APP='GATEWAY',  # 'TWS' or 'GATEWAY'
                                   TWS_MAJOR_VRSN=config.get('TWSMajorVersion'),
                                   TRADING_MODE=config.get('TWSTradingMode'),
                                   IBC_INI=config.get('IBCIniPath'),
                                   IBC_PATH=config.get('IBCPath'),
                                   TWS_PATH=config.get('TWSPath'),
                                   LOG_PATH=config.get('IBCLogPath'),
                                   TWSUSERID='',
                                   TWSPASSWORD='',
                                   JAVA_PATH='',
                                   TWS_CONFIG_PATH='')
```
Then `Watchdog` is initialized and started:
```
super().__init__(controller=self.controller,
                 host='127.0.0.1',
                 port='4002',
                 clientId=self.client_id,
                 connectTimeout=connect_timeout,
                 appStartupTime=app_startup_time,
                 appTimeout=app_timeout,
                 retryDelay=retry_delay)
super().start()
```

Is there anything else that I have to do?

**Comment by erdewit** [comment]
The warning is likely not something serious but i will look into how it can be avoided.

**Comment by AfroMetal** [comment]
@erdewit so my initialization of `Watchdog` is good and it works fine then, yes? Because the TWS freezes for me everyday when run with `ib-controller` 24/7. I hope it will resolve the problems.

To restart 'manually' is calling `Watchdog.scheduleRestart()` at predefined hour enough? I would like to restart the `ib-controller` and therefore IBGateway at 2:30 UTC each day.

**Comment by erdewit** [comment]
@AfroMetal  the watchdog instantiation looks okay. The use of the threading and socketserver module looks a bit troubling in the sense that they do not work well with asyncio so I hope you have thought that through.

For a manual restart, first do watchdog.stop() and then watchdog.scheduleRestart(). In my experience the gateway is restarted at least once a day anyway because of either timeout or error 1100.

**Comment by AfroMetal** [comment]
@erdewit would you recommend moving to [`multiprocessing`](https://docs.python.org/3.6/library/multiprocessing.html?highlight=process#module-multiprocessing) instead of `threading`?

**Comment by erdewit** [comment]
@AfroMetal I can't really recommend anything as I have no clue what your project looks like. For myself I prefer asyncio in a single thread and use [distex](https://github.com/erdewit/distex) to farm out to other processes.

**Comment by erdewit** [comment]
This should be no longer a problem.
