### ISSUE TITLE
Missing data when using "formatDate=2" inside reqHistoricalData function

### ISSUE THREAD

**Issue by Sdoof** [erdewit/ib_insync#481]
Hello 

As per the thread on groups.io, I think I have found out what may be a bug when setting formatDate=2 with 4 hours of data missing, I am EST time while I am requesting UTC time for consistency, the daily 4 hours gap on EURUSD is illustrated with code and output here:
https://groups.io/g/insync/topic/91467033#7923

![image](https://user-images.githubusercontent.com/5991149/174457213-4f8f7bec-fc93-4555-b590-1f9e00afa754.png)

The issue disappears when setting "formatDate = 1".

**Comment by erdewit** [comment]
The ``endDateTime`` parameter of ``reqHistoricalData`` is assumed to use the same timezone as TWS, even if a datetime with a different timezone is supplied.

It is possible to use a different timezone if ``endDateTime`` is supplied as a string with an explicit timezone that TWS understands, see https://interactivebrokers.github.io/tws-api/classIBApi_1_1EClient.html and search for "timezone".
