### ISSUE TITLE
Wrong price data on bars.updateEvent += onBarUpdate function at minute 0.

### ISSUE THREAD

**Issue by vvd-vdw187** [erdewit/ib_insync#482]
With the bars.updateEvent += onBarUpdate, the data at minute 0 is all the same. I'm making the requests on ES, globex, 1 minute timeframe with WhattoShow as MIDPOINT. See the difference between the first and second 11:26 for the issue.
![bar update issue](https://user-images.githubusercontent.com/64206426/173544892-7ce8b486-f0f9-4d64-9e10-f9b4bdb403cd.PNG)

**Comment by erdewit** [comment]
The last bar is still forming and is not necessarily finished yet.
