### ISSUE TITLE
Question/Suggestion: Is it possible to pass more than one parameter for "whatToShow" ?

### ISSUE THREAD

**Issue by WoodWorker49** [erdewit/ib_insync#488]
Hello @erdewit ,

First of all, thank you for this amazing project. I am using IB_Insync to pull historical stock data (bid, ask, midpoint), however I have to do it in two steps for now:
- Fetching bid/ask first
- Then, polling midpoint

Is there a way to enhance the request, by allowing more than one string param at one time? Example, using an array?

One idea/suggestion I have is as follows:

From

```
bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='2 D',
    barSizeSetting='1 min', whatToShow='BID_ASK', useRTH=True)

bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='2 D',
    barSizeSetting='1 min', whatToShow='MIDPOINT', useRTH=True)
```

To

```
bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='2 D',
    barSizeSetting='1 min', whatToShow=['BID_ASK', 'MIDPOINT'], useRTH=True)
```

Thanks :)

**Comment by mattsta** [comment]
A couple points:

ib_insync is a nice wrapper around the IBKR API itself, so features and interfaces are all defined by [the actual underlying IBKR API](https://interactivebrokers.github.io/tws-api/historical_bars.html) (and it doesn't support multiple `whatToShow` fetches at once (plus they have really restrictive rate limits for various data combinations)).

also, fetching `MIDPOINT` _and_ `BID_ASK` seems redundant? You could get a usable `MIDPOINT` by averaging [`Open` and `Close` of the `BID_ASK` results](https://interactivebrokers.github.io/tws-api/historical_bars.html#hd_what_to_show).

**Comment by WoodWorker49** [comment]
Hello @mattsta,

Thanks a lot for your reply, understood! :-)

Yes, fully redundant and doesn't make sense indeed. I didn't select the right example...

Thanks again!
