### ISSUE TITLE
TypeError: onError() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by AfroMetal** [erdewit/ib_insync#49]
Using `Watchdog` caused this error to show in logs. 

I think that it may be related to:

> - Errors and warnings will now log the contract they apply to
> - IB error() callback signature changed to include contract

```
Traceback (most recent call last):
  File "(...)/venv/lib/python3.6/site-packages/ib_insync/wrapper.py", line 129, in _handleEvent
    cb(*args)
TypeError: onError() takes 4 positional arguments but 5 were given
```

**Comment by erdewit** [comment]
Thanks for the bug report, it is indeed a problem with the new error signature. This has been fixed in v0.9.4.
