### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by giphoneix** [erdewit/ib_insync#492]
When I use IBC, show these warning on macOS 12.4. Can somebody tell me how to fix it? Or is it ibcAlpha/IBC's issue? Thanks.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by feature.search.recorder.JtsMultiLookAndFeel (file:/XXX/jars/twslaunch-1012.jar) to method javax.swing.UIManager.getLAFState()
WARNING: Please consider reporting this to the maintainers of feature.search.recorder.JtsMultiLookAndFeel
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Warning: Nashorn engine is planned to be removed from a future JDK release
Warning: Nashorn engine is planned to be removed from a future JDK release

**Comment by m12t** [comment]
What is certain is that it's not an ib insync error. It has to do with Java. Last I recall IBC uses some Java so it could be coming from there, although the warning log specifies `file:/XXX/jars/twslaunch-1012.jar` which is a TWS jar file. It could be either of those two. Good luck, but please close this issue as it isn't an ib insync issue :)

**Comment by giphoneix** [comment]
Ok, thanks for the answer.
