### ISSUE TITLE
Installation from pip is different from git clone

### ISSUE THREAD

**Issue by zdytch** [erdewit/ib_insync#493]
I try to use `reqHistoricalSchedule()` method from version from pip install, and there is no such method in `ib.py` file. If I clone ib_insync from master and compare it to pip version, there are a lot of differences over the files, some of them:

reqHistoricalSchedule()
reqSmartComponents()
class HistoricalSession
class HistoricalSchedule

and lots of minor changes.

At the same time, `version.py` file for both versions contain `__version_info__ = (0, 9, 70)`

**Comment by erdewit** [comment]
I'll try to put out a new release shortly.

**Comment by erdewit** [comment]
v0.9.71 has just been released.
