### ISSUE TITLE
[Query] does IB HistoricalTickLast time support millisecond?

### ISSUE THREAD

**Issue by pg-adm1n** [erdewit/ib_insync#496]
[Query] does IB HistoricalTickLast time support millisecond? I had used the ib_insync reqHistoricalTicks to download the ticks data, and noticed that the dt only have the second level instead of millisecond, so I'm curious that IB HistoricalTickLast time support millisecond.
https://github.com/erdewit/ib_insync/blob/1de6ba9929aad46cad06f49aa12cc913925373e3/ib_insync/decoder.py#L760
https://interactivebrokers.github.io/tws-api/classIBApi_1_1HistoricalTickLast.html#a497c7f74ae405bfbf2e7b726bed211c6

Thanks.

**Comment by erdewit** [comment]
It's 1 second resolution for historical ticks, unfortunately.
