### ISSUE TITLE
Last row of data not delivered properly through onBarUpdate event 

### ISSUE THREAD

**Issue by wolfcuring** [erdewit/ib_insync#500]
Hi erdewit, 
Appreciate your great work for the ib api community. As I am trying to retrieve the last bar update for plotting purpose with bokeh, I encountered some unexpected results. The last bar is alright if check it with bars[-1], but not so, if I get it through onBarUpdate event. Here is the code:

`
from ib_insync import *
import random 

util.startLoop() 

id = random.randint(0,9999) 

ib = IB()
ib.connect('127.0.0.1', 7496, clientId=id, timeout=0)

contract = Future(symbol='MES',
                  localSymbol='MESU2',
                  exchange='GLOBEX',
                  multiplier='5',
                  currency='USD',
                  )

ib.qualifyContracts(contract)

bars = ib.reqHistoricalData(
        contract,
        endDateTime='',
        durationStr='1 W',
        barSizeSetting='1 min',
        whatToShow='MIDPOINT',
        useRTH=False,
        formatDate=1,
        keepUpToDate=True,       # So, this is real time 
        timeout= 60,
        )

def onBarUpdate(bars, hasNewBar):    
    if hasNewBar:                   
        print(bars[-1])

`
The bars delivered are all having same value with open, high, low close, like this:

`
BarData(date=datetime.datetime(2022, 9, 2, 8, 48), open=3979.125, high=3979.125, low=3979.125, close=3979.125, volume=-1, average=-1.0, barCount=-1)
BarData(date=datetime.datetime(2022, 9, 2, 8, 49), open=3984.625, high=3984.625, low=3984.625, close=3984.625, volume=-1, average=-1.0, barCount=-1)
BarData(date=datetime.datetime(2022, 9, 2, 8, 50), open=3985.875, high=3985.875, low=3985.875, close=3985.875, volume=-1, average=-1.0, barCount=-1)
BarData(date=datetime.datetime(2022, 9, 2, 8, 51), open=3987.875, high=3987.875, low=3987.875, close=3987.875, volume=-1, average=-1.0, barCount=-1)
BarData(date=datetime.datetime(2022, 9, 2, 8, 52), open=3990.125, high=3990.125, low=3990.125, close=3990.125, volume=-1, average=-1.0, barCount=-1)
`
I am not sure why this is happening.

**Comment by mattsta** [comment]
In your sample output all the values change with each line, so it looks like it works?

In your `onBarUpdate` callback you can also remove bars after processing so the list doesn't grow forever. Just add a `bars.clear()` at the end of the event so you can process all bars each time the event triggers.

**Comment by wolfcuring** [comment]
> In your sample output all the values change with each line, so it looks like it works?
> 
> In your `onBarUpdate` callback you can also remove bars after processing so the list doesn't grow forever. Just add a `bars.clear()` at the end of the event so you can process all bars each time the event triggers.

Well, yes the value changed every line, but does not match with bars[-1]. During that time, ohlc values changed a lot which can be seen on the TWS chart.

**Comment by erdewit** [comment]
```
if hasNewBar:
  print(bars[-1])

`
The bars delivered are all having same value with open, high, low close
```

When a new bar is added, the new bar at ``bars[-1]`` is just starting. Use bars[-2] for the last **completed** bar.
