### ISSUE TITLE
unable to modify order 

### ISSUE THREAD

**Issue by sudheer628** [erdewit/ib_insync#501]
i am using below to create a order first and then i have changed the limit price triggered the order , it places a new order instead of modifying the order. is there a way to mention orderId in subsequent order modification requests? 

places an order with limit price 60
```
from ib_insync import *
contract = Contract(secType='OPT', localSymbol='NIFTY2290817700CE', exchange='NSE', currency='INR')
order = LimitOrder( 'BUY', 50.0 , 60)
x = IB()
x.connect('127.0.0.1', 7496, clientId=1)
print(x.placeOrder(contract=contract, order=order))
```

Now i have triggered the same with new limit price -70

```
from ib_insync import *
contract = Contract(secType='OPT', localSymbol='NIFTY2290817700CE', exchange='NSE', currency='INR')
order = LimitOrder( 'BUY', 50.0 , 70)
x = IB()
x.connect('127.0.0.1', 7496, clientId=1)
print(x.placeOrder( contract=contract, order=order))
```

it placed a new order on the same security with new limit price instead of modifying the existing one.

Kindly help.

**Comment by mattsta** [comment]
You're generating a completely new order there, so it does what you're asking.

You need to modify an existing order then re-submit using the original order metadata instead of creating a new order.

So, something like:

```python
trades = ib.openTrades()

for trade in trades:
    if trade.contract.localSymbol == "NIFTY2290817700CE": # note: the formatting of .localSymbol may be different, so it's better to enumerate them and pick visually sometimes.
        trade.order.lmtPrice = 70
        newTrade = ib.placeOrder(trade.contract, trade.order)
        print("Updated:", newTrade)
```

**Comment by erdewit** [comment]
``>         updatedOrder = dataclasses.replace(trade.order)``

This makes a copy of ``trade.order``. This can be confusing as ``trade.order`` will still refer to the old unmodified order, which is why you still get the old limit price in your output. If you look carefully in TWS you will find that the order has been modified successfully though.

To avoid the confusion it's preferable to modify ``trade.order.lmtPrice`` directly and resubmit ``trade.order``.

**Comment by mattsta** [comment]
The reason for copying `trade.order` is because if we directly modify `trade.order`, then the results from `.openTrades()` and `.openOrders()` is modified locally without being the actual IBKR server state anymore (example: maybe there's an error or an exception between the local order modification and actual IBKR submission, or the submission gets rejected by IBKR, but then the local state is wrong forever and doesn't have a way to "revert" back to a known-good state).

Ideally the internal trade objects would be immutable and only updated by server callbacks.

**Comment by erdewit** [comment]
You're right Matt. The old ``trade.order`` will be updated by the ``openOrder`` callback, if some time for it is allowed.

For example with ``ib.sleep(1)`` after the placeOrder.

**Comment by sudheer628** [comment]
Hi, Thanks again,, I tried this but now i am getting error 321 from IBKR.

```
trades = ib.openTrades()
for trade in trades:
    if trade.contract.localSymbol == "NIFTY2290817600PE":
        trade.order.lmtPrice = 60 # also tried 60.0 , '60.0'
        updatedOrder = dataclasses.replace(trade.order)
        newTrade = ib.placeOrder(trade.contract, updatedOrder)
        ib.sleep(1)
        print("Updated:", newTrade)
```

response:

`Updated: Trade(contract=Option(conId=572126439, symbol='NIFTY50', lastTradeDateOrContractMonth='20220908', strike=17600.0, right='P', multiplier='1', exchange='NSE', currency='INR', localSymbol='NIFTY2290817600PE', tradingClass='NIFTY'), order=Order(orderId=24, clientId=1, permId=73920343, action='BUY', totalQuantity=50.0, orderType='LMT', lmtPrice=60, auxPrice=0.0, tif='DAY', ocaType=3, displaySize=2147483647, trailStopPrice=56.0, volatility=18.13, volatilityType=2, deltaNeutralOrderType='None', referencePriceType=0, account='xxxxxxxx', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=24, status='Cancelled', filled=0.0, remaining=50.0, avgFillPrice=0.0, permId=73920343, parentId=0, lastFillPrice=0.0, clientId=1, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(time=datetime.datetime(2022, 9, 7, 9, 43, 48, 285725, tzinfo=datetime.timezone.utc), status='Submitted', message='', errorCode=0), TradeLogEntry(time=datetime.datetime(2022, 9, 7, 9, 43, 48, 351689, tzinfo=datetime.timezone.utc), status='Submitted', message='Modify', errorCode=0), TradeLogEntry(time=datetime.datetime(2022, 9, 7, 9, 43, 48, 357265, tzinfo=datetime.timezone.utc), status='Cancelled', message="**Error 321, reqId 24: Error validating request.-'bN' : cause - VOL order requires non-negative floating point value for volatility.  Do not set it for other order types.", errorCode=321)], advancedError=**'')
`

**Comment by erdewit** [comment]
Yes that is classic IB. Any field that IB complains about can be set to it's default value, like 
```
order.volatility = util.UNSET_DOUBLE
```
It is so weird that they fill order fields that they themselves then reject.

It is also possible to create a new order in the same way the original order was created and then setting the existing ``orderId``.

**Comment by mattsta** [comment]
Just realized another example why duplicating orders helps more than changing openTrades() directly: when modifying orders after hours, we submit the new order, but IBKR sets the updated order state to "(PreSubmitted, Modify)," so don't know if the change is actually accepted until IBKR's market submission time happens (could even be days later if a modification is submitted after-hours Friday for a Monday open).

If we modify an order attached to a live open trade directly with assignment, the local state gets temporarily updated (or until we restart and it reloads live data again) then we have a false view of current limit order / quantity versus what IBKR still holds in the trading system until it submits the next update.

Though, this also means an order's updated limit price can't be viewed until the market opens so we have no record of what the updated order _will_ be when submitted again (so if we have limit order at $3, and we updated it to $2 after hours, the `openTrades()` order will never show the modified $2 price until the order is re-submitted at market open... we either have to just remember or record it in another database locally as some "pending modification queue price updates").
