### ISSUE TITLE
live PNL on account. 

### ISSUE THREAD

**Issue by raph1900** [erdewit/ib_insync#513]
Hey. I am trying to have live PNL using `ib.reqPnl` and `ib.pnl` but it seems that its updating every minute and not live as in TWS.
What are the options? 
Am I doing something wrong?
Thanks !

**Comment by mattsta** [comment]
I think this is just another weird IBKR API limitation. The account `DailyPnL` doesn't update with every market trade (much like how the per-position `marketPrice` also only updates every 30-180 seconds).

Though, for some reason the account `UnrealizedPnL` field does track much faster than the other fields.

Their [official docs say](https://interactivebrokers.github.io/tws-api/pnl.html#account_window_pnl):

>  In particular, the unrealized P&L information shown in the TWS Account Window which is sent to updatePortfolioValue will update either (1) when a trade for that particular instrument occurs or (2) every 3 minutes.

> It is important to keep in mind that the P&L data shown in the Account Window and Portfolio Window will sometimes differ because there is a different source of information and a different reset schedule.
