### ISSUE TITLE
Futures for S&P 500

### ISSUE THREAD

**Issue by piotrgolawski** [erdewit/ib_insync#514]
Hi guys, I am performing 
```     contract = Future('ES', '202212', 'GLOBEX')
    bars = ib.reqHistoricalData(
        contract=contract,
        endDateTime='',
        durationStr='2 Y',
        barSizeSetting='1 day',
        whatToShow='TRADES',
        useRTH=False,
        formatDate=1,
        keepUpToDate=False,
        chartOptions=[]
    )

And receiving "Error 162, reqId 3: Historical Market Data Service error message:No market data permissions for GLOBEX FUT, contract: Future(symbol='ES', lastTradeDateOrContractMonth='202212', exchange='GLOBEX')" 
    
    I have subscribed for global -> CUSIP but nothing have changed.
    
    My goal is to fetch history and live data for S&P 500, could you please help me?

**Comment by zdytch** [comment]
You need to subscribe to "CME Real-Time" in order to fetch ES data

This is not related to ib_insync

**Comment by piotrgolawski** [comment]
Are you sure this is this one? It cost 123$ / month!

**Comment by zdytch** [comment]
I use it myself, so I'm sure. It costs $1.25/mo, please check the market subscription prices from the "User settings" page:
https://take.ms/rX05Y

**Comment by piotrgolawski** [comment]
https://ibb.co/rsvcPNf Is it this?

**Comment by zdytch** [comment]
Level 1 (enough to get historical data) costs $1.25 for me: https://take.ms/c7tXr
Level 1 and Level 2 subscription costs $11: https://take.ms/TJmqBZ

Maybe you are qualified as a professional, so the prices are higher for you

**Comment by piotrgolawski** [comment]
Yeah, you are right! I had changed that for now. Thanks for help
