### ISSUE TITLE
Borrow rate

### ISSUE THREAD

**Issue by dmoklaf** [erdewit/ib_insync#515]
Borrow rate (for shorting shares) is available in the undocumented IB API, through generic tick 499:
https://groups.io/g/twsapi/topic/28217344#41103

This is how TWS manages to display borrow rates in the live UI.

However this generic tick; althought stable, is not documented officially by IB yet. Consequently, it is not available in ib_insync, despite being very vital for shorting strategies.

Is ib_insync's intent to stick 100% to the documented part of the API, or is it possible today to push a PR that would integrate these 2 new fields into the Ticker (fee rate and borrow rate)? In such case I can propose a pull request.

**Comment by erdewit** [comment]
Sure a PR is welcome.

**Comment by dmoklaf** [comment]
I am testing the patch, which includes both tiny code changes and the documentation update in the `reqMktData` docstring. How do I test the later? I have tried regenerating the Sphinx doc with `make html` in the `docs` directory but it keeps generating the old documentation (my docstring change is not reflected in the HTML documentation). A cursory look at the make targets didn't allow me to identify which command I have missed to regenerate it entirely (I am no Sphinx expert).

**Comment by erdewit** [comment]
``make html`` should have done it, with the new docs in the ``html`` subdir. The ``html`` subdir can be removed to make sure it's regenerated.

If it doesn't work you can commit without testing that.

**Comment by dmoklaf** [comment]
Ok I will probably commit Monday or Tuesday once all my tests are green.

**Comment by dmoklaf** [comment]
Early tests indicate that the generic tick 499 is not supported through the IBGateway API - the entire subscription (including requests for other generic ticks) becomes ignored by the IB server, whereas the subscription is fine if not including this generic tick. Maybe IB has removed these 2 fields (fee rate, rebate rate) from its API - in a recent release note IB has indicated having removed the rebate rate from TWS, but not the fee rate yet. Closing this ticket without a resolution
