### ISSUE TITLE
not getting any events triggered with release 0.9.72 

### ISSUE THREAD

**Issue by nurettin** [erdewit/ib_insync#522]
Hi, 

With the release 0.9.72, my program doesn't trigger any events anymore. 
I made a small program just doing a reqPnL, but I couldn't reproduce the issue.
For now, I just downgraded to 0.9.71

These are the events my program subscribes to:
```
        self.ib.disconnectedEvent += self.on_ib_disconnected
        self.ib.connectedEvent += self.on_ib_connected
        self.ib.barUpdateEvent += self.on_bar_update
        self.ib.orderStatusEvent += self.on_order_status
        self.ib.commissionReportEvent += self.on_commission_report
        self.ib.execDetailsEvent += self.on_execution_details
        self.ib.newOrderEvent += self.on_new_order
        self.ib.errorEvent += self.on_error
        self.ib.pnlEvent += self.on_pnl
        self.ib.accountSummaryEvent += self.on_account_summary
        self.ib.timeoutEvent += self.on_timeout
```
and I just use `ib.run()` to start the forever loop. 
there are no asyncio shenanigans in my code, either.

I will do some more tests next week if I find the time.

**Comment by erdewit** [comment]
Probably was something with the IB servers at the time.
