### ISSUE TITLE
API messages in Client tab in IB Gateway

### ISSUE THREAD

**Issue by cca32** [erdewit/ib_insync#526]
Love how easy it was to set this up and get it running. Incredibly well documented and super awesome package.

I do have a question regarding API messages in the Client tab in IB Gateway. After I create the `ib = ib_insync.IB()` object and connect, even if I make no other types of requests, I see API messages regarding net liquidation and other detailed information. Is there something I'm misunderstanding here? 

I hate to assume the worst, but this does not seem very reassuring. Thanks!

**Comment by erdewit** [comment]
This is part of the normal synchronization upon connecting.
