### ISSUE TITLE
Timeout when connecting from wsl2 to windows-based TWS

### ISSUE THREAD

**Issue by yarimiz** [erdewit/ib_insync#529]
I've been facing an issue where a connection between a code that runs in WSL2 (ubuntu 22.04) and a TWS running on Windows 10 is disconnected due to timeout.

Connecting to the same TWS using the same code but directly from Windows (without WSL) works flawlessly.

In TWS settings, I have enabled connections from 172.18.240.1.

Log is as follows
```
2022-11-21 19:24:14,360 ib_insync.client INFO Connecting to 172.18.240.1:7496 with clientId 999...
2022-11-21 19:24:14,362 ib_insync.client INFO Connected
2022-11-21 19:24:18,363 ib_insync.client INFO Disconnecting
2022-11-21 19:24:18,364 ib_insync.client ERROR API connection failed: TimeoutError()
```

**Comment by atakanokan** [comment]
This stackoverflow page has more information on how to access Windows host from within WSL2: https://superuser.com/questions/1679757/how-to-access-windows-localhost-from-wsl2 

Same result as the accepted answer states: the `ping` command doesn't work but the `nc` command does. 
```
 ~$ ping "$(hostname).local"
PING  (172.28.208.1) 56(84) bytes of data.
^C
--- ping statistics ---
58 packets transmitted, 0 received, 100% packet loss, time 59242ms

~$ nc -zv "$(hostname).local" 7496
Connection to XXX.local (172.28.208.1) 7496 port [tcp/*] succeeded!
```

**Comment by ben1628** [comment]
In case anybody is still looking for a solution on this, after google this for a while and try multiple solutions, this is the solution that seem to work

https://learn.microsoft.com/en-us/windows/wsl/networking

So basically:

Obtain the IP address of your host machine by running this command from your Linux distribution: cat /etc/resolv.conf
Copy the IP address following the term: nameserver.
Connect to any Windows server using the copied IP address.

and then you just use that IP Address for 

ib.connect('<nameserver IP> ', 749, clientId=1)

**Comment by sean-silverpine** [comment]
@ben1628 I'm having the same issue and I followed your steps. I'm using the nameserver address from `resolv.conf` and I've added the two IP addresses from `ip route` in the IB API trusted IPs. I restarted TWS and retried many times and I continue to get the TimeoutError.
```
2023-01-19 21:03:53,434 ib_insync.client INFO Connecting to 172.21.240.1:7497 with clientId 1...
2023-01-19 21:03:53,434 ib_insync.client INFO Connected
2023-01-19 21:03:57,438 ib_insync.client INFO Disconnecting
2023-01-19 21:03:57,439 ib_insync.client ERROR API connection failed: TimeoutError()
2023-01-19 21:03:57,439 ib_insync.client INFO Disconnected.
```
Was there any other step that helped you find a solution?

**Comment by sean-silverpine** [comment]
@ben1628 , No, I've tried many times with your steps and I continue to get the TimeoutError after getting connected. It seems that TWS is not allowing the connection. I've checked the trusted IPs against the values in IP route many times. Any other ideas?

**Comment by ben1628** [comment]
Try this:Add 127.0.0.1 as trusted IP in TWS and then ib.connect(127.0.0.1)

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nick-reinstein** [comment]
I am also getting TimeoutError after putting the xxx stuff in the code and the yyy stuff in TWS, i have tried with 127.0.0.1 and the result from "ip route".
