### ISSUE TITLE
Time notation change

### ISSUE THREAD

**Issue by stock888777** [erdewit/ib_insync#530]
IB is going to change the time notation.
Please read this. https://groups.io/g/twsapi/topic/adding_timezone_to_request/93271054

I have not confirmed that it works, but I think formatIBDatetime needs to be changed this way.

```Python
def formatIBDatetime(dt: Union[date, datetime, str, None]) -> str:
    """Format date or datetime to string that IB uses."""
    if not dt:
        s = ''
    elif isinstance(dt, datetime):
        # convert to UTC timezone
        dt = dt.astimezone(tz=timezone.utc)
        s = dt.strftime('%Y%m%d-%H:%M:%S UTC')
    elif isinstance(dt, date):
        dt = datetime(dt.year, dt.month, dt.day, 23, 59, 59).astimezone(tz=timezone.utc)
        s = dt.strftime('%Y%m%d-%H:%M:%S UTC')
    else:
        s = dt
    return s
```

**Comment by john9631** [comment]
Change `-` to space in the data format and you have something that no longer attracts the warning.

`
def formatIBDatetime(dt: Union[date, datetime, str, None]) -> str:
    """Format date or datetime to string that IB uses."""
    if not dt:
        s = ''
    elif isinstance(dt, datetime):
        # convert to UTC timezone
        dt = dt.astimezone(tz=timezone.utc)
        s = dt.strftime('%Y%m%d %H:%M:%S UTC')
    elif isinstance(dt, date):
        dt = datetime(dt.year, dt.month, dt.day, 23, 59, 59).astimezone(tz=timezone.utc)
        s = dt.strftime('%Y%m%d %H:%M:%S UTC')
    else:
        s = dt
    return s
`

Tested collecting historical and 5 second data from fx + hk futures in Australian timezone.

**Comment by stock888777** [comment]
I'm sorry. I didn't read the text and properly.

> The preferred format going forward is "yyyymmddd hh:mm:ss TZ" (e.g. a space separates date and time) with an explicit time zone identifier appended to the date and time string

Dash should be removed.

**Comment by erdewit** [comment]
Thanks for the heads-up about this change. It is available now in v0.9.78.

**Comment by stock888777** [comment]
Thank you.

**Comment by john9631** [comment]
Just a note that people using the new versions may run into issues if they compare tz aware datetime objects with tz unaware objects.  If you have this problem I suggest using this method to remove tz awareness for the comparison:  

`datetime.datetimeobject.replace(tzinfo=None)`

So when comparing the bar's date which was time zone aware with my last_datetime object I changed

`if b.date <= self.last_datetime:`
to
`if b.date.replace(tzinfo=None) <= self.last_datetime:`
