### ISSUE TITLE
Why does ib_insync require market data subscription when standard ibapi client doesn't?

### ISSUE THREAD

**Issue by carera** [erdewit/ib_insync#535]
Hello, I am trying to replace `ibapi` client provided by IBKR with your ib_insync library, and similarly to #461 , #514 , #234 , #19 - ib_insync shouts at me that I have no market data permissions.
What is different in `ib_insync.reqHistoricalData` vs `ibapi.reqHistoricalData` ? The standard `ibapi` client allows me to access historical data without additional subscription.

**Comment by erdewit** [comment]
There's no difference.
