### ISSUE TITLE
Are positions rounded to closest int?

### ISSUE THREAD

**Issue by fredmontet** [erdewit/ib_insync#538]
I would like to get the positions I have in my portfolio. When I look on IB, I see fractional values of positions (e.g. `1.4`) and when I get the Position object from IB insync, I obtain rounded float (e.g. `1.0`).

Is this issue known? How to deal with it?

**Comment by erdewit** [comment]
There is no rounding done by ib_insync for the position size. The introduction of fractional shares has not been a smooth one for IB, perhaps the problems are fixed in a newer TWS version.

**Comment by fredmontet** [comment]
Thanks for your quick answer!
