### ISSUE TITLE
contract description specified for KWEB is ambiguous

### ISSUE THREAD

**Issue by edwardhuanghz** [erdewit/ib_insync#539]
from ib_insync import *
#util.startLoop()

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=123)

def getMktData(symbol): 
    contract = Stock(symbol, 'SMART', 'USD')
    bars = ib.reqHistoricalData(
                   contract,
                   endDateTime='',
                   durationStr='3 M',
                   barSizeSetting='10 mins',
                   whatToShow='TRADES',
                   useRTH=True,
                   formatDate=1)
    df = util.df(bars)
    return df

rst=getMktData('KWEB')

# output

 The contract description specified for KWEB is ambiguous., contract: Stock(symbol='KWEB', exchange='SMART', currency='USD')

**Comment by jlixfeld** [comment]
```python
contract = ib.reqContractDetails(Stock(symbol, 'SMART', 'USD'))
print(contract)
```
