### ISSUE TITLE
Can't comunicate with the gateway from remote host

### ISSUE THREAD

**Issue by AmitKehat** [erdewit/ib_insync#540]
Hello,
I am runng the gateway on a server.
I added in the gateway settings the remote IP of the client machine I want to operate from.

In the client machine I am trying to run ib_insync and connect to gateway:

```
import ib_insync

ib = ib_insync.IB()
ib.connect('<SERVER_HOST>', 4001, clientId=10)

```

```
The output I am getting is:
API connection failed: TimeoutError() Traceback (most recent call last): File ".\ib_insinc_test.py", line 4, in <module> ib.connect('<SERVER_HOST>', 4001, clientId=10) File "C:\Users\amitk\Documents\repositories\easyib\venv\lib\site-packages\ib_insync\ib.py", line 269, in connect return self._run(self.connectAsync( File "C:\Users\amitk\Documents\repositories\easyib\venv\lib\site-packages\ib_insync\ib.py", line 308, in _run return util.run(*awaitables, timeout=self.RequestTimeout) File "C:\Users\amitk\Documents\repositories\easyib\venv\lib\site-packages\ib_insync\util.py", line 341, in run result = loop.run_until_complete(task) File "C:\Users\amitk\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete return future.result() File "C:\Users\amitk\Documents\repositories\easyib\venv\lib\site-packages\ib_insync\ib.py", line 1674, in connectAsync await self.client.connectAsync(host, port, clientId, timeout) File "C:\Users\amitk\Documents\repositories\easyib\venv\lib\site-packages\ib_insync\client.py", line 211, in connectAsync await asyncio.wait_for(self.conn.connectAsync(host, port), timeout) File "C:\Users\amitk\anaconda3\lib\asyncio\tasks.py", line 490, in wait_for raise exceptions.TimeoutError() asyncio.exceptions.TimeoutError 
```
(I replaced my real server IP with: <SERVER_HOST>)

Any idea how can I overcome this issue?

Thanks,
Amit

**Comment by ben1628** [comment]
Try this, may be it will help

https://github.com/erdewit/ib_insync/issues/529#issuecomment-1397255851

or tell me what O/S you are using and where is your ibgateway located

**Comment by AmitKehat** [comment]
Hi erdewit, thanks for your email.

I am actually looking for doing the opposite thing.
I want to run the gateway on a remote server with Ubuntu OS and implement
my code on my local Win 10 OS machine.
I am getting timeout from ib_insync when trying to communicate with the
gateway…
I don’t have enough knowledge regarding what can block the accesses between
my local machine and the remote machine…
Any idea / knowledge you can share with me about this will be greatly
appreciated.

Thanks,
Amit

**Comment by ben1628** [comment]
I'm Ben1628, not erdewit... lol

You need to provide more detail about your setup, are you running wsl2? What GUI are you using to host ibgatway in Ubuntu?  Are you able to see the typical ibgateway window?  How do you access ibgateway from windows 10?

If you are using  wsl2, try to following the microsoft link I provided, basically localhost will suffice.

If that doesn't  work, then try the opposite.  i.e. xxx.xx.xxx.x on ibgateway in linux and yyy.yyy.yyy.y on ib.connect(...)

What we are trying to do here is find out the ip address of Ubuntu OS and windows 10 and go from there.
