### ISSUE TITLE
small typo in docu

### ISSUE THREAD

**Issue by laroche** [erdewit/ib_insync#541]
Mini-docu fixup:

<pre>
--- a/docs/recipes.rst
+++ b/docs/recipes.rst
@@ -52,7 +52,7 @@ Scanner data (blocking)
 
 .. code-block:: python
 
-    allParams = ib.reqScannerParameters())
+    allParams = ib.reqScannerParameters()
     print(allParams)
 
     sub = ScannerSubscription(
</pre>

Thanks a lot for ib_insync development,
best regards,

Florian La  Roche

**Comment by erdewit** [comment]
Thanks for noticing, I will update the documentation.
