### ISSUE TITLE
All Contracts have same conId

### ISSUE THREAD

**Issue by piotrgolawski** [erdewit/ib_insync#543]
Hello,
Each time I am creating new contract and qualifying them, they have same conId which make impossible calculation loss and profits based on same contract Id

contract CFD(conId=111767871, symbol='IBUS500', exchange='SMART', currency='USD', localSymbol='IBUS500', tradingClass='IBUS500')

**Comment by erdewit** [comment]
From your previous bug report I assume you mean with a pnlSingle subscription. As the name implies this is for a subscription to a single position only,  multiple positions require multiple pnlSingle subscriptions.

**Comment by erdewit** [comment]
If you're saying multiple different contracts have the same conId then give an example of that.

**Comment by piotrgolawski** [comment]
[https://ibb.co/Fsy5t4X](url)

[https://ibb.co/Fsy5t4X](url)

I do not have trades for today, but it comes back in trades as it is here

**Comment by erdewit** [comment]
If you create all CFD contracts with the same name they will all be the same contract...

**Comment by piotrgolawski** [comment]
So all contracts made for CFD IBUS500 will have the same id?
Ok, thank you for the info, it is not intuitive for me tho.

Could you please tell me what is a proper way to connect buy and sell transaction, or it is not a good idea?

Anyway, I am looking for a way, to calculate profit or loss for single transaction. 

reqPnLSingle / reqPnL / reqPositions - returns only conId, so it gives me nothing, because all of my conId are the same

The only Id which is in the commissionReport and in the trade is execId, so I can connect it by that.
But then in trade I have fills, so I bet they are updates to the trade. Do it make sense to use only the last one, or they should be merged somehow.

If you think this is too much to answer, I can pay you for consultation if you are open to that.
Anyway, thank you for help!

**Comment by erdewit** [comment]
> Could you please tell me what is a proper way to connect buy and sell transaction, or it is not a good idea?

You can set ``order.orderRef`` with your own unique ID for the entry and exit order and then later tie them together.

**Comment by piotrgolawski** [comment]
So I see this is also the way to connecting it with commission in trade.

But then in trade I have fills, so I bet they are updates to the trade. Do it make sense to use only the last one, or they should be merged somehow. How to decide if the fill will be the last? They have same status.
