### ISSUE TITLE
reqAllOpenOrdersAsync does not return contract details with order

### ISSUE THREAD

**Issue by Goober68** [erdewit/ib_insync#545]
In wrapper.openOrder, somewhere around line 382, I believe that the object appended to the results - results.append(order) should be results.append(trade) so that the client receives the contract and order information in the results order set.  Otherwise the receiver will get only the naked order information without any symbol or market details.  Makes the reqAllOpenOrdersAsync almost useless.

**Comment by erdewit** [comment]
I agree, thanks for bringing this up.
