### ISSUE TITLE
IBC Watchdog - Support for new IBC restart command

### ISSUE THREAD

**Issue by Plumakeem** [erdewit/ib_insync#546]
TWS/IBG introduced a few versions ago a new feature to only reset the auth information on Sundays keeping logged in for a whole week. IBC now added the option to soft restart TWS/IBG by keeping the auth. On windows this can be used in python by the following code:
```
import telnetlib

HOST = "127.0.0.1"
PORT = "1234" #port defined for the command server in the config.ini

tn = telnetlib.Telnet(HOST, port=PORT)

tn.write("RESTART".encode('ascii') + b"\n")
```
(Can't test on linux).

I'd like to discuss in this "Issue" whether this new function should be introduced in the watchdog as the default restart on error method (unless it is a Sunday).

**Comment by erdewit** [comment]
It's not in the planning to add communication with the IBC command server.
