### ISSUE TITLE
Historical Market Data Service error message:HMDS query returned no data

### ISSUE THREAD

**Issue by gooner22** [erdewit/ib_insync#550]
Hi,

I have question with regards to historical data pagination and approach described in the documentation
[Fetching consecutive historical data ](https://ib-insync.readthedocs.io/recipes.html#fetching-consecutive-historical-data)

**Steps to reproduce**:
run [sample code ](https://ib-insync.readthedocs.io/recipes.html#fetching-consecutive-historical-data) with params :

durationStr='1 D',
barSizeSetting='1 min', 
whatToShow='TRADES', 
useRTH=False, 
contract = Stock('T', 'SMART', 'USD')

**Output**:
```
2023-01-31 09:16:00
2023-01-30 09:00:00
2023-01-27 09:00:00
2023-01-26 09:00:00
2023-01-25 09:06:00
2023-01-24 09:10:00
2023-01-23 12:00:00
Error 162, reqId 10: Historical Market Data Service error message:HMDS query returned no data: T@SMART Trades, contract: Stock(symbol='T', exchange='SMART', currency='USD')
```

**Problem**
Normally, when paginating, previous page bar date points to somewhat start of trading day ~09:00 (UTC),
but for some symbols (T, DIA) first bar time appears to be few hours later ~12:00 (UTC), like in the log above.
In such cases, IB returns empty result for the next page request (from ~12:00 1D back) and pagination falls back.

For pagination itself,
I was able to workaround this by explicitly pointing next page request endDateTime to ~09:00 (UTC) same day
Afterwards, data stream seems to arrive properly. I've checked volumes and bar counts for problematic days.
```
head = bars[0].date
if duration == "1 D" and head.hour != 9:
    head = head.replace(minute=0, second=0, hour=9, microsecond=0)
endDateTime = head
```

my question is how to handle such cases properly?
maybe someone can suggest better solution

P.S. thank you for the great framework @erdewit

**Comment by erdewit** [comment]
This is probably a timezone issue. You can try with ``formatDate=2`` in the request to make sure that UTC timezone is used throughout.

**Comment by gooner22** [comment]
I am using UTC in gateway, thanks anyway
