### ISSUE TITLE
Trades - TradeLogEntry Submitted Time Changes with Each Session For Same Trade and TradeLogEntry 

### ISSUE THREAD

**Issue by jakemdrew** [erdewit/ib_insync#551]
**Problem**
TradeLogEntry submitted entry timestamp changes for LMT and STP orders each time the kernel or session is restarted for the same exact trade and TradeLogEntry 

**Reproduce**

from ib_insync import *

util.startLoop() 

ib = IB()
ib.connect('127.0.0.1', 4002, 1)
ib.reqMarketDataType(marketDataType=3)

trades1 = ib.trades()

ib.disconnect()

# Code Restarts!

util.startLoop() 

ib = IB()
ib.connect('127.0.0.1', 4002, 1)
ib.reqMarketDataType(marketDataType=3)

trades2 = ib.trades()

**Output trades1**

Trade(contract=Stock(conId=265598, symbol='AAPL', right='?', exchange='SMART', currency='USD', localSymbol='AAPL', tradingClass='NMS'), order=Order(orderId=3165, clientId=1, permId=2130238219, action='SELL', totalQuantity=8.0, orderType='LMT', lmtPrice=150.19, auxPrice=0.0, tif='GTC', ocaGroup='2130238218', ocaType=3, displaySize=2147483647, outsideRth=True, rule80A='0', openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='XXXXX', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=3165, status='Submitted', filled=0.0, remaining=8.0, avgFillPrice=0.0, permId=2130238219, parentId=0, lastFillPrice=0.0, clientId=1, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(**time=datetime.datetime(2023, 2, 1, 21, 27, 6, 23195, tzinfo=datetime.timezone.utc**), status='Submitted', message='', errorCode=0)])

**Output trades2**

Trade(contract=Stock(conId=265598, symbol='AAPL', right='?', exchange='SMART', currency='USD', localSymbol='AAPL', tradingClass='NMS'), order=Order(orderId=3165, clientId=1, permId=2130238219, action='SELL', totalQuantity=8.0, orderType='LMT', lmtPrice=150.19, auxPrice=0.0, tif='GTC', ocaGroup='2130238218', ocaType=3, displaySize=2147483647, outsideRth=True, rule80A='0', openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='XXXXX', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=3165, status='Submitted', filled=0.0, remaining=8.0, avgFillPrice=0.0, permId=2130238219, parentId=0, lastFillPrice=0.0, clientId=1, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(**time=datetime.datetime(2023, 2, 1, 21, 27, 6, 236386, tzinfo=datetime.timezone.utc**), status='Submitted', message='', errorCode=0)])

**Comment by erdewit** [comment]
The small time difference is because of local vs server time. The preference is to use local time for live order executions. For past executions the IB server time is used. The relevant code is here:

https://github.com/erdewit/ib_insync/blob/886fb1a904fce963ccee6845e98aaed36cea4e4d/ib_insync/wrapper.py#L471
