### ISSUE TITLE
How to add Trailing Stop Order using ib_insync

### ISSUE THREAD

**Issue by MilindRCodes** [erdewit/ib_insync#560]
Hi All,

I am seeking assistance with respect to trailing stop order using ib_insync
I read some old threads related to it, but did not find any successful post on this.

Can you please post the trailing stop order code if you have been able to submit it successfully in TWS?

Thank you.

**Comment by jlixfeld** [comment]
It's more appropriate to ask those kinds of questions [here](https://groups.io/g/insync/topics)

**Comment by erdewit** [comment]
See the IB documentation here:

https://interactivebrokers.github.io/tws-api/basic_orders.html
