### ISSUE TITLE
util.df(bars) return error

### ISSUE THREAD

**Issue by rydeen7** [erdewit/ib_insync#568]
It might be dependent on my environment (M1 MacBook Air + python3.8),
util.df(bars) does not work correctly.
Did IB original API change their bar object?

**Comment by jlixfeld** [comment]
Works for me.

**Comment by August1328** [comment]
It works for me on Windows 10 and Python 3.10 but I updated Python and ib_insync in the last months and got errors with, I guess, util.df(bars). If you can give more details about the error or the traceback, I will try to help.

**Comment by rydeen7** [comment]
Dear all,
After all, I did clean install macOS, and made new environment with python3.9.
Then, I was able to call util.df.

So please ignore my former comment.
Thanks.

**Comment by erdewit** [comment]
It seems ``backports.zoneinfo`` was not installed.

**Comment by nick-reinstein** [comment]
It is not working for me.  I am using PyCharm 2022.2.5 (built Mar15, '23) and I installed ib_insync today.
Here is the error I am getting:

  File "C:\Users\nnrei\PycharmProjects\what_if\venv\lib\site-packages\pandas\core\arrays\datetimelike.py", line 415, in astype
    converted = ints_to_pydatetime(
  File "pandas\_libs\tslibs\vectorized.pyx", line 158, in pandas._libs.tslibs.vectorized.ints_to_pydatetime
  File "pandas\_libs\tslibs\timezones.pyx", line 266, in pandas._libs.tslibs.timezones.get_dst_info
AttributeError: 'NoneType' object has no attribute 'total_seconds'

**Comment by nick-reinstein** [comment]
Solved.  Here is a replacement for util.df() that seems to work for me based on results from b.reqHistoricalData():

# df = util.df(amzn_bars)

def deconstruct_bardata(bardata):
    data = []
    for bar in bardata:
        data.append({'open': bar.open,
                     'high': bar.high,
                     'low': bar.low,
                     'close': bar.close,
                     'volume': bar.volume,
                     'date': bar.date.strftime('%Y-%m-%d %H:%M:%S')})

    df = pd.DataFrame(data)
    return df

df = deconstruct_bardata(amzn_bars)
print(df)

**Comment by nick-reinstein** [comment]
There are other errors, I cannot get contract data either regardless of which underlying I try  SPY, AMZN, TSLA all produce the following error.  ChatGPT was unable to help although it provided 5 different wrong answers.

Is there a more stable recent version I should be using?

Or can someone message me and try to sort this out? I am exhausted trying to get this library to work.
