### ISSUE TITLE
Broken link in FlexReport docs

### ISSUE THREAD

**Issue by chrism2671** [erdewit/ib_insync#569]
I'm trying to get FlexReport to work. I see two main issues:

Both links in the documentation go to 404 pages- the first is a soft 404 (redirect to an irrelevant page):
-   https://guides.interactivebrokers.com/am/am/reports/flex_web_service_version_3.htm
-   https://guides.interactivebrokers.com/cp/cp.htm#am/reporting/flexqueries.htm
(link to code here: https://github.com/erdewit/ib_insync/blob/9e3aa191f394ecd049129cc2f0e2b81be0589ede/ib_insync/flexreport.py#L22)

The code necessitates a `token` field, but this token isn't referenced anywhere else in the code.

Here are the instructions for getting the token (thanks, ChatGPT!):

- Login to web portal
- Go to Settings
- Click on "Configure Flex Web Service"
- Generate token

Well done on wrapping a really tricky API!

**Comment by erdewit** [comment]
Thanks Chris, and to our AI overlords.
