### ISSUE TITLE
real time bars to df issue

### ISSUE THREAD

**Issue by dccw** [erdewit/ib_insync#57]
Hello

I got the error "'BarData' object has no attribute 'tuple'" when doing the following:

`bars = ib.reqHistoricalData(
        contract_fut,
        endDateTime='',
        durationStr='60 S',
        barSizeSetting='5 secs',
        whatToShow='TRADES',
        useRTH=True,
        formatDate=1,
        keepUpToDate=True)

util.df(bars)`

Grateful for advice.

**Comment by erdewit** [comment]
This was a bug in the historicalDataUpdate wrapper and has been fixed in the 0.9.9 release.
