### ISSUE TITLE
No module named 'EventKit'

### ISSUE THREAD

**Issue by luketych** [erdewit/ib_insync#573]
running macOS 13.3 (m1), python latest version 3.11

When importing eventkit or ib_insync:

```
Exception has occurred: ModuleNotFoundError       (note: full exception trace is shown but execution is paused at: <module>)
No module named 'EventKit'
  File "/Users/me/poetry/projects/ibReader/src/IBApp/__init__.py", line 3, in <module>
    import eventkit
  File "/Users/me/poetry/projects/ibReader/src/__main__.py", line 20, in <module>
    from src.IBApp import IBApp
  File "<string>", line 1, in <module> (Current frame)
ModuleNotFoundError: No module named 'EventKit'
```

eventkit is installed

**Comment by gzeid** [comment]
open the file `/Users/me/poetry/projects/ibReader/src/IBApp/__init__.py` and replace `import eventkit` with `import EventKit`

**Comment by luketych** [comment]
still the same issue. Not sure what's happened here.

**Comment by fusillijerry89** [comment]
I had a similar issue before. Now sure what was going on.

**Comment by erdewit** [comment]
On macOs there can be a python wrapping of Apple's own Eventkit library installed, which causes a name clash. This wrapping can be deinstalled.
