### ISSUE TITLE
"ConnectionError: Socket disconnect" on reqHistoricalData

### ISSUE THREAD

**Issue by Yuvalya5** [erdewit/ib_insync#574]
Hi, I'm trying to get Historical Data of QQQ and somehow on random times this error is being raised.

The code is:
stock_symbol_contract = Stock(symbol, 'SMART', 'USD')
current_historical_data = ib_client.reqHistoricalData(
    stock_symbol_contract,
    '',
    barSizeSetting='30 mins',
    durationStr='{0} D'.format(days_from_now),
    whatToShow='TRADES',
    useRTH=True
)

The error  is:
ConnectionError: Socket disconnect (in the reqHistoricalData)
Thanks in advance :)

**Comment by erdewit** [comment]
Happens when some request pace limit is exceeded.
