### ISSUE TITLE
scaleTable

### ISSUE THREAD

**Issue by michagruner** [erdewit/ib_insync#582]
Hi, 

first: thank you very much for providing this API. It is very easy to use.

I'm not a very good (python) developer. I just build a small web-App that takes a stop and a high probability target and a risk multiple to calculate an entry price that would suit these parameters and then submits the trades to the TWS. It's available under https://github.com/michagruner/IB-trade-generator/tree/master .

As we all know having more than two specific take profits is not that easy to achieve with TWS. So I looked into the API and stumbled accross the property "scaleTable" and I wondered what this is. The official documentation about this is not very helpful and there is not one example I could find for how to use it. So I tried to execute a scale order and get the properties of that order. However, no matter the execution status of the order the field was empty.

So I did search a little bit in the code base of ib_sync and tried to figure out what could be wrong. I tried to find differences between the properties "scaleInitLevelSize" (which obviously works fine) and scaleTable. The only difference I found between the two is that scaleTable doesn't show up in decoder.py while "scaleInitLevelSize" does. Could that be a reason it always returns an empty string? How could I debug what is returned for scaleTable from TWS?

Thank you very much for any advise, Michael.

**Comment by erdewit** [comment]
> How could I debug what is returned for scaleTable from TWS?

It isn't returned, that's why it's not in decoder.py
