### ISSUE TITLE
Unable to connect with expired ITM option

### ISSUE THREAD

**Issue by huanxiliu99** [erdewit/ib_insync#584]
I have been using the thread to connect my real money account with thread

> from matplotlib import pyplot as plt
> import math
> import pandas as pd
> import numpy as np
> 
> from ib_insync import *
> util.startLoop()
> util.logToConsole('DEBUG')
> ib = IB()
> #make sure only one cliendID can run at a time, you can allow multiple cliendId to run at the same time
> #when using 7497, only log into PAPER account,7496 for REAL MONEY
> ib.disconnect()
> ib.connect('127.0.0.1', 7496, clientId=1, timeout = 10)

but whenever I have expired option that I did not close, I am unable to connect. Whenever it passes 12am EST, I can connect. 
I have attached the log here, it would stuck on the last few numbers "7,3,2,0,,,,,," and then show timeout. I have extended timeout but still unable to connect. Any potential solutions? Thanks a lot really enjoy the work you do!

![image](https://user-images.githubusercontent.com/55967944/236108804-9b100488-948d-4e24-9666-ff657d5f666b.png)

**Comment by erdewit** [comment]
It seems TWS has issues uploading the portfolio. Not much I can do about that, better ask IB.

**Comment by huanxiliu99** [comment]
Thanks a lot for explaining!  Appreciate your work!
