### ISSUE TITLE
Broken link in references

### ISSUE THREAD

**Issue by ClimberMel** [erdewit/ib_insync#587]
There are a few places in the code comments that reference "https://interactivebrokers.github.io/tws-api/fundamental_ratios_tags.html".  That page is gone.  I can find the page on the Internet Archive, so it was there, but not now.  Do we need to create data to replace that, or ask IB if they have plans to provide it in their documentation?

**Comment by erdewit** [comment]
The fundamental ratios is officially deprecated. The link has been removed.
