### ISSUE TITLE
issue with adaptive order

### ISSUE THREAD

**Issue by xabaddonx1** [erdewit/ib_insync#594]
I am trying to create an adaptive market order via the API but it always creates the order as a regular MKT order when I look in TWS. I can create the same order manually in TWS as adaptive so it should be possible.

creditSpread, strikeDiff, spreadPrice = self.createCreditSpreadContract(contract)
order = MarketOrder('BUY', totalQuantity=self.getQuantity(curPrice), algoStrategy='Adaptive', algoParams=[TagValue('adaptivePriority', 'Normal')], tif="DAY") 
trade = self.ib.placeOrder(creditSpread, order)

Any ideas what could be wrong?

**Comment by 805karansaini** [comment]
It looks fine to me. You can try printing out the order object after it is created to verify that the algoStrategy and algoParams parameters are set correctly.

Do check if your Interactive Brokers account may not have the necessary permissions to use the Adaptive Algo. You can check your account settings in TWS to ensure that you have the necessary permissions.
