### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mdelvaux** [erdewit/ib_insync#6]
I think there is a typo for a logger expression, line 136 in wrapper.py, it should be exception instead of execption.

    def _handleEvent(self, eventName, *args):
        # invoke optional callback
        cb = self._callbacks.get(eventName)
        if cb:
            try:
                cb(*args)
            except Exception:
                _logger.execption('Event %s(%s)', eventName, args)

**Comment by erdewit** [comment]
Thanks for mentioning this, it has been fixed.
