### ISSUE TITLE
ib.reqCurrentTime() infinite loop

### ISSUE THREAD

**Issue by peachy88** [erdewit/ib_insync#604]
I am using ib.reqCurrentTime() to ensure that script is connected to IB. 
ib.isConnected() will return true when script initially connected, but then IB Gateway was restarted.
```

def myibconnect():
    try:
        if not ib.isConnected() : ib.connect('127.0.0.1', 4001, clientId=1, timeout=10)
        #catch connection errors getting time from client. so even if it shows connected, it will show if it's broken
        print("IB Time : ",ib.reqCurrentTime())
    except:
        print("NOT CONNECTED")


myibconnect()
orgcontract = Stock("TTEC","SMART","USD")
ib.qualifyContracts(orgcontract)
print("IB Time : ",ib.reqCurrentTime())
print("HELLO")
```

After upgrading to IB Gateways 10.19 this will hang forever. It never reaches the print("HELLO") statement.

**Comment by erdewit** [comment]
The issue can be simplified to

```python
print("IB Time : ",ib.reqCurrentTime())
print("IB Time : ",ib.reqCurrentTime())
```

which hangs on the second request.

This is due to some limitation in TWS that there must be at least one second between time requests. So this does not hang:

```python
print("IB Time : ",ib.reqCurrentTime())
ib.sleep(1)
print("IB Time : ",ib.reqCurrentTime())
```
