### ISSUE TITLE
ocaGroup - inconsistence between TWS and ib_insync 

### ISSUE THREAD

**Issue by Plumakeem** [erdewit/ib_insync#606]
TWS 10.22, ib_insync 0.9.85

I've got some problems with the ocaGroup of my trades:

Create a buy-order with an attached stop-loss. Set the ocaGroup of the attached stop-loss to a custom value, eg. "test1". Transmit the orders. Problem: ib_insync says the ocaGroup is "test1" when querying the Trade object with openTrades(), TWS shows a different value eg. "1234567890" (the next order id number regarding to the TWS API documentation). After restarting TWS and ib_insync both say that "1234567890" is the ocaGroup of the attached stop-loss. The inconsistency continues after the order got filled, as TWS then sets the ocaGroup to "test1" and ib_insync - unless being restarted again - still has the wrong "1234567890" as ocaGroup.

I'm not sure whether this is a problem of TWS as it reports the "wrong" ocaGroup while the parent order has not yet been filled, or if it's an syncronisation error of ib_insync, as it needs to be restarted to report the same as TWS does. I'd be happy if ib_insync was in-sync with TWS all the time, especially when the parent order was filled as I'd like to use the ocaGroup to set further orders at this point.

**Comment by erdewit** [comment]
It seems that it's TWS that is ignoring the name of the ocaGroup, so I don't believe this is an issue with ib_insync.
