### ISSUE TITLE
ib.reqMatchingSymbols fails to get search data

### ISSUE THREAD

**Issue by tomsaso** [erdewit/ib_insync#608]
Searching for AAPL logs this error
![image](https://github.com/erdewit/ib_insync/assets/33942721/94869ed5-836a-4ccd-870d-f973e9778f28)

```
def symbolSamples(self, fields):
        _, reqId, n, *fields = fields

        cds = []
        for _ in range(int(n)):
            cd = ContractDescription()
            cd.contract = c = Contract()
            c.conId, c.symbol, c.secType, c.primaryExchange, c.currency, \
                m, *fields = fields
            c.conId = int(c.conId)
            m = int(m)
            cd.derivativeSecTypes = fields[:m]
            fields = fields[m:]
            if self.serverVersion >= 176:
                (
                    cd.contract.description,
                    cd.contract.issuerId,
                    *fields) = fields
            cds.append(cd)

        self.wrapper.symbolSamples(int(reqId), cds)
```

As far as I can check is somewhere in this method symbolSamples. For some reason it thinks that the first item in the fields is actually a contract id, while in this case is the company name 'AAPLE INC'

Now is this library issue, TWS API version issue, I don't know. I have to research. 

Did IBRK Change how they deliver the data for symbolSearch ? I would not be surprised as it is a relatively new feature.

I am running TWS 1019 on IBC Controller & watchdog. Trying to search for symbols and get a list back.

Can you provide a fix, or can you at least point me in the right direction and I will try to do it myself?

**Comment by erdewit** [comment]
It works for me with TWS 1023. This version will be the minimum required by IB in a couple of weeks.
