### ISSUE TITLE
Dividends Payment Schedule

### ISSUE THREAD

**Issue by atamkapoor** [erdewit/ib_insync#615]
I am looking to pull IB's dividend projections for a stock/ETF. I can see this information when I hover over the "Dividend Yield %" column for the ticker in my TWS watchlist/monitor, but don't know how to pull this information through ib_insync .

For example (today's date = 13-Jul-2023): 
![IB Dividend Projection](https://github.com/erdewit/ib_insync/assets/29904583/4adfc819-5460-49c0-85cf-2854e15e5055)

**Comment by erdewit** [comment]
This can be done with ``reqMktData`` with generic tick 456:

https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.reqPnL
