### ISSUE TITLE
PNL Issue

### ISSUE THREAD

**Issue by EngAhmedElkady** [erdewit/ib_insync#618]
when try to return pnl , give me this Daily PnL:  [PnL(account='my account number', modelCode='', dailyPnL=nan, unrealizedPnL=nan, realizedPnL=nan)]

why the dailyPnl is nan, this is code  pnl = self.ib.pnl()

**Comment by erdewit** [comment]
Call this method first:

https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.reqPnL
