### ISSUE TITLE
Trade orderStatus not updated

### ISSUE THREAD

**Issue by vertangelx** [erdewit/ib_insync#62]
My code is running outside of a Jupyter notebook. When it places an order 

    trade = ib.placeOrder(contract, order)

calling `trade.orderStatus.status` after `ib.sleep(10)` or `ib.sleep(30)` always shows that the order is `PendingSubmit`

I think this might be because my code is not running in a Jupyter notebook where you used `util.startLoop()` to continuously update the trade's order status?

How can we get the updated `orderStatus.status` when not using Jupyter notebook?

**Comment by erdewit** [comment]
ib.sleep should do the trick, you sure you didn't use time.sleep?

**Comment by wyxr** [comment]
I have this problem too, and I haven't solved it. Can you give me some advice
