### ISSUE TITLE
orders stuck in PendingSubmit

### ISSUE THREAD

**Issue by 430scud** [erdewit/ib_insync#623]
Anyone run into this issue and know how to resolve? I'm trying to build some Flask endpoints for ease of trading on my end, using the ib-insync Python package, but my orders never get submitted, even though I'm fairly sure the parameters are correct. I can place orders just fine on the GUI, 
but even copying over the exact same parameters, the orders go through but always end up with PendingSubmit status. They are then stuck in open orders until I restart the app, never reaching Submitted status.

Here's one example, for buying some Google stock:
```
@app.route('/test-trade', methods=['GET'])
async def test_trade():
    contract = Stock(conId=208813719, symbol='GOOGL', exchange='NASDAQ', currency='USD', localSymbol='GOOGL', tradingClass='NMS')
    order = MarketOrder('BUY', 2)
    trade = ib.placeOrder(contract, order)

    print(trade.log)
    print('---------------------------------------------------------------')
    print(trade.orderStatus)
    print('---------------------------------------------------------------')
    print(ib.trades())

    if trade.orderStatus.status == 'Submitted':
        print(f"Order submitted: {trade}")
    else:
        print(f"Failed to submit order: {trade}")

    return jsonify({"trade_log": trade.log}), 200

if __name__ == '__main__':
    import asyncio

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

    app.run(host='0.0.0.0', port=5000)
```

If I run this, I get this in console:

[TradeLogEntry(time=datetime.datetime(2023, 8, 9, 17, 7, 57, 976911, tzinfo=datetime.timezone.utc), status='PendingSubmit', message='', errorCode=0)]
---------------------------------------------------------------
OrderStatus(orderId=896049, status='PendingSubmit', filled=0.0, remaining=0.0, avgFillPrice=0.0, permId=0, parentId=0, lastFillPrice=0.0, clientId=0, whyHeld='', mktCapPrice=0.0)
---------------------------------------------------------------
[Trade(contract=Stock(conId=208813719, symbol='GOOGL', exchange='NASDAQ', currency='USD', localSymbol='GOOGL', tradingClass='NMS'), order=MarketOrder(orderId=896049, clientId=998, action='BUY', totalQuantity=2), orderStatus=OrderStatus(orderId=896049, status='PendingSubmit', filled=0.0, remaining=0.0, avgFillPrice=0.0, permId=0, parentId=0, lastFillPrice=0.0, clientId=0, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(time=datetime.datetime(2023, 8, 9, 17, 7, 57, 976911, tzinfo=datetime.timezone.utc), status='PendingSubmit', message='', errorCode=0)], advancedError='')]

Anyone know what this is because of? I can't seem to figure it out or find any similar solutions. Would really appreciate any suggestions.

**Comment by xozxro** [comment]
Having the exact same issue:

```
self.contract = data.ib.insync_app.qualifyContracts(
            self.contract
        )
self.order = LimitOrder('SELL', order_qty, round(self.limit,2), tif='DAY')
data.ib.insync_app.placeOrder(self.contract, self.order) 
```

I just get:

`Trade(contract=Contract(secType='FOP', conId=647837223, symbol='NQ', lastTradeDateOrContractMonth='20230816', strike=15140.0, right='C', multiplier='20', exchange='CME', currency='USD', localSymbol='Q3CQ3 C15140', tradingClass='Q3C'), order=LimitOrder(orderId=179, clientId=456445645, action='SELL', totalQuantity=2.0, lmtPrice=52.86, tif='DAY'), orderStatus=OrderStatus(orderId=179, status='PendingSubmit', filled=0.0, remaining=0.0, avgFillPrice=0.0, permId=0, parentId=0, lastFillPrice=0.0, clientId=0, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(time=datetime.datetime(2023, 8, 16, 2, 9, 58, 680814, tzinfo=datetime.timezone.utc), status='PendingSubmit', message='', errorCode=0)], advancedError='')`

Happens randomly, but when it does, won't go away. Resetting order ID's doesn't help in TWS. Can't seem to figure out the exact cause.

**Comment by erdewit** [comment]
There needs to be some pause after ``placeOrder`` to see how the order is doing. Trading doesn't happen instantaneous.
