### ISSUE TITLE
`openTrades` and `openOrders` don't reflect some manual changes

### ISSUE THREAD

**Issue by Henry-E** [erdewit/ib_insync#625]
`ib.openTrades()` and `ib.openOrders()` don't update to reflect orders that have been manually deleted before being transmitted.

Steps to reproduce
- submit an order with transmit = False
- Manually delete the order in TWS before transmitting it
- check `ib.openTrades()` or `ib.openOrders()` and the orders are still there

It just seems like possibly inconsistent behaviour since transmitting an order manually and then cancelling the order manually does reflect in `openOrders` and `openTrades`, i.e. those manually cancelled orders (after being properly transmitted) are removed from the list of open orders and trades.

Edit: Maybe this is just some issue with the IB API that they don't even provide events related to deleting "non-transmitted" API submitted orders.

Update: You can send a `cancelOrder()` call to cancel a manually deleted order without getting an error message. So this is definitely just an edge case the IB API doesn't even want to think about.

**Comment by erdewit** [comment]
This is a limitation of the API with regards to orders that have never been transmitted.
