### ISSUE TITLE
ib.trades() results change after calling ib.reqAllOpenOrders()

### ISSUE THREAD

**Issue by jakemdrew** [erdewit/ib_insync#628]
I am noticing that in my current IB account, I have a limit order placed from the TWS GUI that only shows up in trades after ib.reqAllOpenOrders() is called.  

**Example:**

```
ib = IBC.connect()
trades = ib.trades()
[t for t in trades if t.contract.localSymbol == 'ASNS']
```
**Returns:**

[Trade(contract=Stock(conId=626259992, symbol='ASNS', right='?', exchange='SMART', currency='USD', localSymbol='ASNS', tradingClass='SCM'), order=Order(orderId=36593, clientId=1, permId=302371717, action='BUY', totalQuantity=5.0, orderType='LMT', lmtPrice=1.14, auxPrice=0.0, tif='GTC', ocaType=3, displaySize=2147483647, outsideRth=True, rule80A='0', openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='DU6019510', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=36593, status='Submitted', filled=0.0, remaining=5.0, avgFillPrice=0.0, permId=302371717, parentId=0, lastFillPrice=0.0, clientId=1, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(time=datetime.datetime(2023, 8, 26, 17, 0, 11, 889763, tzinfo=datetime.timezone.utc), status='Submitted', message='', errorCode=0)])]

**Then only when ib.reqAllOpenOrders() is called:**

```
open_orders = ib.reqAllOpenOrders()`
trades = ib.trades()
[t for t in trades if t.contract.localSymbol == 'ASNS']
```

**The same trades request returns:**

[Trade(contract=Stock(conId=626259992, symbol='ASNS', right='?', exchange='SMART', currency='USD', localSymbol='ASNS', tradingClass='SCM'), order=Order(orderId=36593, clientId=1, permId=302371717, action='BUY', totalQuantity=5.0, orderType='LMT', lmtPrice=1.14, auxPrice=0.0, tif='GTC', ocaType=3, displaySize=2147483647, outsideRth=True, rule80A='0', openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='DU6019510', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=36593, status='Submitted', filled=0.0, remaining=5.0, avgFillPrice=0.0, permId=302371717, parentId=0, lastFillPrice=0.0, clientId=1, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(time=datetime.datetime(2023, 8, 26, 17, 0, 11, 889763, tzinfo=datetime.timezone.utc), status='Submitted', message='', errorCode=0)]),
 Trade(contract=Stock(conId=626259992, symbol='ASNS', right='?', exchange='SMART', currency='USD', localSymbol='ASNS', tradingClass='SCM'), order=Order(permId=1674124202, action='BUY', totalQuantity=5.0, orderType='LMT', lmtPrice=0.95, auxPrice=0.0, tif='GTC', ocaType=3, displaySize=2147483647, rule80A='0', openClose='', volatilityType=0, deltaNeutralOrderType='None', referencePriceType=0, account='DU6019510', clearingIntent='IB', adjustedOrderType='None', cashQty=0.0, dontUseAutoPriceForHedge=True), orderStatus=OrderStatus(orderId=0, status='PreSubmitted', filled=0.0, remaining=5.0, avgFillPrice=0.0, permId=1674124202, parentId=0, lastFillPrice=0.0, clientId=0, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(time=datetime.datetime(2023, 8, 26, 17, 1, 30, 725609, tzinfo=datetime.timezone.utc), status='PreSubmitted', message='', errorCode=0)])]

It appears that ib.trades() is now returning limit orders from the client permId and from the TWS GUI permId?  Is the behavior expected or a Bug?

**Comment by erdewit** [comment]
> Is the behavior expected or a Bug?

This is expected behavior.

**Comment by jakemdrew** [comment]
A documentation update for reqAllOpenTrades() would be helpful. Thank you!Sent from my iPhoneOn Aug 26, 2023, at 12:33 PM, Ewald de Wit ***@***.***> wrote:﻿

Is the behavior expected or a Bug?

This is expected behavior.
