### ISSUE TITLE
List of Trades and its session

### ISSUE THREAD

**Issue by vertangelx** [erdewit/ib_insync#63]
In the [API docs](https://rawgit.com/erdewit/ib_insync/master/docs/html/api.html#ib_insync.ib.IB.trades), the `trades()` function returns a "List of all order trades from this session". How is a session defined or identified? Is it possible to manually start and end a session?

For every Trade objects returned by `trades()`, `Trade.contract` appear to be either a `Contract` object or not a `Contract` object. Usually all Trade.contract are `Contract` objects except for one which is can be a `Stock` object. Can you explain? Thank you very much.

**Comment by erdewit** [comment]
The session is determined by IB, it roughly ends at midnight. So the list of trades that is sent is of the current trading day.

The contract of trades from previous connections will be of type Contract, but if the order was placed by the current connection then the resulting trade will use the exact same contract object used in placeOrder (which can be Stock). In a next connection it will be Contract again.
