### ISSUE TITLE
how to receive bars in background?

### ISSUE THREAD

**Issue by avatarstones** [erdewit/ib_insync#633]
For the examples in 
[github.com/erdewit/ib_insync/blob/master/notebooks/bar_data.ipynb
](url)

After running 

`ib.sleep(30)`

what should I do if I want to run other commands during this 30 seconds?
In other words, how to run the waiting for data process 
`ib.sleep(30)`
in background?

Thanks for your help!

**Comment by erdewit** [comment]
Instead of ``ib.sleep`` there can be a loop that issues requests, for example for historical data. The realtime bars will still keep coming in.
