### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by TreKar99** [erdewit/ib_insync#635]
Hey guys, im trying to work on error handling, because the wrapper errors are too extensive:

>     Error 321, reqId 194: Error al validar la solicitud.-'bS' : causa - El tama\u00f1o de la orden no se ajusta a la normativa del mercado.
>  Canceled order: Trade(contract=Stock(symbol='AMZN', exchange='SMART', currency='USD'), order=MarketOrder(orderId=194, clientId=1, action='BUY', totalQuantity=100000000000), orderStatus=OrderStatus(orderId=194, status='Cancelled', filled=0.0, remaining=0.0, avgFillPrice=0.0, permId=0, parentId=0, lastFillPrice=0.0, clientId=0, whyHeld='', mktCapPrice=0.0), fills=[], log=[TradeLogEntry(time=datetime.datetime(2023, 8, 29, 17, 39, 41, 26849, tzinfo=datetime.timezone.utc), status='PendingSubmit', message='', errorCode=0), TradeLogEntry(time=datetime.datetime(2023, 8, 29, 17, 39, 41, 26849, tzinfo=datetime.timezone.utc), status='Cancelled', message="Error 321, reqId 194: Error al validar la solicitud.-'bS' : causa - El tama\u00f1o de la orden no se ajusta a la normativa del mercado.", errorCode=321)], advancedError='')

Is there any form to catch errors with the IB object like in official IBAPI?

>     def error(self, reqId, errorCode, errorString):
>     # 502: Error Socket o 504: No está conectado
>     if(errorCode == 502) or (errorCode == 504):
>     print("ERROR: Fallo de conexión - Comprobar sockets TWS")
>     exit()
>     elif(errorCode not in self.goodErrors):
>     print("Error {} {} {}".format(reqId,errorCode,errorString))
>     #self.disconnect()

PD: i posted also that on discussions, but i didnt get any response, my bad.

**Comment by erdewit** [comment]
> Is there any form to catch errors with the IB object like in official IBAPI?

That can be done by connecting a handler to IB.errorEvent.

**Comment by TreKar99** [comment]
I'm working on that. I'm using your example of #134:
`ib.errorEvent += onError`
But i want to substitute completely the error message. I mean, put by own error message, like this
![image](https://github.com/erdewit/ib_insync/assets/101529212/595aa24a-d537-4942-a5af-ba2f0cde5a2b)
