### ISSUE TITLE
"cancelOrder: Unknown orderId"

### ISSUE THREAD

**Issue by cindymenp** [erdewit/ib_insync#636]
I have a code that places a parent and child order with orderId's assigned by ib.client.getReqId(). Some time later I cancel the parent with ib.cancelOrder() and the child automatically gets cancelled as well. I repeat this process in a loop. Every iteration the code outputs "cancelOrder: Unknown orderId 23782". The number varies every time. What is the reason of this message and can I prevent it and save time?

**Comment by erdewit** [comment]
No idea.
