### ISSUE TITLE
JEFFALGO order produces "Error 145, reqId 231: Error in validating entry fields -"

### ISSUE THREAD

**Issue by NoSpaghettiCode** [erdewit/ib_insync#643]
Using version 0.9.85 and IB TWS Build 10.19.2d, Aug 30, 2023 3:51:59 PM. Ubuntu 22.

This simple code reproduces the issue (I have tried many different variations of which TagValues to use and which not and with no difference):

order = LimitOrder('SELL', 200, 370.1)
order.algoStrategy = "DS"
order.algoParams = [TagValue("RelativeLimit", 5.0)]

order.account = 'U123456'
order.orderRef = 'TESTING'
 
stock_test = Stock('MSFT', 'JEFFALGO', 'USD')
 
trade = ib.placeOrder(stock_test, order)
 

For some JEFFALGO order types, I can get it to work though, e.g. this will work in above example:

order.algoStrategy = "BLITZ"

--------------

I can create DS JEFFALGO orders just fine using TWS. I have looked into the API log and tried to compare vs. audit trail, but it is tricky to see exactly what is wrong. Thanks in advance.

**Comment by erdewit** [comment]
This is an excellent question to ask the IB help desk.
