### ISSUE TITLE
Replacement for += while subscribing for events

### ISSUE THREAD

**Issue by Roh-codeur** [erdewit/ib_insync#648]
Hi

this is an awesome library, thanks a lot for putting this together. 

Qq: I am using this library from Julia using Pycall. It all works great, however, I can’t subscribe to the events. From the notebooks it appears that I can do it using +=. I can’t seem to find a way to do that from Julia using Pycall. 

Is there an alternative to using that operator to subscribe to events pls?

thanks
Roh

**Comment by erdewit** [comment]
Use .connect(...) instead of the += shortcut.

**Comment by Roh-codeur** [comment]
@erdewit thanks a lot for the quick response
