### ISSUE TITLE
Request historical trades with keepUpToDate

### ISSUE THREAD

**Issue by Roh-codeur** [erdewit/ib_insync#653]
Hi

thanks for all your work on this. 

I am using the below code to subscribe to historical Trades and keepThemUpToDate. I see historical trades, I don't however, see any updates to that. I have tried both barUpdateEvent and updateEvent. Do you know whereI could have gone wrong please? or is this not supported? also, I am using Paper account. I did, however, tried placing orders which got filled. so, presumably, that should have triggered a response.

```
    contract = Stock("AAPL", "SMART", "USD")
    def onBarUpdate(bars, hasNewBar):
        if hasNewBar:
            print(util.df(bars))
        else:
            print("No new bars")
    ib.positions()
    bars = ib.reqHistoricalData(
        contract,
        endDateTime='',
        durationStr='1 D',
        barSizeSetting='5 secs',
        whatToShow='TRADES',
        useRTH=False,
        keepUpToDate=True,
        formatDate=1)

    print(util.df(bars))
    # ib.barUpdateEvent += onBarUpdate
    ib.barUpdateEvent += onBarUpdate
    bars.updateEvent += onBarUpdate

```

thanks
Roh

**Comment by Roh-codeur** [comment]
Update: if I use the below code, for stocks, I tried NSE stocks, AAPL etc, and it seems to work for those. I can see the bid/offer along with sizes and ohlcv. I am a tad confused, as to why the above call doesnt work. 

```
def req_mkt_data_pending_ticker_event_for_stocks():
    contracts = [Stock("TATAMOTOR")]
    contracts = ib.qualifyContracts(*contracts)

    eurusd = contracts[0]
    df = pd.DataFrame(
        index=[c.symbol for c in contracts],
        columns=['bidSize', 'bid', 'ask', 'askSize', 'high', 'low', 'close'])

    print(eurusd)
    for contract in contracts:
        ib.reqMktData(contract, '', False, False)

    def onPendingTickers(tickers):
        for t in tickers:
            df.loc[t.contract.symbol] = (
                t.bidSize, t.bid, t.ask, t.askSize, t.high, t.low, t.close)
        print(df)

    ib.pendingTickersEvent += onPendingTickers

```

**Comment by cgntiger** [comment]
```
def onBarUpdate(bars, hasNewBar):
    if hasNewBar:
        print(bars)
    else:
        print("No new bars")

bars = ib.reqHistoricalData(
    contract,
    endDateTime='',
    durationStr='60 S',
    barSizeSetting='5 secs',
    whatToShow='TRADES',
    useRTH=False,
    keepUpToDate=True,
    formatDate=1)

ib.barUpdateEvent += onBarUpdate
ib.run()

```
durationStr你设置一天，我怀疑是数据量太大，盈透不给了，或者处理不了五秒获取一天的数据
我记得获取数据有限制来着

**Comment by cgntiger** [comment]
获取数据的限制：https://interactivebrokers.github.io/tws-api/historical_limitations.html
durationStr=1D，barSizeSetting的范围要在1min~1D

**Comment by cgntiger** [comment]
![image](https://github.com/erdewit/ib_insync/assets/42635834/64b0eaae-d758-494a-ac61-fe7f6cfffeff)

**Comment by Roh-codeur** [comment]
@cgntiger : you, my friend, are a Star! thanks for this. I will try out with the 1min~1day. 

thanks a lot!

**Comment by erdewit** [comment]
The proper data subscriptions are needed, or else delayed data can be used with ``ib.reqMarketDataType(3)``.
