### ISSUE TITLE
CFD Contract

### ISSUE THREAD

**Issue by Muzika29** [erdewit/ib_insync#657]
Hi. I can't create a CFD contract :

INPUT : 
contract = CFD(symbol='USDCHF', exchange='SMART', currency='CHF')
bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='30 D',
    barSizeSetting='30 mins', whatToShow='MIDPOINT', useRTH=True)

OUTPUT :
Error 200, reqId 3: No security definition has been found for the request, contract: CFD(symbol='USDCHF', exchange='SMART', currency='CHF')

I also tried this way : 

INPUT : 
contract = Contract(conId=230949815, exchange='SMART')
bars = ib.reqHistoricalData(
    contract, endDateTime='', durationStr='30 D',
    barSizeSetting='30 mins', whatToShow='MIDPOINT', useRTH=True)

OUTPUT : 
reqHistoricalData: Timeout for Contract(conId=230949815, exchange='SMART')
Error 366, reqId 3: No historical data query found for ticker id:3, contract: Contract(conId=230949815, exchange='SMART')

I don't understand..

**Comment by mattsta** [comment]
Are you sure `USDCHF` is a `CFD` and not a `Forex`?

`Forex("CHFUSD")` and `Forex("USDCHF")` works for me. IBKR doesn't list `USD`/`CHF` pairs as CFDs, but they are listed under Forex.

You can always search for IBKR contracts at https://contract.ibkr.info/v3.10/index.php too.

**Comment by Muzika29** [comment]
Yes i'm sure. Here's you can check this out : 

https://contract.ibkr.info/v3.10/index.php?action=Conid Info&wlId=IB&conid=230949815&lang=en&ib_entity=

That's why i tried the second time directly with the contract ID (conId)

**Comment by skalaydzhiyski** [comment]
same here I cant' create ANY CFD contract, it just times out or sais it cannot find the contract. I love ib_insync and no idea why this is happening :(

**Comment by skalaydzhiyski** [comment]
Error 366, reqId 15: No historical data query found for ticker id:15, contract: CFD(conId=120549668, symbol='NVDA', exchange='SMART', currency='USD', localSymbol='NVDAn', tradingClass='NVDA')

**Comment by erdewit** [comment]
I think IB doesn't have historical data for any CFDs, including index CFDs.
