### ISSUE TITLE
Historical data for FUT does not have open_interest

### ISSUE THREAD

**Issue by nwillemse** [erdewit/ib_insync#66]
Ewald,

When I am requesting historical data for ES contract on GLOBEX, I do not see the open_interest column.  These are the only columns available:

`Index(['date', 'open', 'high', 'low', 'close', 'volume', 'barCount', 'average'])`

I'm using this code:

`bars = ib.reqHistoricalData(contract, endDateTime=dt, durationStr='70 D', barSizeSetting='1 day', whatToShow='TRADES', useRTH=True)`

**Comment by erdewit** [comment]
Not sure what makes you think that IB has historical open interest available.
