### ISSUE TITLE
There is no current event loop in thread 'Thread-x'.

### ISSUE THREAD

**Issue by mgobi** [erdewit/ib_insync#67]
Thanks for your great work on ib_insync. I would like to use ib_insync with Django. However, when I call the python ib_insync code from a Django view there will be an error: "There is no current event loop in thread 'Thread-147'"

I hope you have an idea on how this can be fixed?

best regards,
M

**Comment by erdewit** [comment]
The Django server does not cooperate with asyncio-based applications such as ib_insync. It should however be possible to use a Django WSGI app + Tornado webserver with asyncio loop.

**Comment by mgobi** [comment]
thanks, I will give it a try
