### ISSUE TITLE
Why is it not possible to get the historical data of the META

### ISSUE THREAD

**Issue by jxhuliqun138** [erdewit/ib_insync#673]
contract = Stock(“TSLA”, exchange='SMART', currency='USD')
constructing the contract as above. 
TSLA, GOOG can get the data fine, but META, BSC, etc. can't.

**Comment by LunarSilhouette** [comment]
hello,
For certain stocks, like META, the primary exchange must also be specified.
`Stock('META','SMART','USD',primaryExchange=‘NASDAQ’)`
