### ISSUE TITLE
Pending Order not found.

### ISSUE THREAD

**Issue by kaidaniel82** [erdewit/ib_insync#674]
I manually added a bracket order to an existing position using TWS. This position is synchronized across multiple devices, so it resides on the IB server.

Since it's the weekend, this bracket order is marked as "Held and being monitored," which is visible on multiple devices.

When I try to find this order using ib_insync, it does not appear.

I tried:
ib.orders()
ib.trades()
ib.openOrders()
....

Is also wrote Issue #39

Is this a gap in the API?

Best regards.

**Comment by kaidaniel82** [comment]
looks like with client_id = 0 its working, but that seems to be not ideal.

**Comment by biney59** [comment]
This is a a limitation of _TWS_, and not _ib_insync_ I beleive, according to [their API](https://interactivebrokers.github.io/tws-api/open_orders.html#:~:text=If%20client%200%20invokes%20reqOpenOrders%2C%20it%20will%20cause%20currently%20open%20orders%20placed%20from%20TWS%20manually%20to%20be%20%27bound%27%2C%20i.e.%20assigned%20an%20order%20ID%20so%20that%20they%20can%20be%20modified%20or%20cancelled%20by%20the%20API%20client%200.).
