### ISSUE TITLE
Contract can't be hashed

### ISSUE THREAD

**Issue by jjharr** [erdewit/ib_insync#676]
I'm using ib_insync-0.9.86, which is the current version as of today.

Error is:

ValueError: Contract Stock(symbol='TZA', exchange='SMART', currency='USD') can't be hashed

To reproduce:

```
    hist = ib.fetch_history(Stock('AMD', 'SMART', 'USD'),
                    datetime.datetime(2023, 12, 21, 0, 0, 0, tzinfo=zoneinfo.ZoneInfo('America/New_York')),
                    duration_str = '1 day',
                    bar_size = '1 secs',
                    )
```

**Comment by mattsta** [comment]
Where is `fetch_history` from?

You're probably trying to use `Stock()` as a dict key, but the `Stock` classes aren't frozen/immutable, so they can't be used as dict keys.

Simplest solution is to index by symbol only, or you can combine `(symbol, exchange, currency)` into a tuple for indexing your results too.
