### ISSUE TITLE
Notebook cells are pending after connection to TWS

### ISSUE THREAD

**Issue by enricoangelelli** [erdewit/ib_insync#688]
This is a problem I have with any notebook using a  ib_insync connection to TWS. I report a minimal example.

After executing cell

```Python
import ib_insync
ib_insync.util.startLoop()
ib = ib_insync.IB()
ib.connect('127.0.0.1', 7497, clientId=11)
contract = ib_insync.Stock('AMZN', 'SMART', 'USD')
ib.qualifyContracts(contract)
display(contract) 
ib.disconnect()
```
the next cell

```Python
print("Hello")
```
remains pending. I cannot even execute again the same cell.

Thank you in advance for any help.

Enrico

**Comment by RGLDN** [comment]
try replacing `display(contract)` with `print(contract)`

**Comment by enricoangelelli** [comment]
I tried, but unfortunately it does not work.

**Comment by erdewit** [comment]
You can try upgrading to the latest ``nest_asyncio``.

**Comment by enricoangelelli** [comment]
Yeeeessss! It works. Thank you very much!
