### ISSUE TITLE
Example in README.rst doesn't work in read-only mode

### ISSUE THREAD

**Issue by perpetualcrayon** [erdewit/ib_insync#7]
I've got my API access in IB set to read-only mode.  The example script, when run, warned me that the call could not be satisfied in read-only mode.

However, the example appears to be a request for historical data, which as far as I know shouldn't require write access.

**Comment by erdewit** [comment]
Also see #1 

Since you are the second person I have removed the reqOpenOrders call. Be sure to check 'Download open orders on connection' option in TWS.

**Comment by perpetualcrayon** [comment]
Thanks for the link.  I noted, during my own troubleshooting, that the issue was occuring during "connect", which I did not mention in my original comment above.  I actually wrote a much longer addendum to my first note which I never submitted once I figured this out, but my general rule has always been don't try to clutter the bug reports if it's not necessary :)

Thanks

**Comment by lJoublanc** [comment]
Probably worth documenting this in the README i.e. that there is a read-only option, and that you need to **un**check the option 'download open orders' in settings.
