### ISSUE TITLE
ib.ticker(mystock).time in while loop

### ISSUE THREAD

**Issue by dccw** [erdewit/ib_insync#70]
Hi, the ticker time i got from the following seems problematic (same time reported in different iterations)

while 1:
    print(ib.ticker(mystock).time)
    sleep(1)

I am running from Sypder. Thanks

**Comment by erdewit** [comment]
The ticker.time is the time that the ticker was last updated. If it's not updated it stays the same. Also make sure to use ib.sleep, not time.sleep.

**Comment by dccw** [comment]
Thanks. I should have used ib.sleep. But does ib.sleep work with threading? i tried doing an infinite while loop where the script includes ib.sleep but there seems to be only one execution instead of infinite.
