### ISSUE TITLE
Question: Weekly Log In/2 Factor Authentication?

### ISSUE THREAD

**Issue by mr-september** [erdewit/ib_insync#703]
I see that many other users/developers have this unsolvable challenge that IBKR logs users out once every week, requiring a full log in with 2FA (on mobile phone). I couldn't find any mention of this in the readme nor documentation.

Has this project found a solution to that? Or is it also a shared limitation?

**Comment by mattsta** [comment]
I think there's 2.5 common solutions seem to be:

- live with it expiring every week (it _also_ expires any time during the week if your IP address changes between gateway restarts!)
- ask IBKR to disable 2FA requirements on your account, but then you are responsible for any security problems yourself
  - then, with 2FA disabled, you can use one of the UI automation helpers to re-enter your username/password during the weekly saved-session-token rejection to re-login.

Depends on your needs overall. There's not a clean way to run a 100% unmanaged IBKR gateway system without disabling 2FA which opens up other problems. Or, you can attempt to use the UI restart password filling automation and just remember to be near your phone for remote authorization anytime it restarts (assuming it restarts on a proper schedule and not at random times during outages).

**Comment by mr-september** [comment]
Thanks. From some other sources on the internet there are 2 other workarounds, to various degrees of reliability and security:
1. Ibeam github repository
2. Adding a second user to your IBKR account with trading permissions to the linked account, which _apparently_ does not need 2FA. Still need to deal with automated re-log-ins, but that's easier.

Still a bit of a toss-up between self-hosted servers and QC. Hope easier platforms/methods emerge in the future.

I'll close this thread since my questions are answered.
