### ISSUE TITLE
bracketOrder has different transmit values?

### ISSUE THREAD

**Issue by mgobi** [erdewit/ib_insync#71]
Hello, thanks for the great API. I was just discovering bracketOrders and found that my orders are not transmitted. The code explicits transmit=False for the parent and takeprofit part, but a transmit=True for the stopLoss. What would be best to get the entire bracket transmitted? just set them all to transmit=True or is there a particular reason for this setup?

thanks for your consideration,
best regards,
Sbt

parent = LimitOrder(
                action, quantity, limitPrice,
                orderId=self.client.getReqId(),
                transmit=False,
                **kwargs)
        takeProfit = LimitOrder(
                reverseAction, quantity, takeProfitPrice,
                orderId=self.client.getReqId(),
                transmit=False,
                parentId=parent.orderId,
                **kwargs)
        stopLoss = StopOrder(
                reverseAction, quantity, stopLossPrice,
                orderId=self.client.getReqId(),
                transmit=True,
                parentId=parent.orderId,
                **kwargs)

**Comment by erdewit** [comment]
Submit the bracket like:
```python
for o in bracket:
    ib.placeOrder(contract, o)
```

**Comment by mgobi** [comment]
sorry i did not mention that. The submission of the bracket is succesfull, but it shows up with Transmit buttons. So the user will have to click Transmit to actually place the order to the market. Is there an option to send the complete bracket to the market instantly?

![schermafbeelding 2018-06-15 om 10 43 04](https://user-images.githubusercontent.com/34093653/41459182-11fcf0c2-7089-11e8-8015-60542d575be0.png)

**Comment by mgobi** [comment]
thanks. It seems to works, it had to do with the time i was submitting the orders. Outside of office hours.

**Comment by Will695** [comment]
I'm having the same issue, I've got the 
```
for o in bracket:
    ib.placeOrder(contract, o)
   
```
and trading in hours but i still get the transmit button. any help?
