### ISSUE TITLE
Event loses track of all but the first handler assigned to it

### ISSUE THREAD

**Issue by llevar** [erdewit/ib_insync#72]
Code to reproduce issue is here - https://gist.github.com/llevar/72c30f40b95f0c217386beba75fb6b0e

There are multiple event handlers successfully connected to the barUpdateEvent which I can confirm by debugging the Event.connect() method and looking at self.slots. When it comes to firing the event however, only 1 slot is retained (when stepping through Event.fire()) and subsequently only one event handler is called. I did not detect Event.disconnect() being called anywhere so I am not sure what is responsible for the loss of the other event handlers. When more than 2 handlers are registered, only 1 remains active.

**Comment by erdewit** [comment]
By default, the event keeps a weak reference to the event handler. This allows the event handler to get garbage collected, in which case the event will automatically disconnect from it. This is by careful design. You can use ``event.connect(handler, weakRef=False)``  to keep a hard ref to the handler to prevent it from being garbage collected.

**Comment by llevar** [comment]
Can you clarify a bit on this garbage collection? The event handlers are bound to existing objects that are not garbage collected at execution time. What is being garbage collected here, and why? What is the design assumption behind this behaviour that my code is breaking?

**Comment by erdewit** [comment]
There will actually be no references left to your LiveFuturesGetter objects as soon as the tasks are finished.

Btw, the code looks like it could do without any "async def" programming, using just a subscription and the reactive callbacks.

**Comment by llevar** [comment]
Ok, understood, thanks. I have other tasks that request historical data and are long-living. These only create a data subscription so would be gc eligible after the subscription is made. The code I put in the gist is only an excerpt, there are many async tasks that are actually being run, and even within the event handler there is usually an async call to send the bar to an InfluxDB database, so that's the reason for the async calls. I guess the qualifyContracts may not be worth to context switch on since they typically return very fast. Thanks again.
