### ISSUE TITLE
async is a reserved keyword in Python 3.7

### ISSUE THREAD

**Issue by andrushkin** [erdewit/ib_insync#78]
async keyword causes problems as it is a reserved keyword in Python 3.7

for example

`from ibapi.client import EClient`
  `File "Local\Programs\Python\Python37\lib\site-packages\ibapi\client.py", line 60`
    `self.async = False`
             `^`
`SyntaxError: invalid syntax`

**Comment by andrushkin** [comment]
My mistake, this is to do with ibapi and not ib_insync

**Comment by hallgren** [comment]
@andrushkin Did you have to downgrade to a previous version of python to get around this error?

**Comment by andrushkin** [comment]
@hallgren Yep, downgrading to python 3.6 helped get around this

**Comment by tgoodlet** [comment]
@andrushkin @hallgren did anyone bother to submit a patch for this to IB?
They [accepts PRs once you sign their license agreement](http://interactivebrokers.github.io/api_software_contribute.html). If no once else is going to patch it I will.

**Comment by tgoodlet** [comment]
Omg lolz. It's literally an instance variable they don't even use because there's a `TODO` for async support.

**Comment by erdewit** [comment]
It has been fixed in the repo by renaming it to ``asynchronous``: https://github.com/InteractiveBrokers/tws-api/issues/697
