### ISSUE TITLE
bracketOrder functionality

### ISSUE THREAD

**Issue by PeterGardas** [erdewit/ib_insync#79]
Hello
How to use the bracketOrder function to buy stocks? I dont understand the documentation for this particular function. Here is my code:
`
contract = Stock(ticker, 'SMART', 'USD')

#Number of stock i have in portfolio
count = n_stock[ticker]
ib.qualifyContracts(contract)
order = bracketOrder('SELL', count, data['Close'].iloc[0], data['Close'].iloc[0]*1.05, data['Close']*0.9)
for o in order:
    trade = ib.placeOrder(contract, order)
    trade`

**Comment by erdewit** [comment]
Code looks fine to me, not sure what the problem is.

**Comment by PeterGardas** [comment]
The code is supposed to be trade = ib.placeOrder(contract, o)
