### ISSUE TITLE
Can't Request Future Contract's Historical Data

### ISSUE THREAD

**Issue by leochirag** [erdewit/ib_insync#81]
How to request historical data for "ES" Futures ?? 

I am getting the following error when trying to do this:

contract = Future('ES','20180921','GLOBEX')
ib.reqHeadTimeStamp(contract,whatToShow="TRADES", useRTH=True)

<img width="1012" alt="screen shot 2018-07-27 at 3 41 29 pm" src="https://user-images.githubusercontent.com/18371048/43345600-a8eaba0a-91b3-11e8-96e7-0aa284e962ef.png">

Please help with this error. 

Thanks a lot.
Chirag

**Comment by erdewit** [comment]
As the IB error says, you need market data permission for GLOBEX.
