### ISSUE TITLE
market order with a bracket, price issue

### ISSUE THREAD

**Issue by 33327** [erdewit/ib_insync#85]
Hi, what would be the best way to execute a bracket Market order?
I am currently sending Market along with attached bracket for stop&take, but problem I am having is when Market gets filled, the filled price is not the same as execution and my stop&take prices get an offset because of it. 
I guess may have to just send a Market, wait for it for be executed and filled then grab filled priced and then attach a bracket order to the existing one? Or is there some kinda of condition order available in insync? 
Anyways, looking for most efficient way to accomplish it, so that my stop&take are correctly calculated off the total order fill price, thanks.

**Comment by erdewit** [comment]
A better place to ask this is the IB helpdesk.

**Comment by PeterGardas** [comment]
Hey man i have solution, this func sends bracket order with market price
`
def BracketOrder(parentOrderId, childOrderId, action: str, quantity: float, stopPrice: float):

    parent = Order()
    parent.orderId = parentOrderId
    parent.action = action
    parent.orderType = "MKT"
    parent.totalQuantity = quantity
    parent.tif = 'OPG'
    parent.transmit = False

    stopLoss = Order()
    stopLoss.orderId = parentOrderId + 2
    stopLoss.action = "SELL" if action == "BUY" else "BUY"
    stopLoss.orderType = "STP"
    stopLoss.totalQuantity = quantity
    stopLoss.auxPrice = stopPrice
    stopLoss.tif = 'GTC'
    stopLoss.parentId = parentOrderId
    stopLoss.transmit = True

    bracketOrder = [parent, stopLoss]
    return bracketOrder`

**Comment by erdewit** [comment]
> stopLoss.orderId = parentOrderId + 2

Set it to childOrderId otherwise you'll get duplicate orderId later on.

**Comment by PeterGardas** [comment]
When i execute it and then buy it and then sell it so i am at stocks 0, but the sell statement is still there so i will go negative. How to fix that?

**Comment by 33327** [comment]
It's actually Impossible to send a Market order via API and attach bracket orders.

**Comment by PeterGardas** [comment]
Then why is it working for me?

**Comment by 33327** [comment]
In a scenario when you need to send a Market order and then set a order prices with say an offset of 1 dollar for your STOP & TAKE bracket order. Using bracket functionality is not going to work.

I am not certain on what exactly works for you based on the code above.

It will not work in the scenario I have described, because ones parent order is filled you will need to get avgFillprice to calculate Order prices for STOP & TAKE then send correct orders. By the time parent is filled API wont let you attach bracket order to an already filled order and produce and error.

You have to send child orders at the same time with parent thats the only way it will accept them, but at that time you know your fill price.

**Comment by michaelkawaicheung** [comment]
Why is this ticket closed? I can execute a bracket order (with take profit and stop loss) in TWS, so I am expecting the same for this API.

**Comment by PabloCanovas** [comment]
This is not the cleanest as you have to pass the ib object but it does the trick:

`def PlaceBracketMarketOrder(ib, contract, action: str, qty: int, sl_pct: float, tp_pct: float):
    """
    Custom Bracket Order with tp and sl referenced to the avgFillPrice
    For that reason, this function creates the orders AND places the trades
    """
    parent_order = MarketOrder(action, qty)
    parent_trade = ib.placeOrder(contract, parent_order)
    
    while not parent_trade.isDone():
        ib.waitOnUpdate()

    if parent_trade.orderStatus.status != "Filled":
        print("Order cancelled")
        return
      
    fill_price = parent_trade.orderStatus.avgFillPrice

    if action == "BUY":
        sl_pct = -sl_pct
        tp_pct = -tp_pct

    child_action = "SELL" if action == "BUY" else "BUY"

    stop_loss_order = StopOrder(
        action = child_action,
        totalQuantity = qty,
        stopPrice = fill_price * (1 - sl_pct),
        orderId = ib.client.getReqId(),
        transmit = True,
        parentId = parent_trade.order.orderId
    )
    sl_trade = ib.placeOrder(contract, stop_loss_order)

    take_profit_order = LimitOrder(
        action = child_action,
        totalQuantity = qty,
        lmtPrice = fill_price * (1 + tp_pct),
        orderId = ib.client.getReqId(),
        transmit = True,
        parentId = parent_trade.order.orderId
    )
    tp_trade = ib.placeOrder(contract, take_profit_order)

    return [parent_trade, sl_trade, tp_trade]`

**Comment by openSourceBugs** [comment]
none of these answers seem correct. What security or other financial instrument are you placing a bracket order for?
