### ISSUE TITLE
ABOUT THE CONTRACT

### ISSUE THREAD

**Issue by viponedream** [erdewit/ib_insync#96]
ib.barUpdateEvent += onBarUpdate     # 设置回调函数
    spy = Stock('SPY', 'ARCA')
    bars = ib.reqRealTimeBars(spy, 5, "MIDPOINT", True, [])

the bars doesn't include the conid, localsymbol,  because the contract is what we supply ,and we just give him the symbol and exchange. 

but i have a better idea.   all the contract use the complete attr that response by the tws. it need the frame to qualify and replace the contract details  when the contract use in first time .

so  all our operation we can get the full description of that.

**Comment by erdewit** [comment]
The wrapper.realtimeBar response doesn't send any extra contract info.

If you want extra contract info then use for example ib.qualifyContracts.
