### ISSUE TITLE
orderRef= is there a way to check that on an open position ?

### ISSUE THREAD

**Issue by 33327** [erdewit/ib_insync#97]
Having a hard timing figuring out how can I reconfirm that 
1) a pending order
2) an open position 
were sent via API and not any other way like TWS terminal etc

1) I can send orderRef and then I can see under ib.orders() that my orderRef flag is the one I set.
2) I cant figure out what should I query to verify that an open position belongs to my system and was sent via API

Another place I found ib.executions() show it, but when TWS restarted all executions data is lost.

I need a way to be able to verify that an open position belongs to my system at any time even after a disconnect. Is there a way?

Thanks

**Comment by erdewit** [comment]
For a position I don't believe it's possible to see how it was established, other then keeping track of the trades yourself in some sort of database.
